### ISSUE TITLE
Crear Base Datos Testing Backend Examen Online

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#1]
Elias, necesito ir creando la base de datos para el Examen Online. Adjunto te envió el documento que me enviaron desde el área de análisis.

La base tenes que crearla en la siguiente VM: 192.168.33.32

Usuario y contraseña las misma que las de dominio.

PD: Anda guardando todos los query de generación, que cuando este el repositorio los metemos en el mismo.

 
[MODELO ER Backend Examen.docx](https://github.com/leoimoli/Base-De-Datos/files/359358/MODELO.ER.Backend.Examen.docx)

**Comment by EliasWasinger** [comment]
Al conectarme me tira el siguiente error:

**Comment by EliasWasinger** [comment]
La base de datos ya está creada, la estoy revisando por si pasó un error que no vi. Por favor, revisala antes de confirmar el uso.
