### ISSUE TITLE
SINALIC- Update(GLPI 1748)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#10]
Se debe actualizar la licencia.

Query para correr:

  update [sinalic_prod].[dbo].[tLicencias]
  set txEstado = ‘VIGENTE’
  where idLicencia = 12586812

 
  update [sinalic_prod].[dbo].[tTramites]
  set txEstado = ‘EMITIDO’
  where idTramite = 13558925

   
update [sinalic_prod].[dbo].[tInsumos]
set txEstado = ‘ASIGNADO’
where idInsumo = 6313897

**Comment by EliasWasinger** [comment]
Realizado!
