### ISSUE TITLE
SINALIC -Activar Licencia (GLPI 3658)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#100]
DEJAR EN ESTADO VIGENTE LA LICENCIA QUE SE DETALLA A CONTINUACION:
D.N.I.: 27475401
Apellido y Nombres: UMLANDT, RUBEN MOISES
Sexo: MASCULINO
Nº de insumo: 003468937

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado a VIGENTE, dejo la query:

`select * from tInsumos where txNumeroInsumo = '003468937' /* id = 3768319 */

select * from tLicencias where txNroLicencia = '27475401' and idInsumo = '3768319'

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '8173993'
	
commit`
