### ISSUE TITLE
SINALIC - Modificar matricula (GLPI 3672)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#101]
Modificar las matriculas cargadas en Junin de los Andes, Mendoza

numero cargado / numero correcto
23659802-100 / 23659208-100 
23659802-200 / 23659208-200
23659802-300 / 23659208-300

**Comment by EliasWasinger** [comment]
Listo, se cambiaron las matriculas en la columna legajos de funcionarios, dejo la query:

`select * from tFuncionarios where txLegajo = '23659802-100' /* id 7219 */
select * from tFuncionarios where txLegajo = '23659802-200' /* id 7220 */
select * from tFuncionarios where txLegajo = '23659802-300' /* id 7221 */
/* NO VA
select * from tPersonasFisicas where idPersonaFisica = '641058'

select * from dbo.tDetallesHabilitacion d where  d.idFuncionario = '7219'
*/

begin transaction
	update dbo.tFuncionarios set txLegajo = '23659208-100' where idFuncionario = '7219'
	update dbo.tFuncionarios set txLegajo = '23659208-200' where idFuncionario = '7220'
	update dbo.tFuncionarios set txLegajo = '23659208-300' where idFuncionario = '7221'
commit`
