### ISSUE TITLE
SINALIC - CAMBIAR DE ESTADO (GLPI 3720)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#102]
cambio de estado de la Licencia del ciudadano ALMEIDA CARLOS DANIEL, DNI 28.675.592 a aprobada

**Comment by EliasWasinger** [comment]
Se cambió el estado a VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '28675592' /* la Licencia anulada id = 7189058 */

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '7189058'
	
commit`
