### ISSUE TITLE
SINALIC - Volver a estado aprobado(GLPI 3886)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#104]
volver a estado aprobado el tramite, no solo el estado sino que la fecha de baja tambien debe quedar en nula, y quitar el motivo de la anulacion, el tramite corresponde a la licencia con dni 10367002 sexo masculino y el nro de insumo es 005505674

**Comment by EliasWasinger** [comment]
Listo, se cambió el ESTADO, FECHA ANULACIÓN, Y MOTIVO del trámite.
Dejo la query:

`select * from tLicencias where txNroLicencia = '10367002'

select * from tInsumos where idInsumo = '5502929' /* nro 005505674 */

select * from tTramites where idTramite = '14752621'
/* *** */
begin transaction
	update tTramites set txEstado = 'APROBADO' where idTramite = '14752621'
commit

begin transaction
	update tTramites set fcFechaAnulacion = NULL where idTramite = '14752621'
commit

begin transaction
	update tTramites set idMotivoAnulacionTramite = NULL where idTramite = '14752621'
commit`
