### ISSUE TITLE
SINALIC - volver a estado vigente (GLPI 3901)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#105]
Cambiar estado de licencia a vigente dni 33310900 sexo masculino realizada el 06/04/2016

**Comment by EliasWasinger** [comment]
Listo, se cambio el estado a VIGENTE. Dejo la query:

`select * from tLicencias where txNroLicencia = '33310900' /* id 11535433 */

begin transaction

	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '11535433'
	
commit`
