### ISSUE TITLE
SINALIC -- Consulta Id de Cel(GLPI 3920)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#107]
Necesito los Id de cel de los siguientes Centros Emisores.

SALTA - CHICOANA 
SALTA - ROSARIO DE LERMA
MENDOZA - GODOY CRUZ 
ENTRE RIOS - ESTANCIA GRANDE
FORMOSA - FORMOSA CAPITAL

**Comment by EliasWasinger** [comment]
SALTA - CHICOANA | ID = 534
SALTA - ROSARIO DE LERMA | ID = 230
MENDOZA - GODOY CRUZ | ID = 533
ENTRE RIOS - ESTANCIA GRANDE |  ID = 535
FORMOSA - FORMOSA CAPITAL --> FORMOSA CAPITAL NO EXISTE, se encontró FORMOSA con ID = 527 (se realizó búsqueda con WHERE y LIKE, el único encontrado fue el mencionado)
