### ISSUE TITLE
SINALIC -- Anular Licencia(GLPI 3957)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#108]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	
Trámite y Licencia N° 35262262, Cutipa, Emanuel Martín, Masculino, Nro. de insumo 006712522, Emitida el 26/10/2016.

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de vigente a ANULADA, dejo la query:

`select * from tLicencias where txNroLicencia = '35262262' /* id 13807826 */


begin transaction
	update tLicencias set txEstado = 'ANULADA' where idLicencia = '13807826'
commit`
