### ISSUE TITLE
SINALIC -- Anular Licencia(GLPI 3935)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#109]
Anulara licencia 30788567 mal generada.

**Comment by EliasWasinger** [comment]
Listo, se pasó el estado a ANULADA, dejo la query:

`select * from tLicencias where txNroLicencia = '30788567' /* id 6958725 */


begin transaction
	update tLicencias set txEstado = 'ANULADA' where idLicencia = '6958725'
commit`
