### ISSUE TITLE
SINALIC- Reporte(GLPI 1768)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#11]
Solicito reporte de licencias no impresas del municipio de san Luis, prov de san Luis.

**Comment by EliasWasinger** [comment]
Usé el script de reporte.licenciasNoImpresasPorProvincia
Acá te lo dejo
[No impresas San Luis.xlsx](https://github.com/leoimoli/Base-De-Datos/files/381525/No.impresas.San.Luis.xlsx)
