### ISSUE TITLE
SINALIC -- Pasar licencia a estado Vigente(GLPI 3931)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#110]
Javier Ricardo Stagno /Masculino/Argentino/DNI 27495155.

**Comment by EliasWasinger** [comment]
La licencia ya se encontraba en estado VIGENTE, dejo los datos:
Emisión: 2016-10-25 13:37:22.000
Trámite: 14829446
idLicencia: 13799400
