### ISSUE TITLE
SINALIC -- Cambiar Estado Licencia(GLPI 3962)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#111]
pasar a estado "No Vigente" la licencia N°25114816, emitida el día 25/11/2014 en Bahía Blanca.

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a estado NO_VIGENTE, dejo la query:

`select* from tLicencias where txNroLicencia = '25114816' /* id 7667201 */


begin transaction
	update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '7667201'
commit`
