### ISSUE TITLE
ALTA SIM ROSARIO DEL TALA ( ENTRE RIOS)--(GLPI 3975)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#113]
Estimados muy buenos días les solicito el alta de la localidad Rosario del Tala, les adjunto los datos;
- Autoridad de Juzgamiento: "JUZGADO MUNICIPAL DE FALTAS" con ID SAFIT 912
- Dirección física: San Martin N°689
- Teléfono: (03445) 421188
- Horario de atención: L A V 08:30 a 11:30
- Correo electronico: juzgadodefaltastala@gmail.com
- Valor combustible: $ 20.00
- Nombre de la Autoridad de Constatación: Municipalidad de Rosario del Tala 
- Partido al que se asocia la Autoridad de Constatación: 	Tala
- Provincia al que se asocia la Autoridad de Constatación: Entre Ríos
- Archivo del Logo J13A008.pcx
-Id (13 para Entre Rios)
-Código: 008
- Adhesión a la ordenanza 437/11

**Comment by leodimonio** [comment]
ya se dio de alta el juzgado en produccion
