### ISSUE TITLE
ALTA DE SIM Santo tome Corrientes – PROD Y EXTERNO PRIORIDAD ALTA(GLPI 3977)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#114]
Estimados muy buenos dias les adjunto los datos de la localidad 
- Autoridad de Juzgamiento: "JUZGADO MUNICIPAL DE FALTAS" con ID SAFIT 1460
- Dirección física: San Martin y A. S. Blanco 
- Teléfono: (03756)-421177
- Horario de atención: L A V 07:00 a 13:00
- Correo electronico: -
- Valor combustible: $ 20.29
- Nombre de la Autoridad de Constatación: Municipalidad de Santo Tome 
- Partido al que se asocia la Autoridad de Constatación: 	Santo Tome
- Provincia al que se asocia la Autoridad de Constatación: Corrientes
- Archivo del Logo J13A012.pcx
-Id (19 para Corrientes)
-Código: 012
- Adhesión a la ordenanza 437/11

**Comment by leodimonio** [comment]
ya se encuentra realizado el cambio en produccion y testing externo
