### ISSUE TITLE
SINALIC -- Licencia aparece anulada REACTIVAR(GLPI 3992)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#115]
LICENCIA Nº 24338599
TITULAR: JUAN FACUNDO QUIROGA
SEXO: MASCULINO
TRÁMITE: 7553991

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado a VIGENTE, dejo la query:
`select * from tLicencias where txNroLicencia = '24338599' /* 7151862 */


begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '7151862'
commit`

**Comment by leoimoli** [comment]
Nos indican que la licencia debe quedar en estado "NO_VIGENTE" y el tramite asociado a dicha licencia "EMITIDA"

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado, de ambas, dejo la query:

`select * from tLicencias where txNroLicencia = '24338599'

select * from tTramites where idTramite = '7553991'

begin transaction
	update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '7151862'

begin transaction	
	update tTramites set txEstado = 'EMITIDO' where idTramite = '7553991'
	
commit`
