### ISSUE TITLE
SIM-ANULACION DE ARTICULOS DEL DECRETO 437 PARA EL MUNICIPIO GRAL. RAMIRES/ ENTRE RIOS -PRIORIDAD ALTA(GLPI 3994)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#118]
Estimados les mando este correo para informarle que Gral. Ramírez (Entre Ríos) esta adherido al decreto 437, pero con reserva hacia ciertos artículos del mismo. Ante lo cual se solicita que se descarte dichos artículos los cuales son:
107, 111, 116, 13, 15, 17, 19, 3, 33 inciso 1 y 2, 6, 69, 8, 86, 9 inciso 1 y 2, 90, 94.
Ala ves se debe agregar en el SIM la ordenanza 2369 que reemplazaría A los artículos anulados del decreto 437 descripto anteriormente, dicha ordenanza se encuentra cargada ya en el SINAI.

**Comment by leodimonio** [comment]
se borraron los detalles de adhesion referidos en el ticket , y se agrego la ordenanza 2369 y su adhesion a ramirez
