### ISSUE TITLE
SINAI --MODIFICACION DE SEXO EN EL SISTEMA(GLPI 4021)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#119]
Solicito la modificación en el sistema del SEXO correspondiente a Samanta Andrea, Cheroni MARRO (DNI 30.702.689) de MASCULINO por el correcto FEMENINO.

**Comment by leodimonio** [comment]
existen dos personas cargadas con el sexo distinto y mismo dni, y ambos contienen antecedentes de tipo inhabilitacion, el que esta cargado femenino tiene como numero de causa 14788/2015, y el masculino, ccc14788/2015/pl1
