### ISSUE TITLE
SINAI -- INCIDENTE- SOLICITUD ID JUZGADO SINAT(GLPI 1807)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#12]
Se solicita el Id del Juzgado de Instrucción de la 1º Nominación de Rafaela - Santa Fe creado en Sinat.

**Comment by EliasWasinger** [comment]
id 373 - JUZGADO DE PRIMERA INSTANCIA DISTRITO N° 5 EN LO PENAL CORRECCIONAL PRIMERA SECRETARIA
id 455 - JUZGADO DE PRIMERA INSTANCIA EN LO PENAL CORRECCIONAL N° 5 SEGUNDA SECRETARIA
id 820 - OFICINA DE GESTIÓN JUDICIAL CIRCUNSCRIPCIÓN JUDICIAL N° 5

No existe la solicitada.

**Comment by EliasWasinger** [comment]
Otra vez la mula al trigo:
Se encontró:
JUZGADO PENAL DE INSTRUCCION DE LA 1ERA NOMINACIÓN con el id 827 que se dio de alta el día 2016-07-25
