### ISSUE TITLE
SINALIC -- Modificar estado(GLPI 4015)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#120]
LICENCIA Nº 24338599 Pasar a Estado NO_VIGENTE
TRÁMITE: 7553991 Estado EMITIDO

**Comment by EliasWasinger** [comment]
La licencia ya se encuentra en estado de NO_VIGENTE, dejo los datos para que lo veas:

- 7151862	24338599	2014-09-24 13:55:44.000	 QUIROGA	JUAN FACUNDO	1975-01-02 00:00:00.000	M	NO_VIGENTE	7553991	A E	3199999	3	DNI		   		ARGENTINA	MZA. 756 LOTE	Bº AMPL. SANTA ANA II	0	-	SALTA	6	2016-09-24 00:00:00.000			NULL	NULL
