### ISSUE TITLE
SINALIC -- Modificar Pais Emisor(GLPI 4019)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#121]
Modificar a la persona fisica la el pais Emisor 
Actual: Cabo Verde Cambiarlo a ARGENTINA(id 13)

DNI:  24.697.694

**Comment by EliasWasinger** [comment]
Se cambió el país emisor, dejo la query:

`select * from tPersonasFisicas where txNumeroDocumento = '24697694' /* id 160815 */

begin transaction
	update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '160815'
commit`
