### ISSUE TITLE
SINALIC -- Consulta IdCel(GLPI 4069)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#124]
Necesito los id de Cel de los siguientes Centro Emisores:
MENDOZA - MALARGÜE -
CORDOBA - VILLA ALLENDE -

**Comment by EliasWasinger** [comment]
Listo, te dejo los id de los CELs

MENDOZA - MALARGÜE - id = 536
CORDOBA - VILLA ALLENDE - id = 526
