### ISSUE TITLE
SINAI -- Error producción SINAI - Versión 1.13.8(GLPI 4039)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#125]
Cuando se quiere ingresar al detalle del acta N° 062000116004692 y 062000116004707 sale el siguiente cartel de error "query did not return a unique result: 2". Al detalle se accede desde el menú Actas/ Consulta de actas de contatación, seleccionando la lupa una vez consultada el acta en cuestión.

**Comment by leodimonio** [comment]
listo estaban duplicadas las imagenes del acta
