### ISSUE TITLE
SINALIC -- modificar perfil usuario(GLPI 3787)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#127]
Necesitan cambiar el perfil de los siguiente usuarios a un prefil ANSV.
Usuarios:
27555645 
36498905
34253489

**Comment by EliasWasinger** [comment]
Listo, se les dio Perfil ANSV con id = 1 a los usuarios, dejo la query:

`select * from tUsuarios where txUsuarioAD = '27555645' /* id 155 */

select * from tUsuarios where txUsuarioAD = '36498905' /* id 2468 */

select * from tUsuarios where txUsuarioAD = '34253489' /* id 218 */

begin transaction
	update tPerfilesPorUsuario set idPerfil = '1' where idUsuario = '155'
commit

begin transaction
	update tPerfilesPorUsuario set idPerfil = '1' where idUsuario = '2468'
commit
	
begin transaction
	update tPerfilesPorUsuario set idPerfil = '1' where idUsuario = '218'
commit`

**Comment by leoimoli** [comment]
El usuario N° 27555645 se encuentra inactivo, solicito que se active.

**Comment by EliasWasinger** [comment]
Listo, se activo el usuario (estado a ACTIVO), dejo la query:

`select * from tUsuarios where txUsuarioAD = '27555645'

begin transaction
	update tUsuarios set txEstado = 'ACTIVO' where idUsuario = '155'
commit`
