### ISSUE TITLE
SINALIC -- anulación licencia(GLPI 3870)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#128]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	
DNI:34659460
 INSUMO:006349272
EMISION DE LA LICENCIA: 21/10/2016

**Comment by EliasWasinger** [comment]
No se realizo lo pedido, la licencia se encontraba en estado ANULADA, el trámite asociado está en estado EMITIDO, dejo la query:

`select * from tLicencias where txNroLicencia = '34659460'/* id = 13741079 */

select * from tTramites where idTramite = '14698303'`
