### ISSUE TITLE
SINALIC -- Modificar estado licencia(GLPI 4106)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#130]
Solicito modificar los siguientes estados de las licencias emitidas N° LICENCIA 22641608

La que tiene tramite N° 14688611 pasar a estado NO VIGENTE
La que tiene tramite N° 7867829 pasar a estado VIGENTE.

**Comment by EliasWasinger** [comment]
La licencia con el trámite 14688611 ya se encontraba en estado: NO_VIGENTE.
Se cambió el estado de la licencia con el idTramite: 7867829 
Dejo la query:

`select * from tLicencias where txNroLicencia = '22641608' and idTramite = '7867829' /* id 7446288 */

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '7446288'
commit`
