### ISSUE TITLE
SINALIC -- CAMBIAR DE ESTADO(GLPI 3720)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#131]
Cambiar de estado el tramite relacionado a la licencia  DNI 28.675.592. El mismo debe quedar en estado aprobado.

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite relacionda a la Licencia, dejo la query con las aclaraciones:

`select * from tLicencias where txNroLicencia = '28675592' /* id de ultima licencia 14737187 en VIGENTE */

select * from tTramites where idTramite = '14737187' /* estado EMITIDO */

begin transaction
	update tTramites set txEstado = 'APROBADO' where idTramite = '14737187'
commit`

**Comment by EliasWasinger** [comment]
Se volvió a realizar el cambio, ahora a estado EMITIDO, dejo la query:

`select * from tLicencias where txNroLicencia = '28675592' /* id de ultima licencia 14737187 en VIGENTE */

select * from tTramites where idTramite = '14737187' /* estado EMITIDO */

begin transaction
	update tTramites set txEstado = 'EMITIDO' where idTramite = '14737187'
commit`
