### ISSUE TITLE
SINALIC -- Cambiar vigencia(GLPI 4124) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#132]
Modificar la vigencia del siguiente tramite, el sistema le da una vigencia de 3 años y le corresponden 5.

14906954 APROBADO 31/10/2016 08:34:15 a.m. 13508864 SENOBIO RAUL ACOSTA RENOVACIÓN A.3 B.1 225122

**Comment by EliasWasinger** [comment]
Se modificó la Vigencia Máxima del trámite a 5 años.
Dejo la query:

`select * from tTramites where idTramite = '14906954' /* nuVigenciaMaxima = 3 */

begin transaction
	update tTramites set nuVigenciaMaxima = '5' where idTramite = '14906954'
commit`
