### ISSUE TITLE
SIM -- ALTA SIM PRODUCCION GOYA ( CORRIENTE)- PRIORIDAD ALTA(GLPI 4148)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#135]
Estimados solicito ar de alta en SIM producción el juzgado de Goya. Adjunto datos:

- Autoridad de Juzgamiento: "JUZGADO DE FALTAS DE GOYA" con ID SAFIT 1486
- Dirección física: Mariano I. Loza N°30 
- Teléfono: --
- Horario de atención: L A V 07:00 a 13:00
- Correo electronico: -
- Valor combustible: $ 19.00
- Nombre de la Autoridad de Constatación: Municipalidad de Goya 
- Partido al que se asocia la Autoridad de Constatación: 	Goya
- Provincia al que se asocia la Autoridad de Constatación: Corrientes
- Archivo del Logo J19A013.pcx
-Id (19 para Corrientes)
- Código: 013
- Adhesión a la ordenanza 437/11 y Ord. 9/83

**Comment by leodimonio** [comment]
Listo, se agrego el juzgado, la autoridad, el decreto y ambas adhesiones solicitadas
