### ISSUE TITLE
SINALIC -- pasar licencia a estado vigente(GLPI 4163)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#136]
Nro Licencia: 16022952

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente, tenía solamente 2 licencias la más actual (la que fue actualizada) tiene fecha de emisión en 2014, tomé esa por no tener más datos, dejo la query:

`select * from tLicencias where txNroLicencia = '16022952' /* id 5997972, fecha de emision el 31/03/2014 */

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '5997972'
commit`

**Comment by EliasWasinger** [comment]
Se arreglo, dejo query:
`select * from tLicencias where txNroLicencia = '16022952'

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '1664621'
begin transaction
	update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '5997972'
commit`
