### ISSUE TITLE
SINALIC -- Modificar Tipo de DNI(GLPI 4174)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#137]
Modificar tipo de documento para la persona fisica de libreta Civica a DNI

LILLIESKOLD CARMEN CON DNI 5.327.840

**Comment by EliasWasinger** [comment]
Listo, se cambió el tipo de dni, dejo la query:
`select * from tPersonasFisicas where txNumeroDocumento = '5327840'
select * from tLicencias where txNroLicencia = '5327840'

begin transaction /* lo cambio en tLicencias, estaba LC */
	update tLicencias set txTipoDocumento = 'DNI' where idLicencia = '11919326'

begin transaction
	update tPersonasFisicas set idTipoDocumento = '2' where idPersonaFisica = '8634904'
commit

begin transaction
	update tPersonasFisicas set idTipoDocumento = '1' where idPersonaFisica = '8635715'
commit`
