### ISSUE TITLE
SINALIC -- Cambiar estado licencia(GLPI 4162)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#138]
Se solicita pasar a vigente la licencia anulada. Se adjunta DNI y licencia.

DNI :32.064.137

**Comment by EliasWasinger** [comment]
Se pasó a VIGENTE, dejo la query:
`
select * from tLicencias where txNroLicencia = '32064137' /*180830*/

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '180830'
commit`
