### ISSUE TITLE
SINALIC -- ANULAR LICENCIA(GLPI 4083) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#139]
DNI : 18.332.109
Fechas : 31/07/2014	 a 31/07/2015

**Comment by EliasWasinger** [comment]
Listo, se cambio a estado ANULADA, dejo la query:

`
select * from tLicencias where txNroLicencia = '18332109' /*6814962*/

begin transaction
	update tLicencias set txEstado = 'ANULADA' where idLicencia = '6814962'
commit`
