### ISSUE TITLE
SINAI -- Modificacion Antecedente(GLPI 1879)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#14]
Necesito se modifique el Antecedente del Sr IMPAGLIAZZO Jose Luis, DNI : 14746506. Solicito se modifique fecha de sentencia firme , donde dice fecha de sentencia firme 06/05/1960 debe decir 06/05/2016.

**Comment by EliasWasinger** [comment]
Se modificó la fecha.
