### ISSUE TITLE
SINAI -- Error Producción V. 1.13.8(GLPI 4112)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#140]
Necesitamos dar de alta los siguientes Usuarios del Municipio de Santo Tomé:
 16136857 Rosendo Jacinto FERNANDEZ
 21733583 Maria Teresa BALMACEDA
 31701489 CLAUDIO FEDERICO QUIROZ
 33644214 Carlos Maria MONTENEGRO
 24762031 Vilma Delia SANTAREN

Fueron dados de alta como funcionarios, pero cuando queremos dar de alta el Usuario nos sale el mensaje "Nombre Usuario Existente" y no realiza el mismo.

**Comment by leodimonio** [comment]
Buenas, estos usuarios ya fueron creados como usuarios de Jurisdiccion (Corrientes) el 29-08-2016, por ende no se pueden asociar a un usuario de tipo funcionario.
