### ISSUE TITLE
SINALIC -- Cambiar estado de licencia de CABA (GLPI 4196)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#143]
Cambiar estado de licencia de ANULADA a NO_VIGENTE, poner la fecha de anulacion en nula, los datos de la licencia son dni 37945297, sexo femenino

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '37945297'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '3663964'`
