### ISSUE TITLE
SINALIC -- Reporte Licencia Emitida(GLPI 4256)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#146]
Buenos dias. por favor proporcionar Licencias Emitidas por CEL y por mes de Enero a Octubre 2016. 
 Tiene que contener los siguientes campos: 
 Año
 Mes 
JURISDICCION 
CEL 
Estado 
Sexo 
TOTAL

**Comment by EliasWasinger** [comment]
Listo, dejo el excel de las licencias junto con la query:

[Licencias Emitidas - Enero a Octubre 2016.xlsx](https://github.com/leoimoli/Base-De-Datos/files/580850/Licencias.Emitidas.-.Enero.a.Octubre.2016.xlsx)

`use sinalic_prod

declare @FechaIni datetime
declare @FechaFin datetime
set @FechaIni = convert(datetime, '01/01/2016', 103)   -- dd/mm/yyyy 
set @FechaFin = convert(datetime, '31/10/2016', 103)  -- dd/mm/yyyy 
--select @FechaIni,@FechaFin

SELECT   
    Datepart(YEAR,dbo.tLicencias.fcFechaEmision ) as Año ,
    Datepart(MONTH,dbo.tLicencias.fcFechaEmision ) as Mes , 
    tEntidades_1.txNombre AS JURISDICCION, 
    dbo.tCentrosEmisionLicencias.txNombre AS CEL,
    dbo.tLicencias.txEstado as Estado, 
    dbo.tLicencias.txSexoLicencia as Sexo,
    COUNT(   dbo.tLicencias.idLicencia)as TOTAL
FROM         
	 dbo.tLicencias INNER JOIN
     dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite INNER JOIN
     dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia INNER JOIN
     dbo.tEntidades ON dbo.tCentrosEmisionLicencias.idEntidad = dbo.tEntidades.idEntidad INNER JOIN
     dbo.tEntidades AS tEntidades_1 ON dbo.tEntidades.idJurisdiccion = tEntidades_1.idEntidad         
WHERE
	 tLicencias.txEstado in ('VIGENTE','NO_VIGENTE') 
	 and tLicencias.fcFechaEmision BETWEEN @FechaIni AND @FechaFin
	 
GROUP BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia
ORDER BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia`

**Comment by leoimoli** [comment]
Buenas Tardes. Por favor podrian volver a generar el reporte. Revisandolo no me cuadran los totales. por ejemplo. Para el CEL de Formosa me figura 2 licencias Emitidas en el mes 10. Pero en el SINALIC figura 16 licencias. Faltan 14 licencias vigentes del dia 31 de octubre. Gracias

**Comment by EliasWasinger** [comment]
Listo, hubo un error al colocar las fechas, no me tomaba el 31. Dejo el excel con las licencias con tLicencias.txEstado != ('NO_IMPRESA')(el sistema muestra 17 y el excel 16 porque está en estado no impresa) :

[Licencias Emitidas - Enero a Octubre 2016.xlsx](https://github.com/leoimoli/Base-De-Datos/files/585918/Licencias.Emitidas.-.Enero.a.Octubre.2016.xlsx)

`

declare @FechaIni datetime
declare @FechaFin datetime
set @FechaIni = convert(datetime, '01/01/2016', 103)   -- dd/mm/yyyy 
set @FechaFin = convert(datetime, '01/11/2016', 103)  -- dd/mm/yyyy 
--select @FechaIni,@FechaFin

SELECT   
    Datepart(YEAR,dbo.tLicencias.fcFechaEmision ) as Año ,
    Datepart(MONTH,dbo.tLicencias.fcFechaEmision ) as Mes , 
    tEntidades_1.txNombre AS JURISDICCION, 
    dbo.tCentrosEmisionLicencias.txNombre AS CEL,
    dbo.tLicencias.txEstado as Estado, 
    dbo.tLicencias.txSexoLicencia as Sexo,
    COUNT(   dbo.tLicencias.idLicencia)as TOTAL
FROM         
	 dbo.tLicencias INNER JOIN
     dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite INNER JOIN
     dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia INNER JOIN
     dbo.tEntidades ON dbo.tCentrosEmisionLicencias.idEntidad = dbo.tEntidades.idEntidad INNER JOIN
     dbo.tEntidades AS tEntidades_1 ON dbo.tEntidades.idJurisdiccion = tEntidades_1.idEntidad         
WHERE
	 tLicencias.txEstado != ('NO_IMPRESA') 
	 and tLicencias.fcFechaEmision BETWEEN @FechaIni AND @FechaFin
	 
GROUP BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia
ORDER BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia`
