### ISSUE TITLE
SINALIC -- pasar a estado no vigente(GLPI  4262)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#148]
NRO:LICENCIA: 18807101 masc

**Comment by EliasWasinger** [comment]
Listo, se paso la licencia a no vigente, dejo la query:

`select * from tLicencias where txNroLicencia = '18807101' /* id 7507933 */

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '7507933'`
