### ISSUE TITLE
SINALIC -- Solicita reactivar licencia(GLPI 4297)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#149]
Reactivar la siguiente licencia.

NRO.LICENCIA =  37.971.626
NRO.TRAMITE = 15011932

**Comment by EliasWasinger** [comment]
Listo, se pasó de estado anulada a vigente, dejo la query:

`select * from tLicencias where txNroLicencia = '37971626' and idTramite = '15011932' /* 13969640 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '13969640'`
