### ISSUE TITLE
SINALIC -- Cargar SubClases(GLPI 1595)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#15]
Se deben agregar por base de datos las siguientes sublclases a la licencia de señor Veron Mariano Gabriel, DNI: 35.459.105
Subclases:  A3 y B2

**Comment by EliasWasinger** [comment]
Se hizo

`insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (10,3181917)`
