### ISSUE TITLE
SINALIC - solicito listado detallado de licencias NO IMPRESAS de la provincia de mendoza (GLPI 4317)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#150]
solicito el listado detallado de licencias NO IMPRESAS de los Cels de toda la provincia de Mendoza
el mismo debe contenes el detalle de cada tramite en ese estado, ej. nombre apellido tipo de tramite y fecha,etc.

**Comment by EliasWasinger** [comment]
Listo, dejo el excel junto con la query:

[Licencias no impresas - Mendoza.xlsx](https://github.com/leoimoli/Base-De-Datos/files/584053/Licencias.no.impresas.-.Mendoza.xlsx)

`declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='Mendoza';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	dbo.tCentrosEmisionLicencias.txNombre AS CEL,
	dbo.tLicencias.fcFechaEmision as FechaEmision,
	dbo.tLicencias.txNroLicencia as NumeroLicencia,
	dbo.tLicencias.txEstado AS EstadoLicencia,
	dbo.tLicencias.fcFechaVencimiento as FechaVencimiento,
	dbo.tLicencias.txApellidoLicencia as Apellido,
	dbo.tLicencias.txNombreLicencia as Nombre,
	dbo.tLicencias.fcFechaNacimientoLicencia as FechaNacimiento,
	dbo.tLicencias.txSexoLicencia as Sexo,
	dbo.tTramites.idTramite,
	dbo.tTramites.fcFechaInicioTramite as InicioTramite,
	ttramites.txNumeroFormulario as NumeroFormulario,
	dbo.tTramites.fcFechaInicioTramite as FechaInicioTramite,
	dbo.tCategoriasLicencia.txNombre AS CategoriasLicencia

FROM
	dbo.tLicencias
	INNER JOIN dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite
	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	INNER JOIN dbo.tPersonasFisicas ON dbo.tTramites.idPersonaFisica = dbo.tPersonasFisicas.idPersonaFisica
	INNER JOIN dbo.tCategoriasLicencia ON dbo.tTramites.idCategoriaLicencia = dbo.tCategoriasLicencia.idCategoriaLicencia
	INNER JOIN dbo.tTiposDocumento ON dbo.tPersonasFisicas.idTipoDocumento = dbo.tTiposDocumento.idTipoDocumento

WHERE  
	ttramites.idCentroEmisionLicencia 
		IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))
       AND tLicencias.txEstado = 'NO_IMPRESA'

ORDER  BY 
	dbo.tCentrosEmisionLicencias.txNombre,
	dbo.tLicencias.fcFechaEmision,
	dbo.tLicencias.txApellidoLicencia,
	dbo.tLicencias.txNroLicencia 
`
