### ISSUE TITLE
SINALIC -- INCORPORAR EN PAGINA WEB AGENCIA(GLPI 4329)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#151]
Propocionar los id de Cel de los siguientes Centros.
APOLINARIO SARAVIA - SALTA
EL QUEBRACHAL - SALTA

**Comment by EliasWasinger** [comment]
Te dejo los ID:
APOLINARIO SARAVIA - SALTA - ID = 537
EL QUEBRACHAL - SALTA - ID = 538
