### ISSUE TITLE
SINALIC Consulta

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#152]
Un reporte de las cantidad de  licecias emitidas de provincia de bs as del 20016 dividia por mes 
y de los otros años agrupadas por año la cantidad.

**Comment by EliasWasinger** [comment]
Listo, dejo el excel y la query
[Licencias Emitidas - 2016 Buenos Aires.xlsx](https://github.com/leoimoli/Base-De-Datos/files/586357/Licencias.Emitidas.-.2016.Buenos.Aires.xlsx)
:

`declare @idJurisdiccion int, @provincia varchar(20);
declare @FechaIni datetime
declare @FechaFin datetime
set @FechaIni = convert(datetime, '01/01/2016', 103)   -- dd/mm/yyyy 
set @FechaFin = convert(datetime, '01/01/2017', 103)  -- dd/mm/yyyy 
set @provincia='BUENOS AIRES';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	dbo.tCentrosEmisionLicencias.txNombre AS CEL,
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ) as Año ,
	COUNT(1) as Cantidad from dbo.tLicencias


	INNER JOIN dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite
	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	INNER JOIN dbo.tPersonasFisicas ON dbo.tTramites.idPersonaFisica = dbo.tPersonasFisicas.idPersonaFisica
	INNER JOIN dbo.tCategoriasLicencia ON dbo.tTramites.idCategoriaLicencia = dbo.tCategoriasLicencia.idCategoriaLicencia
	INNER JOIN dbo.tTiposDocumento ON dbo.tPersonasFisicas.idTipoDocumento = dbo.tTiposDocumento.idTipoDocumento
/*
WHERE
	 tLicencias.fcFechaEmision BETWEEN @FechaIni AND @FechaFin	*/

GROUP BY
	dbo.tCentrosEmisionLicencias.txNombre,
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision )
ORDER  BY 
	dbo.tCentrosEmisionLicencias.txNombre,
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision )

`
