### ISSUE TITLE
SINALIC - cambiar licencia de estado (GLPI 4362)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#153]
La licencia se encuentra anulada, cambiar a estado NO VIGENTE.
DNI 36095784 femenino

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado, dejo la query:

`select * from tLicencias where txNroLicencia = '36095784' /* id 10347476 */

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10347476'`
