### ISSUE TITLE
SINALIC - pasar de estado (GLPI 4367)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#154]
PASAR A ESTADO VIGENTE:

BONILLA LEANDRO YAIR, N° DE DNI 38.839.622.

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado a la licencia emitida en 2016 (tenía 4 licencias asociadas), dejo la query:

`select * from tLicencias where txNroLicencia = '38839622' /* id 12193518 (la unica emitida en 2016) */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12193518'`
