### ISSUE TITLE
SINALIC -- modificar estado de licencia (GLPI 4348)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#155]
solicito se modifique el estado de la siguiente licencia numero de documento 6434223 fecha de inicio 06/10/2015 numero de tramite 10646100 estado NO_VIGENTE tramite RENOVACIÓN vigencia 06/10/2015 - 06/10/2020 clase B sede ROSARIO DGT apellido NEGRI nombres GRACIELA AMALIA insumo 004473015 el mismo 
**se encuentra en estado NO VIGENTE, solicito se pase a estado VIGENTE**

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '6434223' /* id 10034760 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10034760'`
