### ISSUE TITLE
cambiar tramite a estado EMITIDO(GLPI 4416)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#156]
POR FAVOR CAMBIAR DE ESTADO ESTE TRAMTEE YA QUE DSE ENCUENTRA REALCIONADO A UNA LIECNCIA Y DEBERIA FIGURA EMITIDO

DNI 36095784 	PAOLA NOELIA	PEDROS	RENOVACIÓN CON AMPLIACIÓN	A.2.1	20360928

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del tramite a EMITIDO, dejo la query:

`select * from tLicencias where txNroLicencia = '36095784' /* idTramite 10978294 */

select * from tTramites where idTramite = '10978294'


update tTramites set txEstado = 'EMITIDO' where idTramite = '10978294'`
