### ISSUE TITLE
SINALIC -- CAMBIAR DE ESTADO(GLPI 4458)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#157]
POR ERROR DEL CEL SE INTERCAMBIARON LAS FOTOS DEL CONTRIBUYENTE
SE SOLICITA PONER EL TRAMITE ANULADO EN ESTADO GENERADO PARA QUE PUEDAN MODIFICAR LAS FOTOS.
DNI 6515705 MASCULINO

**Comment by EliasWasinger** [comment]
Listo, se pasó el trámite a estado GENERADO, dejo la query:

`select * from tLicencias where txNroLicencia = '6515705'

select * from tTramites where idTramite = '15074617'

update tTramites set txEstado = 'GENERADO' where idTramite = '15074617'`
