### ISSUE TITLE
SINALIC -- Modificar Nacionalidad(GLPI 4488)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#158]
Datos de la persona Ayala Beltran, Albert, DNI 95067902, nacionalidad Boliviana, país emisor Argentina.

**Comment by EliasWasinger** [comment]
Listo, se cambió el país emisor, por favor chequear la query que dejo:

`select * from tLicencias where txNroLicencia = '95067902' /* id 13117930 */

select * from tPersonasFisicas where txNumeroDocumento = '95067902' /* Arg id = 13 || idPersonaFisica 4927168 */


update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '4927168'`
