### ISSUE TITLE
SINALIC -- Modificar Licencia(GLPI 4477)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#159]
se solicita el cambio de estado de la licencia que figura en estado VIGENTE a no VIGENTE del Sr
INSUA eduardo casto DNI 10329036

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia a no vigente, dejo la query:

`select * from tLicencias where txNroLicencia = '10329036' /* id 13117930 */


update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '13117930'`
