### ISSUE TITLE
SINALIC -- Agregar matricula(GLPI 1894)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#16]
Agregar el numero de matricula 911 y la especialidad Clinico al medico Irigiyen, Miguel Antonio DNI: 14941795 , legajo 10491795-400. Delegacion Santa Teresa, Neuquen

**Comment by EliasWasinger** [comment]
Se hizo

`begin transaction
	update dbo.tDetallesHabilitacion set txMatriculaProfesional = '911' where idDetalleHabilitacion = '647'
	update dbo.tDetallesHabilitacion set txEspecialidad = 'MEDICO CLINICO' where idDetalleHabilitacion = '647' 
commit`
