### ISSUE TITLE
SIM Producción - Cambio de Ordenanza La Quiaca(GLPI 4475)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#160]
Nos pidieron del Municipio de La Quiaca, Provincia de Jujuy el reemplazo de la Ordenanza DEC.283/15- LA QUIACA por la Ordenanza ORDENANZA N° 01/2016.

En el SINAI ya se efectuó la carga de la Ordenanza 01/2016 con fecha de inicio de vigencia 20/01/2016, habría que cargarla en el SIM y eliminar la 283/15.

Aclaración además debe quedar cargado el Decreto 437/11 el cual también es utilizado por la Jurisdicción.

Provincia: Jujuy

Partido / Departamento: Yavi

Localidad: La Quiaca

**Comment by leodimonio** [comment]
Listo, se elimino la adhesion al decreto  283/15, se cargo la nueva ordenanza 01/2016, y se adhirio al partido dicha ordenanza, saludos.
