### ISSUE TITLE
SINALIC -- Reactivar Licencia

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#162]
REACTIVAR LA LICENCIA  QUWE SE ENCUEBTRA ANULADA.

DNI  28838793 MASCULINO

Tramite: 14878112

Insumo: 005621066

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '28838793' and idTramite = '14878112' /* id 13843500 */

select * from tInsumos where txNumeroInsumo = '005621066'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '13843500'`

**Comment by EliasWasinger** [comment]
Listo, dejo la nueva query:

`select * from tLicencias where txNroLicencia = '28838793' and idTramite = '14878112' /* id 13843500 */

select * from tInsumos where txNumeroInsumo = '005621066' /* id 5655921 */

update tInsumos set txEstado = 'ASIGNADO' where idInsumo = '5655921'

select * from tTramites where idTramite = '14878112'

update tTramites set txEstado = 'EMITIDO' where idTramite = '14878112'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '13843500'`
