### ISSUE TITLE
anulacion licencia(GLPI 4559)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#165]
solicito la anulacion de la siguiente licencia, ya que desde el SiNaLiC, no se puede por estar en estado no vigente.

18332109	08/08/2014	7175575	NO_VIGENTE	RENOVACIÓN	31/07/2014	31/07/2015	A B C	GENERAL PUEYRREDON	BLANCO	GUSTAVO JOSE

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia a anulada, dejo la query:

`select * from tLicencias where txNroLicencia = '18332109' /* id 6814962 */

update tLicencias set txEstado = 'ANULADA' where idLicencia = '6814962'`
