### ISSUE TITLE
Error Producción - SINAI V 1.13.8(GLPI  4572)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#168]
Cuando se quiere ingresar al detalle del acta N° 062000116002440 , 062000116002438 y 062000116003958 sale el siguiente cartel de error "query did not return a unique result: 2". Al detalle se accede desde el menú Actas/ Consulta de actas de contatación, seleccionando la lupa una vez consultada el acta en cuestión.

**Comment by leodimonio** [comment]
Buenas, problema resuelto, saludos
