### ISSUE TITLE
SINALIC -- Cordoba Capital

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#17]
Elias, necesito todos los idCel de estos Centros de Córdoba Capital.

C.Capac. de Transp. y Trans.                    
CPC Nº 8 Pueyrredon                           
CPC CENTRO AMERICA                             
CPC ARGUELLO                                        
CPC Nº 6 LIBERTADOR                                 
CPC Nº2 MONSEÑOR PABLO CABRERA  
CPC RUTA 20                                                     
CPC GUIÑAZU                                                  
CPC Nº 9 RANCAGUA                                    
CPC Nº10 MERCADO DE LA CIUDAD         
CPC Nº12 SAN VICENTE                             
CPC EMPALME                                                 
CPC CHALET COLON

**Comment by EliasWasinger** [comment]
C.Capac. de Transp. y Trans. id = 503

CPC Nº 8 Pueyrredon id = 504

CPC CENTRO AMERICA id = 505

CPC ARGUELLO id = 506

CPC Nº 6 LIBERTADOR id = 507

CPC Nº2 MONSEÑOR PABLO CABRERA id = 508

CPC RUTA 20 id = 509

CPC GUIÑAZU id = 510

CPC Nº 9 RANCAGUA id = 511

CPC Nº10 MERCADO DE LA CIUDAD id = 512

CPC Nº12 SAN VICENTE id = 514

CPC EMPALME id = 513

CPC CHALET COLON id = 515
