### ISSUE TITLE
Informe La Rioja Capital(GLPI 4569)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#170]
Me pidieron del Municipio de La Rioja Capital un informe de actas de todo el año 2015 en el mismo debería contener los datos que figuran en exportar excel (que hace un tiempo que no funciona). Los datos que debería contener el excel es:
NroActa	Fecha_Labrada	Estado	Conductor	Domicilio_Conductor	Titular_Fisico	Titular_Juridico	Domicilio_Titular	Dominio	Tipo_Vehiculo	Marca_Vehiculo	Tema_Infraccion	Articulo_Infraccion	Descripcion_Infraccion	Retuvo_Vehiculo	Lugar_Infraccion	Localidad_Infraccion	Partido_departamento_Infraccion	Provincia_Infraccion	Autoridad_Juzgamiento	Autoridad_Constatacion	Agente_Constatacion	Tipo_Sentencia	Nro_Plan	Estado_Plan	Tipo_Pago	Cantidad_Cuotas	Cantidad_Cuotas_Pagas	Fecha_Generacion_Plan	Fecha_Vencimiento	Fecha_Pago	ImporteTotalFinal

**Comment by leodimonio** [comment]
te mande un mail con el excel
