### ISSUE TITLE
SINALIC -- Modificar Usuario(GLPI 4551)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#171]
Modificar el siguiente usuario del CEL de Villa Allende, Cordoba.

DNI cargado 24105567
DNI correcto 24108567

**Comment by EliasWasinger** [comment]
Listo, se cambió el DNI, dejo la query:

`select * from tUsuarios where txUsuarioAD = '24108567' /* id 4119 */

update tUsuarios set txUsuarioAD = '24108567' where idUsuario = '4119'`
