### ISSUE TITLE
SINALIC -- volver tramite a aprobado (GLPI 4670)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#172]
Por error se anulo todo y habia que dejar el tramite abierto,
se solita volver el tramite a estado aprobado, los datos son, licencia Nº 26544739 , num de insumo 005209603, De la torre raul augusto

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado al trámite a APROBADO, dejo la query:

`select * from tLicencias where txNroLicencia = '26544739' /* tramite id 15157808 */

select * from tTramites where idTramite = '15157808'

update tTramites set txEstado = 'APROBADO' WHERE idTramite = '15157808'`
