### ISSUE TITLE
SINALIC -- volver tramite a aprobado (GLPI 4615) 

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#173]
POR ERROR SE ANULO TODO , SE SOLICITA VOLVER EL TRA,MITE A ESTADO APROBADO dni 36417881, Frias Leonardo Nahuel, masculino, Nro. de insumo 006829731

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite a estado APROBADO, dejo la query:

`select * from tLicencias where txNroLicencia = '36417881'

select * from tTramites where idTramite = '15149684'

update tTramites set txEstado = 'APROBADO' where idTramite = '15149684'`
