### ISSUE TITLE
SINALIC -- Cambiar estado de licencia(GLPI 4695)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#174]
Estimados
buenos dias, por favor, necesito que se realice el cambio de estado a VIGENTE de la Licencia de Conducir del señor SAMUEL EXEQUIEL GALVAN, DNI 39.582.587,

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia a VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '39582587' /* id 8169105 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '8169105'`
