### ISSUE TITLE
ELIMINAR INHABILITACIÓN MAL CARGADA (GLPI 4653)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#175]
Se solicita que se ELIMINE la inhabilitacion registrado con el N° 26.633.864 a nombre de la señora ACOSTA, Hilda del Carmen , ya que ese DNI corresponde a otra persona (PELEGRI NATALIA)

**Comment by leodimonio** [comment]
Listo se borro la inhabilitacion y la persona correspondiente, saludos
