### ISSUE TITLE
Error Producción - SINAI V. 1.13.8 Alta Dependencia(GLPI 4768)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#176]
Cuando quiero dar de alta una dependencia me sale el cartel de error: not-null property references a null or transient valueSinai.Core.Domain.FirmaAutoridadDeConstatacion.Dependencia.
La firma de la autoridad de constatación fue agregada para SICAM y está siendo obligatoria para poder dar de alta la dependencia, si bien adjunto un archivo en blanco no está siendo posible dar de alta la misma.

**Comment by leodimonio** [comment]
finalizado en la version 1.13.8
