### ISSUE TITLE
pasar a estado vigente (GLPI 4807)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#177]
Buenas tardes, solitamos el cambio de estado de la licencia N° 6698818 ( Miguel Catany Francisca), N° de trámite 12723305. Pasar de estado NO VIGENTE a VIGENTE por favor.

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a estado VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '6698818' /* id 11794346 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '11794346'`
