### ISSUE TITLE
SINALIC -- Asignar insumo(GLPI 1916)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#18]
Asignar el siguiente insumo a la licencia ya que se encuentra en estado no vigente y por sistema no lo permite

Licencia N°: 25829685
Insumo N°: 001228047

**Comment by EliasWasinger** [comment]
Se asignó y actualizó 

`begin transaction 
	update tLicencias set idInsumo = '1430232' where idLicencia = '2079707'
	
	update tInsumos set txEstado = 'ASIGNADO' where idInsumo = '1430232'
	
commit`

**Comment by leoimoli** [comment]
Deberíamos, modificar el estado de dicha licencia.

Estado: 'NO_VIGENTE'

**Comment by EliasWasinger** [comment]
Listo, se modificó el estado.
