### ISSUE TITLE
reactivar tramite(GLPI 5100)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#180]
POR ERROR SE ANULO TODO, SE SOLICITA REACTIVAR EL TRAMITE DNI 3901830 DEJARLO EN ESTADO APROBADO

**Comment by EliasWasinger** [comment]
Listo, se cambió el trámite a APROBADO, dejo al query:

`select * from tLicencias where txNroLicencia = '3901830' /* id tramite 13393975 */

select * from tTramites where idTramite = '13393975'

update tTramites set txEstado = 'APROBADO' where idTramite = '13393975'`
