### ISSUE TITLE
LICENCIA ANULADA (GLPI 5088)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#181]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	MACHUCA YANINA ANABEL DNI 29.885.517, MASCULINO, nacida 09/12/1982, nro de insumo 005335639, fecha de la emisión 07/12/2016

MOTIVO DE LA ANULACIÓN:	ERROR EN LA CARGA DE DATOS

**Comment by EliasWasinger** [comment]
La licencia ya se encuentra en estado ANULADA.
