### ISSUE TITLE
SINALIC Modificar estado(GLPI 5070)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#182]
Pasar la siguiente licencia a estado VIGENTE

31955499 04/12/2015 11146184 NO_VIGENTE RENOVACIÓN 15/12/2015 15/12/2020 B A CASILDA MEDINA RAMON ALBERTO 004288755

**Comment by EliasWasinger** [comment]
Listo, se pasó a estado VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '31955499' /* id 10569278 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10569278'`
