### ISSUE TITLE
SINALIC volver a estado aprobado(GLPI 5038)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#183]
volver a estado aprobado el tramite que se encuentra anulado
DNI FERNANDEZ, DIANA ORIETTA LUCIA
DNI 3901830

**Comment by EliasWasinger** [comment]
Listo, se pasó el estado a aprobado, dejo la query:

`select * from tLicencias where txNroLicencia = '3901830' /* id tramite 13393975 */

select * from tTramites where idTramite = '13393975'

update tTramites set txEstado = 'APROBADO' where idTramite = '13393975'`
