### ISSUE TITLE
REACTIVAR LICENCIA Y TRAMITE(GLPI 5139)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#184]
DNI 20615871 MASCULINO 

REACTIVAR LICENCIA Y TRAMITE QUE SE ANULO POR EQUIVOCACION DEL CEL

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a vigente y el trámite a emitido, dejo la query:

`select * from tLicencias where txNroLicencia = '20615871' /* idlicencia 14267264, tiene 3 se toma la mas reciente -- id tramite 15311729*/

select * from tTramites where idTramite = '15311729'

update tLicencias set txEstado='VIGENTE' where idLicencia = '14267264'

update ttramites set txEstado='EMITIDO' where idtramite='15311729'`
