### ISSUE TITLE
Cambio valor de combustible SIM (La Quiaca)(GLPI 5158)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#185]
Nos pidieron desde el Municipio de La Quiaca, provincia de Jujuy que se modifique el valor de combustible a $ 15,39. En el SINAI ya fue modificado, necesitamos que modifique en el SIM.

Provincia: Jujuy.

Partido / Departamento: Yavi.

Localidad: La Quiaca.

**Comment by leodimonio** [comment]
listo ya se cambio el valor combustible
