### ISSUE TITLE
ANULACION DE LICENCIA(GLPI 5163)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#188]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	DNI 30166091
Clases: B1
Nombre y apellido : Bringas, Valeria Stella Maris – Sexo: F
Nro de Insumo 006456252
Fcha emisión 19/12/2016

**Comment by EliasWasinger** [comment]
No se realizó ninguna operación, la licencia y trámite ya se encuentran en estado ANULADA.
