### ISSUE TITLE
anular licencia  NO VIGENTE(GLPI 5168)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#189]
anular la licencia en estado NO VIGENTE ya que se encuentra cargada 2 veces y es la misma
DNI: 16482231

**Comment by EliasWasinger** [comment]
Se pasó la licencia a estado ANULADA, dejo la query:

`select * from tLicencias where txNroLicencia = '16482231' /* id 10629783 */

update tLicencias set txEstado = 'ANULADA' where idLicencia = '10629783'`
