### ISSUE TITLE
SINAI --Reporte - Listado actas pagas San Antonio Oeste julio 2016(GLPI 1953)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#19]
consulta para SAO (el xls se llama SAO_Pagos2015….) de las actas pagas en JULIO con los siguientes campos:

numero_acta
fcFechaCarga
nuImportePagado
fcFechaPagoActa
txApellidoNombreFuncionario
txCargoFuncionario

**Comment by EliasWasinger** [comment]
Se realizó 
SELECT txNumeroActa, fcFechaCarga, nuImportePagado, fcFechaPagoActa, txApellidoNombreFuncionario, txCargoFuncionario FROM [sinai_prod].[dbo].[tActasConstatacion] where fcFechaPagoActa >= '2016-06-29' and fcFechaPagoActa <'2016-08-01'


[SAO_Pagos2016_JULIO.xlsx](https://github.com/leoimoli/Base-De-Datos/files/394554/SAO_Pagos2016_JULIO.xlsx)
