### ISSUE TITLE
anulacion de licencia(GLPI 5165)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#190]
ANULAR LAS LICENCIAS Y LOS TRAMITES QUE SE CORRESPONDAN.
DNI: 26545959

**Comment by EliasWasinger** [comment]
Se pasó la licencia y el trámite a anulados, la persona tenía dos licencias no vigentes emitidas con 3 dias de diferencia, se tomó la más reciente junto con su trámite, dejo la query:
`select * from tLicencias where txNroLicencia = '26545959' /* id 275834  idTramite 315760*/
select * from tTramites where idTramite = '315760'

update tLicencias set txEstado = 'ANULADA' where idLicencia = '275834'

update tTramites set txEstado = 'ANULADO' where idTramite = '315760'`
