### ISSUE TITLE
cantidad de insumos utilizados (GLPI 5218)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#191]
Informe de Cantidad e insumos que se utilizaron en la sede ACA LIBERTADOR de la Ciudad autonoma de buenos aires, en el periodo comprendido entre el 1/12/2016 al 26/12/2016, tanto anulados como asignados

**Comment by EliasWasinger** [comment]
Listo, dejo el excel junto con la query:

[Insumos de ACA LIBERTADOR.xlsx](https://github.com/leoimoli/Base-De-Datos/files/673135/Insumos.de.ACA.LIBERTADOR.xlsx)


`declare @FechaIni datetime
declare @FechaFin datetime
set @FechaIni =  '20161130'   -- dd/mm/yyyy
set @FechaFin =  '20161231'  -- dd/mm/yyyy
SELECT DISTINCT
tInsumos.idCentroEmisionLicencia as idCel,
tCentrosEmisionLicencias.txNombre AS nombreCel,
tInsumos.txNumeroInsumo AS nroInsumo

FROM  tInsumos  JOIN tCentrosEmisionLicencias ON tInsumos.idCentroEmisionLicencia = tCentrosEmisionLicencias.idCentroEmisionLicencia
WHERE 
(tInsumos.txEstado in ('ASIGNADO', 'ANULADO'))
and 
tInsumos.idCentroEmisionLicencia=28 --CEL
and tInsumos.fcFechaAdquisicion BETWEEN @FechaIni AND @FechaFin
GROUP BY tInsumos.idCentroEmisionLicencia, tCentrosEmisionLicencias.txNombre, tInsumos.txNumeroInsumo
order by tCentrosEmisionLicencias.txNombre, tInsumos.txNumeroInsumo`
