### ISSUE TITLE
pasar  licencia a vigente(GLPI 5366)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#192]
pasar  licencia a vigente 
27777163	masc

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia con fecha de emisión más actual a VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '27777163' /* id 10349978 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10349978'`
