### ISSUE TITLE
modificacion insumo(GLPI 5358)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#193]
modificar el numero de insumo asignado a la licencia N° 12150687

Numero a asignar 006302700
Numero a dejar disponible 006302500

**Comment by EliasWasinger** [comment]
Listo, se cambió el insumo asignado a la licencia y se cambiaron los estados de los insumos a recibido en cel y asignado, correspondiente a cada uno, dejo la query:

`select * from tLicencias where txNroLicencia = '12150687' /* id 13588763 idInsumo anterior 6416255*/

select * from tInsumos where txNumeroInsumo = '006302700' /* id 6416455 */
select * from tInsumos where txNumeroInsumo = '006302500' /* id 6416255 */

update tInsumos set txEstado = 'ASIGNADO' where idInsumo = '6416455'
update tInsumos set txEstado = 'RECIBIDO_EN_CEL' where idInsumo = '6416255'

update tLicencias set idInsumo = '6416455' where idLicencia = '13588763'`
