### ISSUE TITLE
LICENCIA ANULADA(GLPI 5356) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#194]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	
6696243,LOLIS AZZARIO RICARDO, MASCULINO,

**Comment by EliasWasinger** [comment]
Se anulo la licencia, la persona tenía una anulada y otra vigente, se anuló la vigente por ser la más reciente. Dejo la query:

`select * from tLicencias where txNroLicencia = '6696243' /* id 14326996 */

update tLicencias set txEstado = 'ANULADA' where idLicencia = '14326996'`
