### ISSUE TITLE
INCIDENTE -ELIMINAR  TIPO DE INHABILITACION EN SINAT(GLPI 5369) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#195]
Solicito en el ANTECEDENTE registrado con DNI: 23147576 a nombre de BRANDAN Rodolfo Francisco, la eliminación del tipo inhabilitacion "DEFINITIVA PENAL" por ser un error en su carga

**Comment by leodimonio** [comment]
Hay que eliminar el antecedente completo, o modificar el tipo de inhabilitacion, y cual seria en ese caso?

**Comment by leoimoli** [comment]
NO hay que eliminar el antecedente completo, solo hay que ELIMINAR el tipo de inhabilitacion que en este caso esta completado como "DEFINITIVA PENAL" es decir que quede sin nada ese campo sin completar.

**Comment by leodimonio** [comment]
Listo ya se realizo el cambio
