### ISSUE TITLE
Error Producción - SINAI V. 1.13.8 Actas Repetidas(GLPI 5414)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#197]
Se encuentran en el SINAI las siguientes actas repetidas:

​062000116044393
​062000116044394
​062000116044395
​062000116044396
​062000116044397
​062000116044398
​062000116044399
​062000116044400
​062000116044401
​062000116051001
​062000116051002
​062000116051003
​062000116051005
​062000116051387
​062000116051390
​062000116051396
​062000116051397
​062000116051399
​062000116051400
​062000116051402
​062000116051403
​062000116051406
​062000116051410
​062000116053178
​062000116053179
​062000116053180
​062000116053402
​062000116053404
​062000116053406
​062000116053407
​062000116055274
​062000116055275
​062000116055281
​062000116055286
​062000116056280
​062000116056284
​062000116056445
​062000116056446
​062000116056447
​062000116056580
​062000116056583
​062000116057990
​062000116057991
​062000116058696
​062000116059222
​062000116059223
​062000116059224
​062000116059226
​062000116059227
​062000116059229
061900616004297
061900616004299
061900616004301

Se debería controlar la base de datos porque deben existir más casos.

**Comment by leodimonio** [comment]
se borraron las duplicadas y se esta viendo si hay mas casos y borrar de ser necesario, saludos
