### ISSUE TITLE
INCIDENTE -ELIMINAR  INHABILITACION  EN SINAT(GLPI 5432) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#198]
Solicito se elimine del SINAT la carga de la INHABILITACION correspondiente al DNI 21338152 (masculino) a nombre de DE DIOS Lucia Edith.

**Comment by leodimonio** [comment]
Listo se Borro el antecedente de tipo INHABILITACION, saludos
