### ISSUE TITLE
Modificar valor combustible (Gral Guemes)(GLPI 5447)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#199]
Por medio de la presente nota solicito modificar el valor de U.F (combustible) de la localidad de Gral Guemes (Provincia de Salta), conforme a lo informado por el municipio el valor actual es de $19,09 (pesos diecinueve con nueve centavos). Saludo muy atte.

**Comment by leodimonio** [comment]
listo ya se realizo el cambio
