### ISSUE TITLE
Pedido IdCel Provincia Corrientes

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#2]
Elias, por favor envíame  el IdCel del siguiente Cel de la base datos de producción.

Provincia: Corrientes
Cel: GOBERNADOR VIRASORO

**Comment by leoimoli** [comment]
Con esta Query consultamos siempre nosotros.

**SELECT     dbo.tCentrosEmisionLicencias.txNumeroIdentificacion AS NroIdentCEL, dbo.tDepartamentosPartidos.txIdentificador AS NroIdentDeptoP, 
dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia AS idCEL, dbo.tCentrosEmisionLicencias.txNombre AS CEL, dbo.tLocalidades.idLocalidad, 
dbo.tLocalidades.txNombre AS Localidad, dbo.tDepartamentosPartidos.idDepartamentoPartido AS idDeptoPartido, 
dbo.tDepartamentosPartidos.txNombre AS DeptoPartido, dbo.tProvincias.idProvincia, dbo.tProvincias.txNombre AS Provincia, dbo.tDomicilios.idDomicilio, 
dbo.tDomicilios.txBarrio, dbo.tDomicilios.txCalle, dbo.tDomicilios.txAltura
FROM         dbo.tCentrosEmisionLicencias INNER JOIN
dbo.tDomicilios ON dbo.tCentrosEmisionLicencias.idDomicilio = dbo.tDomicilios.idDomicilio INNER JOIN
dbo.tLocalidades ON dbo.tDomicilios.idLocalidad = dbo.tLocalidades.idLocalidad INNER JOIN
dbo.tDepartamentosPartidos ON dbo.tLocalidades.idDepartamentoPartido = dbo.tDepartamentosPartidos.idDepartamentoPartido INNER JOIN
dbo.tProvincias ON dbo.tLocalidades.idProvincia = dbo.tProvincias.idProvincia AND dbo.tDepartamentosPartidos.idProvincia = dbo.tProvincias.idProvincia                    
where tProvincias.txNombre = 'CIUDAD AUTÓNOMA DE BS. AS.'**

**Comment by EliasWasinger** [comment]
Leo, el idCEL de GOBERNADOR VIRASORO es: 500

**Comment by leoimoli** [comment]
12/07/2016 
Se informo la resolución.

**Comment by leoimoli** [comment]
Se informo por GLPI.
