### ISSUE TITLE
SINAI -- reporte - descripción infracciones Julio 2016(GLPI 1954)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#20]
necesitaría un xls con la siguiente información para JULIO.
Dependencia
Tema infraccion
Articulo infraccion
Descripción infraccion
Cantidad

**Comment by EliasWasinger** [comment]
Se realizó 

`/****** Script para el comando SelectTopNRows de SSMS  ******/

SELECT	Datepart(YEAR,AC.fcFechaLabradaActa) as Año 
		,Datepart(MONTH,AC.fcFechaLabradaActa ) as Mes
		,InNom.txArticulo as Articulo
		,InNom.txDescripcion as Descripcion
		,TemInf.txNombre as Tema 
		,entidad.txNombre
		,count(InNom.txDescripcion) as Cantidad
		
				
  FROM [tActasConstatacion] AC	
  join [tDetallesInfraccionActa] DIn
  on AC.idActaConstatacion = DIn.idActaConstatacion 
  
  join [tInfraccionesNomenclada] InNom
  on InNom.idInfraccionNomenclada = DIn.idInfraccionNomenclada
  
  join [tTemasInfraccion] TemInf
  on TemInf.idTemaInfraccion = InNom.idTemaInfraccion
  
  join [tAutoridadesDeJuzgamiento] AuJuz
  on AuJuz.idAutoridadDeJuzgamiento = AC.idAutoridadDeJuzgamiento
  
  join [tEntidades] entidad
  on entidad.idEntidad = AuJuz.idEntidad
 
  where 
  
   AC.fcFechaLabradaActa >= '20160701 00:00' 
  and AC.fcFechaLabradaActa <  '20160801 00:00' 
  
    
  
  GROUP BY Datepart(YEAR,AC.fcFechaLabradaActa),Datepart(MONTH,AC.fcFechaLabradaActa), 
			InNom.txDescripcion,TemInf.txNombre, InNom.txArticulo,entidad.txNombre
  
  order by Datepart(MONTH,AC.fcFechaLabradaActa),entidad.txNombre, Cantidad DESC`

[descripción infracciones Julio 2016.xlsx](https://github.com/leoimoli/Base-De-Datos/files/394553/descripcion.infracciones.Julio.2016.xlsx)
