### ISSUE TITLE
EROR PAIS EMISOR(GLPI 5455)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#200]
POR FAVOR MODIFICAR PAIS EMISOR ARGETINA Y NACIONALIDAD BOLIVIANA 

BUEN DÍA, SOLICITO CODIFICACIÓN DE DATOS DE BELTRAN ANTONIO FILIMAN, DNI 95.416.807, SEXO MASCULINO, FECHA DE NACIMIENTO 08/03/1992, NACIONALIDAD BOLIVIA, POR ERROR EN LA CARGA DE DATOS EL DÍA 03/01/2017, EL ERROR ES LA NACIONALIDAD Y EL PAÍS EMISOR DEL DNI ARGENTINA.

**Comment by EliasWasinger** [comment]
Listo, se cambió el país emisor y la nacionalidad, dejo la query:

`select * from tPersonasFisicas where txNumeroDocumento = '95416807'

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '9751742' /* 13 = argentina */

update tPersonasFisicas set idPaisNacionalidad = '29' where idPersonaFisica = '9751742' /* 13 = bolivia */`
