### ISSUE TITLE
modificar fecha(GLPI 5440)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#201]
modificar la fecha de emisión de la siguiente licencia
fecha correcta: 30/12/2015

6133848 30/12/2015 11380897 NO_VIGENTE RENOVACIÓN 02/01/2017 30/12/2016 B ROSARIO DGT PIETROMICA RICARDO LUIS 005110649

**Comment by EliasWasinger** [comment]
Listo, se cambió la fecha de emisión, dejo la query:

`select * from tLicencias where txNroLicencia = '6133848' /* id 14364509 */

update tLicencias set fcFechaEmision = '2015-12-30 13:49:50.000' where idLicencia = '14364509' `
