### ISSUE TITLE
Error Producción - SINAI V. 1.13.8(GLPI 5110)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#202]
En el SINAI se encuentran actas repetidas. Se puede consultar por el MPK607 o por el DNI 16214909.
Adjunto Imagenes de la Consulta por SINAI y por página web. Actas repetidas: 062000116057750, 062000116057751
Se debería verificar si es que existen más casos.

**Comment by leodimonio** [comment]
listo ya se realizo el cambio
