### ISSUE TITLE
SOLICITUD- NUMERO DE ID SINAT(GLPI 5457)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#204]
Solicito para dar de alta un juzgado para la provincia de Santa Fe que carga los datos por web service el ID SINAT del siguiente lugar: 

DEPENDENCIA : ROLDAN
DEPARTAMENTO: San Lorenzo
JURISDICCIÓN: SANTA FE
TRIBUNAL DE FALTAS

**Comment by leodimonio** [comment]
El ID de la Autoridad de juzgamiento es **889**
