### ISSUE TITLE
SIM PRODUCCION / URGENTE(GLPI 5452)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#209]
Se debe agregar 3 artículos a la ordenanza vigente de Villa La Angostura ( Ord. 1169), pcia. de Neuquen . 
Articulo 139 inciso a, b y c. Los mismos no tienen porcentaje de descuento.

**Comment by leodimonio** [comment]
ya estaban agregadas estas infracciones y figuran sin porcentaje de descuento
