### ISSUE TITLE
SINAI -- Reporte - Listado actas pagas y labradas julio 2016(GLPI 1952)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#21]
Para los datos de gestión necesito las actas generadas en el mes de JULIO (por fecha de labrado), por jurisdicción por medio de constatación y otro con las actas pagas (por fecha de pago) por jurisdicción por medio de constatación también para JULIO. Mil gracias. 
Los nombres de las consultas son 
Estadisticaslabradas
EstadisticasPagos

**Comment by EliasWasinger** [comment]
Listo, te dejo los excel:
[Actas_Constatacion_JULIO_2016.xlsx](https://github.com/leoimoli/Base-De-Datos/files/397093/Actas_Constatacion_JULIO_2016.xlsx)
[Actas_Labradas_JULIO_2016.xlsx](https://github.com/leoimoli/Base-De-Datos/files/397094/Actas_Labradas_JULIO_2016.xlsx)


Acá te dejo los script:


`
--
-- Version 6 sin VO y CABA . por mes
--


select medio, DATEADD( m, DATEDIFF( m, 0, fcFechaPagoActa ), 0 ) mes_pago, jurisdiccion, dependencia, COUNT(distinct idActaConstatacion) cant, SUM (importecupones) total
from 
(
select m.txNombre Medio, a.idActaConstatacion, a.fcFechaPagoActa, e2.txNombre jurisdiccion, e.txNombre dependencia, a.nuImportePagado, sum(c.nuImportePago) importecupones
  from tActasConstatacion a
    left outer join tMediosConstatacion m on a.idMedioConstatacion = m.idMedioConstatacion
    left outer join tPlanDePago p on a.idActaConstatacion = p.idActaConstatacion
    left outer join tCuponDePago c on p.idPlanDePago = c.idPlanDePago
	inner join tAutoridadesDeJuzgamiento au on a.idAutoridadDeJuzgamiento = au.idAutoridadDeJuzgamiento 
	inner join tEntidades e on au.idEntidad = e.idEntidad 
    left outer join tEntidades e2 on e.idJurisdiccion = e2.idEntidad
 where 
    coalesce(p.idPlanDePago,0) = (select coalesce(max(p2.idPlanDePago),0) from tPlanDePago p2 where a.idActaConstatacion = p2.idActaConstatacion)
--    and a.idAutoridadDeJuzgamiento != 239 
--    and e.idJurisdiccion != 25
    and a.fcFechaPagoActa between '2016-06-30 23:59' and '2016-07-31 23:59'
group by m.txNombre, a.idActaConstatacion, a.fcFechaPagoActa, e2.txNombre, e.txNombre, a.nuImportePagado  
) z
--where importecupones > 0
group by medio, DATEADD( m, DATEDIFF( m, 0, fcFechaPagoActa ), 0 ), jurisdiccion, dependencia


--
-- v7 Actas Labradas
--

select medio, DATEADD( MM, DATEDIFF( MM, 0, fcFechaLabradaActa ), 0 ) mes_labrada, jurisdiccion, dependencia, COUNT(distinct idActaConstatacion) cant
from 
(
select m.txNombre Medio, a.idActaConstatacion, a.fcFechaLabradaActa, e2.txNombre jurisdiccion, e.txNombre dependencia
  from tActasConstatacion a
    left outer join tMediosConstatacion m on a.idMedioConstatacion = m.idMedioConstatacion
	inner join tAutoridadesDeJuzgamiento au on a.idAutoridadDeJuzgamiento = au.idAutoridadDeJuzgamiento 
	inner join tEntidades e on au.idEntidad = e.idEntidad 
    left outer join tEntidades e2 on e.idJurisdiccion = e2.idEntidad
 where 1=1
--    and e.idJurisdiccion = 25
--    and a.idAutoridadDeJuzgamiento != 239 
--    and e.idJurisdiccion != 25
    and a.fcFechaLabradaActa between '2016-06-30 23:59' and '2016-07-31 23:59'
group by m.txNombre, a.idActaConstatacion, a.fcFechaLabradaActa, e2.txNombre, e.txNombre
) z
--where importecupones > 0
group by medio, DATEADD( MM, DATEDIFF( MM, 0, fcFechaLabradaActa ), 0 ), jurisdiccion, dependencia
`
