### ISSUE TITLE
CEL Las Heras(GLPI 5520)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#211]
Pasar la licencia a estado no vigente:
36226812 07/07/2016 13431191 VIGENTE ORIGINAL 20/09/2013 20/09/2018 B SAN MIGUEL LAGUNA JORGE EMANUEL

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '36226812' /* id 12468647 */

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '12468647'`
