### ISSUE TITLE
error en sinalic(GLPI 5667)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#213]
cambiar a estado VIGENTE estas 2 licencias por figurar error en el sistema. que adjunto Buen día, estamos teniendo problemas con un par de tramites en el cual aparece el error adjunto. 
Datos de las personas con problemas: 
Nombre: Jorge Oscar Apellido: Rossi DNI: 27729796 
Nombre: Rolando Apellido: Pisanu DNI: 38783879

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los estados de las licencias, se tomaron las licencias con fecha de emisión más reciente, dejo la query:

`select * from tLicencias where txNroLicencia = '27729796' /* id 14440410 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14440410'`

Caso 2:
`select * from tLicencias where txNroLicencia = '38783879' /* id 14439853 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14439853'`
