### ISSUE TITLE
asigna insumo(GLPI 5714)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#215]
asignar el insumo a la siguiente reimpresion de licencia ya que al estar asignado a la jurisdicción el sistema no lo permite

Licencia N° 13253090
insumo N° 006569281

**Comment by EliasWasinger** [comment]
Listo, se asigno el insumo a la licencia y se cambió el estado del insumo a asignado, dejo la query:

`select * from tLicencias where txNroLicencia = '13253090' /* id 7998598 */

select * from tInsumos where txNumeroInsumo = '006569281' /* id 6968336 */

update tLicencias set idInsumo = '6968336' where idLicencia = '7998598'

update tInsumos set txEstado = 'ASIGNADO' where idInsumo = '6968336'`
