### ISSUE TITLE
cambio de estado de licencia(GLPI 5797)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#218]
7394563 masc de estado anulada a vigente

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '7394563' /* id 10782745 */


update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10782745'`

**Comment by leoimoli** [comment]
La licencia debe pasarse a estado NO_VIGENTE.

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a NO VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '7394563' /* id 10782745 */

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10782745'`
