### ISSUE TITLE
IdCel SINALIC 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#221]
Se necesita los id de Centro de los siguientes:
CORRIENTES CAPITAL
CHACO - RESISTENCIA

**Comment by EliasWasinger** [comment]
Listo, dejo los id de los CELs:
CORRIENTES CAPITAL = Figura como CORRIENTES, ID = 20
CHACO - RESISTENCIA = Figura como RESISTENCIA , ID = 541
