### ISSUE TITLE
Listado  de Licencias informadas Buenos Aires(GLPI 5844)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#223]
Buenos días 
por favor podrían proporcionar el listado de todas las licencias informadas de noviembre y diciembre del 2016 de la provincia de Buenos Aires.
con los siguientes campos:

NroInsumo
NroFormularioCENAT
CodigoBarraSAFIT
ImporteAbonadoSAFIT
FechaPagoSAFIT
NrocomprobanteSAFIT
IdCEL
NombreCEL
IdTipoTramite
NombreTipoTramite
NroTramite
SubClases (separadas por punto y coma ; )
EsDonante
FechaOtorgamiento
FechaVencimiento
Licencia_Observaciones					
Licencia_Estado
GrupoSanguineo
FactorSanguineo
Email
Telefono
Celular
CodTelefono
CodCelular
Estudio
FechaNacimiento
Nacionalidad
Apellido
Nombre
idTipoDocumento
NumeroDocumento
Sexo
domicilio_Altura
domicilio_Barrio
domicilio_Calle
domicilio_CPA
domicilio_Departamento
DomecilioPiso
domicilio_IdLocalidad

**Comment by EliasWasinger** [comment]
Listo, dejo el excel y la query:

[Listado de Licencias informadas Buenos Aires - Noviembre y Diciembre.xlsx](https://github.com/leoimoli/Base-De-Datos/files/716807/Listado.de.Licencias.informadas.Buenos.Aires.-.Noviembre.y.Diciembre.xlsx)

`declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='BUENOS AIRES';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	dbo.tCentrosEmisionLicencias.txNombre AS CEL,
	dbo.tLicencias.fcFechaEmision,
	dbo.tLicencias.txTipoDocumento,
	dbo.tLicencias.txNroLicencia as NumeroDocumento,
	dbo.tLicencias.txNroLicencia,
	dbo.tLicencias.txEstado AS EstadoLicencia,
	dbo.tLicencias.fcFechaVencimiento,
	dbo.tLicencias.txApellidoLicencia,
	dbo.tLicencias.txNombreLicencia,
	dbo.tLicencias.txObservaciones,
	dbo.tLicencias.fcFechaNacimientoLicencia,
	dbo.tLicencias.txSexoLicencia,
	dbo.tLicencias.txTipoSanguineo,
	dbo.tLicencias.txFactorSanguineo,
	dbo.tLicencias.txCalle,
	dbo.tLicencias.txClasesLicencia,
	dbo.tLicencias.txBarrio,
	dbo.tLicencias.txLocalidad,
	dbo.tLicencias.txAltura,
	dbo.tLicencias.txPiso,
	dbo.tLicencias.txCodigoPostal,
	dbo.tLicencias.txNacionalidad,
	dbo.tTramites.idTramite,
	dbo.tTramites.flDonante as esDonante,
	ttramites.txNumeroFormulario,
	dbo.tTramites.idTramite as NumeroTramite,
	dbo.tTramites.idCentroEmisionLicencia,
	dbo.tTramites.fcFechaInicioTramite,
	dbo.tTramites.nuImporteAbonadoSAFIT,
	dbo.tTramites.fcFechaPagoCupon,
	dbo.tTramites.txCodigoBarraSAFIT,
	dbo.tTramites.txNumeroComprobanteSAFIT,
	dbo.tTramites.txNumeroFormulario,
	dbo.tCategoriasLicencia.txNombre AS CategoriasLicencia,
	dbo.tPersonasFisicas.txNombre AS NombreCiudadano,
	dbo.tPersonasFisicas.txApellido AS ApellidoCiudadano,
	dbo.tPersonasFisicas.txNumeroDocumento AS Nrodocumento,
	dbo.tPersonasFisicas.txSexo AS SexoCiudadano,
	dbo.tPersonasFisicas.fcFechaNacimiento AS FechaNacimientoCiudadano,
	dbo.tPersonasFisicas.txTelefono,
	dbo.tPersonasFisicas.txEmail,
	dbo.tPersonasFisicas.txCelular,
	dbo.tPersonasFisicas.txCodCelular,
	dbo.tPersonasFisicas.txCodTelefono,
	dbo.tPersonasFisicas.txNivelEducativo,
	dbo.tPersonasFisicas.fcFechaNacimiento
	/*dbo.tInsumos.txNumeroInsumo*/

FROM
	dbo.tLicencias
	/*INNER JOIN dbo.tInsumos ON dbo.tLicencias.idInsumo = dbo.tInsumos.idInsumo*/
	INNER JOIN dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite
	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	INNER JOIN dbo.tPersonasFisicas ON dbo.tTramites.idPersonaFisica = dbo.tPersonasFisicas.idPersonaFisica
	INNER JOIN dbo.tCategoriasLicencia ON dbo.tTramites.idCategoriaLicencia = dbo.tCategoriasLicencia.idCategoriaLicencia
	INNER JOIN dbo.tTiposDocumento ON dbo.tPersonasFisicas.idTipoDocumento = dbo.tTiposDocumento.idTipoDocumento
	 

WHERE  
	ttramites.idCentroEmisionLicencia 
		IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))
       AND tLicencias.fcFechaEmision BETWEEN '2016-11-01 00:00:00.000' AND '2016-12-31 00:00:00.000'

ORDER  BY 
	dbo.tCentrosEmisionLicencias.txNombre,
	dbo.tLicencias.fcFechaEmision,
	dbo.tLicencias.txApellidoLicencia,
	dbo.tLicencias.txNroLicencia 


`
