### ISSUE TITLE
Agregar subclases(GLPI 5940) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#224]
Agregar subclases a la siguiente licencia

25235863 16/12/2012 2070547 VIGENTE ORIGINAL 16/12/2012 27/11/2017 A B NECOCHEA GOMEZ JOSE MARIA 

subclases A21, B1 y B2

**Comment by EliasWasinger** [comment]
Listo, se agregaron las clases a la tabla de trámites, dejo la query:

`select * from tLicencias where txNroLicencia = '25235863' /* id 1924750 tramite 2070547 | clases A B */


begin transaction
	INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (2070547,4)
	INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (2070547,9)
	INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (2070547,10)
commit`
