### ISSUE TITLE
agregar subclases(GLPI 5921)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#225]
Agregar las subclases a las siguientes licencia

3180048 EMITIDO 28/06/2013 11:58:16 p.m. 32180294 RAMON DIEGO DE OLIVERA ORIGINAL 0 

DNI: 32180294 
Sublases A3, B1, B2

**Comment by EliasWasinger** [comment]
Listo, se agregaron las clases a la tabla de trámites y clases, dejo la query:

`select * from tLicencias where txNroLicencia = '32180294' /* tramite 3180048 | clases A B */


begin transaction
	INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (3180048,6)
	INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (3180048,9)
	INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (3180048,10)
commit`
