### ISSUE TITLE
agregar subclases(GLPI 6107)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#226]
Agregar la subclase B2 a la siguiente licencia

2509646 EMITIDO 10/03/2013 02:50:19 a.m. 92980225 FIDEL VASQUEZ ALACAMA ORIGINAL 0

**Comment by EliasWasinger** [comment]
Listo, se agregó la subclase a la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '92980225' /* tramite 2509646 */

begin transaction
INSERT INTO tClasesLicenciasPorTramite(idTramite, idClaseLicencia) VALUES (2509646,10)
commit`
