### ISSUE TITLE
Alta de juzgado San Pedro/jUJUY en sistema SIM-Urgente(GLPI 6150)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#227]
Estimados:

Se requiere el alta del Municipio de San Pedro en PROD SIM.

- Autoridad de Juzgamiento: "JUZGADO DE FALTAS MUNICIPAL" con ID SAFIT 1516
- Dirección física: Rogelio Leach N° 375
- Teléfono:
- Horario de atención: 07:00 a 14:00hs y de 15:00 a 21:00hs
- Correo electrónico: juzfaltas.spedrojujuy@gmail.com
- Valor combustible: $ 10
- Nombre de la Autoridad de Constatación: Municipalidad de San Pedro
- Partido al que se asocia la Autoridad de Constatación: San Pedro
- Provincia al que se asocia la Autoridad de Constatación: Jujuy
- Archivo del Logo J21A008.pcx
- Id 21 para Jujuy
- Código: 008
- Adhesión a la ordenanza 437/11

**Comment by leodimonio** [comment]
Listo, ya se agrego el juzgado con su respectiva adhesion a ley decreto
