### ISSUE TITLE
Agregar en SIM Ordenanza 815/16 cargada en SINAI del municipio de Añatuya pcia. Sgo. del Estero. (mantener 437/11) (GLPI 5960))

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#229]
Se solicita agregar en SIM para que se puedan labrar actas en PDA de la legislacion que fue dada de alta en SINAI. Correspondiente a la Ordenanza municipal 815/16, articulo 3 (prohibicion de de el ingreso de camiones de gran porte al casco urbano) del municipio de Añatuya de la provincia de Santiago del Estero. (Ademas mantener 437/11)

**Comment by leodimonio** [comment]
Listo ya se agrego la ordenanza y se adhirio a Añatuya
