### ISSUE TITLE
SINAI -- Reporte - Listado actas pagas y labradas julio 2016(GLPI 1952)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#23]
Para los datos de gestión necesito las actas generadas en el mes de JULIO (por fecha de labrado), por jurisdicción por medio de constatación y otro con las actas pagas (por fecha de pago) por jurisdicción por medio de constatación también para JULIO. Mil gracias. 
Los nombres de las consultas son 
Estadisticaslabradas
EstadisticasPagos

Mil gracias. SAludos

**Comment by EliasWasinger** [comment]
Done.

[ActasLabradas_JULIO.xlsx](https://github.com/leoimoli/Base-De-Datos/files/401628/ActasLabradas_JULIO.xlsx)
[ActasPagas_JULIO.xlsx](https://github.com/leoimoli/Base-De-Datos/files/401629/ActasPagas_JULIO.xlsx)
