### ISSUE TITLE
modificar estado(GLPI 6125)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#230]
Pasar la siguiente licencia a estado "VIGENTE" 

8506431 04/11/2015 10904819 NO_VIGENTE RENOVACIÓN 04/11/2015 04/11/2020 B ROSARIO DGT MUBILLA JUAN CARLOS 004483975

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '8506431' /* id 10278065 */

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10278065'`
