### ISSUE TITLE
Modificar Nacionalidad(GLPI 6154)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#231]
Estimados:
 El Sr. VICTOR ANGULO GUZMAN - DNI Nº 92.865.480 de Nacionalidad Boliviana, se presentó en este CEL SALTA-CAPITAL para solicitar su Licencia Nacional, por error involuntario del operador en la carga de datos, puso: 
 en el campo País emisor de documento: BOLIVIA y en el campo Nacionalidad: ARGENTINA.
Modificar la nacionalidad de ARGENTINA A BOLIVIA

**Comment by EliasWasinger** [comment]
Listo, se cambió el país emisor y el de nacionalidad, dejo la query:

`select * from tPersonasFisicas where txNumeroDocumento = '92865480' /* id 9864456 */

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '9864456'

update tPersonasFisicas set idPaisNacionalidad = '29' where idPersonaFisica = '9864456'`
