### ISSUE TITLE
Anulación de licencia y tramite  en estado NO VIGENTE(GLPI 6482)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#235]
Solicitan anular la licencia Nro: 8532935. El tramite ya fue anulado pero requieren anular también la licencia y el insumo asociado a dicha licencia.

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia de estado no vigente a anulada, dejo la query:
`select * from tLicencias where txNroLicencia = '8532935'

update tLicencias set txEstado = 'ANULADA' where idLicencia = '2551377'`
