### ISSUE TITLE
Cambio valor de combustible SIM(GLPI 6551)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#237]
Nos solicitaron del Municipio de Sierra Grande el cambio de valor de combustible a $17,27. Ya se realizó el cambio en el SINAI, necesitamos que se actualice en el SIM.

Provincia: Rio Negro
Departamento / Partido: San Antonio
Localidad: Sierra Grande

**Comment by leodimonio** [comment]
Listo, ya se actualizo el valor combustible, saludos
