### ISSUE TITLE
SINALIC -- modificar estado(GLPI 6610)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#238]
Pasar la siguiente licencia a estado "VIGENTE"

33415747 17/11/2015 11034687 NO_VIGENTE RENOVACIÓN 10/11/2015 10/11/2017 A B C D E G BERISSO PAVON NAHUEL

**Comment by EliasWasinger** [comment]
Se cambió a vigente la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '33415747'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10397067'`
