### ISSUE TITLE
modificar estado(GLPI 6577)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#239]
Solicito pasara a estado "VIGENTE" la sigiente licencia

31658231 01/04/2015 9028807 NO_VIGENTE RENOVACIÓN 01/04/2015 01/04/2020 A B SEDE CHACABUCO PERALTA ROMINA PAOLA 003948466

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a vigente, dejo la query:

`select * from tLicencias where txNroLicencia = '31658231'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '8522400'`
