### ISSUE TITLE
SINALIC -- LICENCIAS EMIITIDAS(GLPI 2049)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#24]
¿Me pueden pasar el archivo por las licencias emitidas por mes y por CEL, de Enero a Julio 2016?
Muchas Gracias

**Comment by EliasWasinger** [comment]
Done
[Licencias emitidas de Enero a Julio 2016.xlsx](https://github.com/leoimoli/Base-De-Datos/files/403765/Licencias.emitidas.de.Enero.a.Julio.2016.xlsx)
