### ISSUE TITLE
Modificar estado(GLPI 6582)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#240]
solicito cambiar el estado de la siguiente licencia a "VIGENTE"

37963218 21/02/2017 15862433 ANULADA RENOVACIÓN 21/02/2017 21/02/2022 A B LUJAN DE CUYO IACONO MARTIN ADRIAN 007115530

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a vigente, dejo la query:

`select * from tLicencias where txNroLicencia = '37963218'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14744527'`
