### ISSUE TITLE
Error SINALIC(GLPI 6668)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#241]
Pasar a estado VIGENTE la siguiente licencia 28044060 23/02/2016 11937227 NO_VIGENTE RENOVACIÓN 06/01/2016 06/01/2021 A B CORONEL ROSALES MARTINEZ ANDREA INES

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a vigente, dejo la query:

`select * from tLicencias where txNroLicencia = '28044060'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '11244274'`
