### ISSUE TITLE
Sinalic -- Consulta

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#25]
Necesitamos saber la fecha y hora del inicio de tramite de los siguientes tramites.

Nro.Tramite: 13475305
Nro.Tramite: 13687173
Nro.Tramite: 13470936
Nro.Tramite: 13475498

**Comment by EliasWasinger** [comment]
Te dejo los trámites con fecha y hora:

Nro.Tramite: 13475305         2016-07-13 11:38
Nro.Tramite: 13687173         2016-07-29 16:32
Nro.Tramite: 13470936         2016-07-13 08:22
Nro.Tramite: 13475498         2016-07-13 11:47
