### ISSUE TITLE
SINAI--MODIFICACIÓN DNI EN EL SISTEMA(GLPI 6772)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#251]
Se solicita que se modifique el DNI del antecedente registrado con el N° 6.274.076 a nombre del señor BUCETA DANIEL HORACIO, por el correcto que es el DNI N° 16.938.096

**Comment by leodimonio** [comment]
Listo ya se actualizo el documento de la persona, saludos
