### ISSUE TITLE
solicito reporte de licencias NO IMPRESAS(GLPI 6700)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#252]
Estimados, solicito reporte detallado de licencias NO IMPRESAS de los centros emisores de licencias de MAIPU y CORRIENTES, ambos pertenecen a CORRIENTES CAPITAL.

**Comment by EliasWasinger** [comment]
Listo, dejo el excel con las no impresas de CORRIENTES, el CEL MAIPU no existe.

[Corrientes - No impiresas - GLPI 6700.xlsx](https://github.com/leoimoli/Base-De-Datos/files/816916/Corrientes.-.No.impiresas.-.GLPI.6700.xlsx)
