### ISSUE TITLE
Cambiar estado trámite(GLPI 6733)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#253]
Se solicita pasar el trámite de estado anulado a aprobado.
ARCE, NICOLAS AVEL
DNI 6890164
Nro:Tramite = 15857612

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de trámite a aprobado, dejo la query:

select * from tTramites where idTramite = '15857612' 


update tTramites set txEstado = 'APROBADO' where idTramite = '15857612'
