### ISSUE TITLE
solicito eliminen un registro triplicado en sistema(GLPI 6802)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#255]
el sr. Chimieliauskas Mario Dante, DNI n° 12843143 posee un registro triplicado en sistema de la localidad de quilmes provincia de buenos aires, necesito si eliminan el registro que corresponde a los tramites 14825334 y 14825418, ya que los mismos impiden la creacion de un nuevo tramite.-

**Comment by EliasWasinger** [comment]
Listo, se eliminó la licencia y los trámites correspondientes, dejo las querys:

`select * from tLicencias where txNroLicencia = '12843143' and idTramite = '14825334' /* id 13792957 */

delete from tLicencias where idLicencia = '13792957';

delete from tClasesLicenciasPorTramite where idTramite = '14825334';
delete from tWorksFlowTramite where idTramite = '14825334';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14825334');
delete from tExamenesPsicoFisico where idTramite = '14825334'
delete from tResultadosExamenTPCurso where idTramite = '14825334';

delete from tTramites where idTramite = '14825334';

/* ==================================================================================================== */

select * from tLicencias where txNroLicencia = '12843143' and idTramite = '14825418' /* id 13793015 */

delete from tLicencias where idLicencia = '13793015';

delete from tClasesLicenciasPorTramite where idTramite = '14825418';
delete from tWorksFlowTramite where idTramite = '14825418';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14825418');
delete from tExamenesPsicoFisico where idTramite = '14825418'
delete from tResultadosExamenTPCurso where idTramite = '14825418';

delete from tTramites where idTramite = '14825418';`
