### ISSUE TITLE
Cambiar Estado Tramite(GLPI 6854)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#256]
se solicita volver a estado de APROBADO el tramite anulado
dni 33832409

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite a aprobado, dejo la query:

`select * from tLicencias where txNroLicencia = '33832409' /* id tramite 15854323 */


select * from tTramites where idTramite = '15854323'

update tTramites set txEstado = 'APROBADO' where idTramite = '15854323'`
