### ISSUE TITLE
Munic.Rawson - Pcia de San Juan, Cambio porcentaje de descuento infracciones labradas por PDA(GLPI 6775)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#258]
Solicito que las infracciones labradas por dispositivo PDA de la jurisdiccion mencionada, tengan el 40% de descuento en el pago voluntario s/normativa municipal, como asi tambien, solicito que figure este importe en el comprobante de pago que entregan los agentes al presunto infractor. 
Esta modificacion ya fue generada en SINAI. Falta en el SIM. Sin mas que decir, saluda atte.

**Comment by leodimonio** [comment]
Se modifico el porcentaje de descuento para todas las infracciones, de dicha ordenanza, saludos
