### ISSUE TITLE
ALTA EN SIM - MUNICIPIO HUMAHUACA (JUJUY). TENER EN CUENTA DESCUENTOS POR PAGO VOLUNTARIO Y ALCOHOLEMIA(GLPI 6926)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#259]
Estimados:

Se requiere el alta del Municipio de Humahuaca en PROD SIM.

- Autoridad de Juzgamiento: "JUZGADO ADMINISTRATIVO DE FALTAS" con ID SAFIT 1527
- Dirección física: Entre Ríos esquina Santa Fe
- Teléfono:
- Horario de atención: 07:00 a 13:00hs
- Correo electrónico: humahuaca@outlook.com
- Valor combustible: $ 19,80
- Nombre de la Autoridad de Constatación: Municipalidad de Humahuaca
- Partido al que se asocia la Autoridad de Constatación: Humahuaca
- Provincia al que se asocia la Autoridad de Constatación: Jujuy
- Archivo del Logo J21A011.pcx
- Id 21 para Jujuy
- Código: 011
- Adhesión a la ordenanza DECRETO 779/95

ACLARACIÓN: LA JURISDICCIÓN UTILIZA EL 25% DE DESCUENTO PARA EL PAGO VOLUNTARIO, SALVO PARA LAS INFRACCIONES DE ALCOHOLEMIA QUE APLICA EL 0% DE DESCUENTO.

**Comment by leodimonio** [comment]
Listo ya se realizo el cambio, los porcentajes de descuentos son los mismo que tiene configurado el sinai saludos
