### ISSUE TITLE
SINALIC -- Reportes(GLPI 2093)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#26]
1) Detalle de licencias emitidas desde el 29/07/2016 hasta hoy con clases A21, B2 o C. 

2) Usuarios con Perfil ANSV.

**Comment by EliasWasinger** [comment]
Te dejo los excel, en usuarios les puse el usuarioAD, no sé si necesitan más datos de cad ausuario.
Te pido que abras los excel y los mires, antes de enviarlos.

[Usuarios con perfil ASNV.xlsx](https://github.com/leoimoli/Base-De-Datos/files/407238/Usuarios.con.perfil.ASNV.xlsx)
[Licencias emitidas por Clase.xlsx](https://github.com/leoimoli/Base-De-Datos/files/407237/Licencias.emitidas.por.Clase.xlsx)
