### ISSUE TITLE
Cambio de normativa SIM (Rosario del Tala)(GLPI 6869)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#262]
Necesito que se modifique la normativa de Rosario del Tala en el Sim. Actualmente se encuentra cargado el decreto 437. Nos informaron de la jurisdicción que dicho decreto no se va a utilizar. Por tal motivo, solicitamos que se cargue la ordenanza municipal 1545 de rosario del Tala y se dé de baja el decreto 437.

**Comment by leodimonio** [comment]
Listo, se agrego la ordenanza 1545/16, y se hizo su correspondiente adhesion, ademas se quito la adhesion al decrete 437, saludos
