### ISSUE TITLE
cambiar pais emisor a argentina(GLPI 7037)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#264]
Cambiar pais emisor a argentina el ciudadano, es DOMINGUEZ, JOSE LUIS DNI 93.784.821 NACIONALIDAD ESPAÑOLA, 13/12/1943,

**Comment by EliasWasinger** [comment]
Listo se cambio el pais emisor a 13 (argentina)

`select * from tPersonasFisicas where txNumeroDocumento = '93784821' /* id 918460 */

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '918460'`
