### ISSUE TITLE
ALTA EN SIM -MUNICIPIO VALLE HERMOSO (CORDOBA)(GLPI 7012) 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#265]
Se requiere el alta del Municipio de Valle Hermoso en PROD SIM.

- Autoridad de Juzgamiento: "AREA ADMINISTRATIVA DE FALTAS" con ID SAFIT 1532
- Dirección física: Avenida Sabattini N° 315
- Teléfono: 03548 - 470635
- Horario de atención: 07:00 a 14:00hs
- Correo electrónico: 
- Valor combustible: $ 22,90
- Nombre de la Autoridad de Constatación: Municipalidad de Valle Hermoso
- Partido al que se asocia la Autoridad de Constatación: Punilla
- Provincia al que se asocia la Autoridad de Constatación: Córdoba
- Archivo del Logo J11A014.pcx
- Id 11 para Córdoba
- Código: 014
- Adhesión a la ordenanza ORDENANZA 912/2016

ACLARACIÓN: LA JURISDICCIÓN UTILIZA EL 50% DE DESCUENTO PARA EL PAGO VOLUNTARIO PARA TODAS LAS INFRACCIONES.

**Comment by leodimonio** [comment]
Listo, ya se agrego el juzgado, autoridad de constatacion, su ordenanza y su correspondiente adhesion, saludos
