### ISSUE TITLE
Cambio valor de combustible SIM (Puerto Esperanza)(GLPI 7067)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#267]
Nos solicitaron desde el Municipio de Puerto Esperanza el cambio de combustible a $21,37.
Ya está modificado el mismo en el SINAI solicitamos se realice la modificación en el SIM.

Provincia: Misiones
Partido / Departamento: Iguazú
Localidad Puerto Esperanza

**Comment by leodimonio** [comment]
Listo , ya se cambio el valor combustible, saludos
