### ISSUE TITLE
Usuario SINAI - V 1.13.8 (De Usuario de Entidad a Usuario Funcionario)(GLPI 7113)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#268]
Solicito poder asociar el Usuario de entidad 30231954 al funcionario cargado recientemente para el Juzgado N°2 de Neuquén Capital.
Dicho usuario estaba cargado como Usuario de entidad. Ahora como vamos a implementar en Neuquén Capital dicho Usuario aparece en el Juzgado N°2, lo que habría que hacer es asociar ese usuario al funcionario cargado ya en el SINAI.

**Comment by leodimonio** [comment]
Listo, ya se asocio el usuario al funcionario correspondiente, saludos
