### ISSUE TITLE
solicito cambio de estado de una licencia(GLPI 7130)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#269]
Estimados, solicito el cambio de estado de una licencia que se encuentra ANULADA, y requiero que se pase a VIGENTE

DNI 21699628 SEXO MASCULINO NUMERO DE TRAMITE 8936579 GUTIERREZ JUAN CARLOS INSUMO 003217949

**Comment by EliasWasinger** [comment]
Se cambió el estado de la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '21699628'  /* id 8451898 */


update tLicencias set txEstado = 'VIGENTE' where idLicencia = '8451898'`
