### ISSUE TITLE
cambiar de estado(GLPI 7158)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#270]
Poner tramite anulado en estado aprobado.
DNI 33046434 masc

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite

`select * from tLicencias where txNroLicencia = '33046434' 
 
select * from tTramites where idTramite = '15902309'

update tTramites set txEstado = 'APROBADO' where idTramite = '15902309'`
