### ISSUE TITLE
Corregir Medio de Constatación(GLPI 7138)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#271]
El acta número 061400617000118 de Rawson, quedo cargado con el medio de constatación AUI MANUALMENTE SOBRE PAPEL., si bien el acta fue confeccionada por la PDA. El medio de constatación cambio cuando se edito desde el SINAI ya que estaba en Juzgado.

**Comment by leodimonio** [comment]
Listo, ya se cambio el medio de constatacion a PDA, saludos
