### ISSUE TITLE
solicito reporte de licencias(GLPI 7178)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#273]
estimados necesito saber:

DE LA PROVINCIA DE SALTA

TOTAL DE LICENCIAS EMITIDAS
TOTAL DE LICECIAS MENSUALES (UN MES COMO PARAMETRO)
TOTAL DE CENTROS

**Comment by EliasWasinger** [comment]
Listo, dejo el excel con las querys correspondientes:

[Reporte SALTA.xlsx](https://github.com/leoimoli/Base-De-Datos/files/855081/Reporte.SALTA.xlsx)

/* CELS de SALTA */

/* tramites en estado EMITIDO en SALTA por MES */

declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='SALTA';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	COUNT(1) as Cantidad from dbo.tCentrosEmisionLicencias
WHERE 
	tCentrosEmisionLicencias.idCentroEmisionLicencia 
	IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))



/* tramites en estado EMITIDO en SALTA por MES */

declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='SALTA';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	DATEPART(Month, tTramites.fcFechaInicioTramite) as MES,
	DATEPART(YEAR, tTramites.fcFechaInicioTramite) as Año,
	COUNT(1) as Cantidad from dbo.tTramites
	


	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	
WHERE 
	ttramites.idCentroEmisionLicencia 
	IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))
    AND tTramites.txEstado = 'EMITIDO'

GROUP BY
	 DATEPART(YEAR, tTramites.fcFechaInicioTramite),
	 DATEPART(Month, tTramites.fcFechaInicioTramite)
ORDER BY
	 DATEPART(YEAR, tTramites.fcFechaInicioTramite),
	 DATEPART(Month, tTramites.fcFechaInicioTramite)



/* tramites en estado EMITIDO en SALTA */

declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='SALTA';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	tTramites.fcFechaInicioTramite as FechaInicio,
	COUNT(1) as Cantidad from dbo.tTramites
	


	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	
WHERE 
	ttramites.idCentroEmisionLicencia 
	IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))
    AND tTramites.txEstado = 'EMITIDO'

GROUP BY
	tTramites.fcFechaInicioTramite
