### ISSUE TITLE
solicito reporte detallado de licencias no impresas(GLPI 7168)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#274]
Estimados solicito un reporte detallado (nombres apellido numero de tramite dni fecha de nac,etc) de licencias NO IMPRESAS de los siguientes municipios:

Bariloche (rio negro)
El bolson (rio negro)
El hoyo (chubut)
El maiten (chubut)
Cholila (chubut)

**Comment by EliasWasinger** [comment]
Listo, dejo el excel y la query usada por CEL:

[Reporte licencias por CEL.xlsx](https://github.com/leoimoli/Base-De-Datos/files/855114/Reporte.licencias.por.CEL.xlsx)

`SELECT        
	tCentrosEmisionLicencias.txNombre as CEL,
	tLicencias.idLicencia,
	tLicencias.fcFechaEmision as fechaEmision,
	tLicencias.fcFechaNacimientoLicencia as fechaNacimiento,
	tLicencias.fcFechaVencimiento as fechaVencimiento,
	tLicencias.idInsumo as idInsumo,
	tLicencias.idTramite,
	tLicencias.txAltura as altura,
	tLicencias.txApellidoLicencia as apellido,
	tLicencias.txBarrio as barrio,
	tLicencias.txCalle as calle,
	tLicencias.txClasesLicencia as ClaseLicencia,
	tLicencias.txCodigoPostal as codigoPostal,
	tLicencias.txDepartamento as Departamento,
	tLicencias.txEstado as Estado,
	tLicencias.txFactorSanguineo as FactorSanguineo,
	tLicencias.txLocalidad as localidad,
	tLicencias.txNacionalidad as Nacionalidad,
	tLicencias.txNombreLicencia as nombre,
	tLicencias.txNroLicencia as NroLicenciaDNI,
	tLicencias.txObservaciones as Observaciones,
	tLicencias.txPiso as Piso,
	tLicencias.txSexoLicencia as sexo,
	tLicencias.txTipoDocumento as TipoDocumento,
	tLicencias.txTipoSanguineo as TipoSanguineo
	

FROM
	tLicencias 
	INNER JOIN tTramites ON tLicencias.idTramite = tTramites.idTramite
	INNER JOIN tCentrosEmisionLicencias ON tTramites.idCentroEmisionLicencia = tCentrosEmisionLicencias.idCentroEmisionLicencia
	
	
WHERE
	tCentrosEmisionLicencias.txNombre = 'CHOLILA' AND
	(tLicencias.txEstado = 'NO_IMPRESA') /*AND
	tLicencias.fcFechaEmision BETWEEN convert(datetime, '01/08/2016', 103) AND convert(datetime, '30/09/2016', 103)*/

GROUP BY
	tLicencias.idLicencia,
	tLicencias.fcFechaEmision,
	tLicencias.fcFechaNacimientoLicencia,
	tLicencias.fcFechaVencimiento,
	tLicencias.idInsumo,
	tLicencias.idTramite,
	tLicencias.txAltura,
	tLicencias.txApellidoLicencia,
	tLicencias.txBarrio,
	tLicencias.txCalle,
	tLicencias.txClasesLicencia,
	tLicencias.txCodigoPostal,
	tLicencias.txDepartamento,
	tLicencias.txEstado,
	tLicencias.txFactorSanguineo,
	tLicencias.txLocalidad,
	tLicencias.txNacionalidad,
	tLicencias.txNombreLicencia,
	tLicencias.txNroLicencia,
	tLicencias.txObservaciones,
	tLicencias.txPiso,
	tLicencias.txSexoLicencia,
	tLicencias.txTipoDocumento,
	tLicencias.txTipoSanguineo,
	tCentrosEmisionLicencias.txNombre`
