### ISSUE TITLE
GLPI 7385

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#278]
Solicito cambio de estado de anulado a aprobado
dni 33927657 masculino Fick Miguel Enrique
Tramite N° 15435821

**Comment by EliasWasinger** [comment]
Listo, se pasó el trámite a estado aprobado, dejo la query:

`select * from tLicencias where txNroLicencia = '33927657' /* tra 15435821 */

select * from tTramites where idTramite = '15435821'

update tTramites set txEstado = 'APROBADO' where idTramite = '15435821'`
