### ISSUE TITLE
solicito modificar la clase de licencia de una licencia nacional(GLPI 7345)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#279]
Estimados la siguiente persona:

22709325	19/09/2012	1566430	VIGENTE	ORIGINAL	19/09/2012	17/09/2017	B	JOSE CLEMENTE PAZ	RANCES	LUCAS ALBERTO	 

posee la licencia nacional, por sistema figura clase B, únicamente y debería figurar como B.1, necesito se corrija ese campo. gracias

**Comment by EliasWasinger** [comment]
Listo, se agregó a la tabla ClaseLicenciaPorTramite el idtramite y el idclase
Dejo la query:

`insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (9,1566430)`
