### ISSUE TITLE
ERROR EN BACKEN(GLPI 7353)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#280]
Recientemente solicitamos importar actas en lotes al SINAI, si bien la respuesta fue satisfactoria....observo que el numero de actas que quedan es alto. Revisando...vemos que no hay comunicacion con el servidor del reg.nac. prop. aut. con las actas que siguen quedando. Es el caso del acta 062100916001278 (gestionada al dominio DYT366), si observamos por backend nos dice no existen datos para el dominio y si chequeamos el dominio por SINAI nos arroja el resultado del titular. Tambien estan quedando actas que tienen cargado los datos del conductor....por ende podrian ser enviadas. Aguardo comentarios. Gracias.

**Comment by leodimonio** [comment]
ya se soluciono el inconveniente con la consulta al dnrpa, se intentaran enviar automaticamente todas las actas de manera automatica, saludos
