### ISSUE TITLE
ALTA EN SIM - MUNICIP. NEUQUEN CAPITAL(GLPI 7352)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#281]
Se requiere el alta del Municipio de Neuquén Capital en PROD SIM.

- Autoridad de Juzgamiento: "Tribunal Municipal de Faltas" con ID SAFIT 1535
- Dirección física: Mitre N° 461
- Teléfono: 0299-4491200 INTERNO 4610/4611
- Horario de atención: 08:00 a 13:00hs
- Correo electrónico:
- Valor combustible: $ 14
- Nombre de la Autoridad de Constatación: Municipalidad de Neuquén
- Partido al que se asocia la Autoridad de Constatación: Confluencia
- Provincia al que se asocia la Autoridad de Constatación: Neuquén
- Archivo del Logo J06A011.pcx
- Id 06 para Neuquén
- Código: 011
- Adhesión a la ordenanza ORDENANZA 12028

ACLARACIÓN: LA JURISDICCIÓN UTILIZA EL 20% DE DESCUENTO Y SALVO PARA ALGUNOS CASOS QUE DIRECTAMENTE NO LE OTORGA DESCUENTO, Ya esta cargado en la normativa de SINAI.

**Comment by leodimonio** [comment]
listo se agrego el juzgado la ordenanza y su correspondiente adhesion, saludos
