### ISSUE TITLE
Alta de juzgado Bell Ville/ Cordoba en sistema SIM-Urgente(GLPI 7383)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#282]
Se requiere el alta del Municipio de Bell Ville en PROD SIM.

- Autoridad de Juzgamiento: "Juzgado de Faltas" con ID SAFIT 1537
- Dirección física: Sarmiento 14 - Planta Alta
- Teléfono: 03537-415995
- Horario de atención: 06:00 a 12:30hs
- Correo electrónico: juzgadofaltasbv@hotmail.com
- Valor combustible: $ 19,09
- Nombre de la Autoridad de Constatación: Municipalidad de Bell Ville
- Partido al que se asocia la Autoridad de Constatación: Unión
- Provincia al que se asocia la Autoridad de Constatación: Córdoba
- Archivo del Logo J11A015.pcx
- Id 11 para Córdoba
- Código: 015
- Adhesión a la ordenanza 1889/2014 y decreto nacional 437/

**Comment by leodimonio** [comment]
se agrego el juzgado , la ordenanza municipal y su correspondiente adhesion, el decreto 437 ya estaba adherido a dicho partido, saludos
