### ISSUE TITLE
ERROR SINALIC(GLPI 7429)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#283]
La licencia le figura vigente cuando debería estar NO VIGENTE

7003104 masc

**Comment by leodimonio** [comment]
La persona tiene una licencia vigente donde las fechas de emision y vencimiento son correctas.
Fecha Emision: 2017-03-28 11:27:12.000
Fecha Vencimiento: 2018-03-28 00:00:00.000
