### ISSUE TITLE
Modificar fecha de emision(GLPI 7489)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#286]
DNI: 6015320
Fecha de emision erronea: 29/03/2017
Fecha de emision que corresponde: 0302/2016

6015320 03/02/2016 11706432 VIGENTE RENOVACIÓN 29/03/2017 03/02/2017 A ARROYO SECO FALVELLA DONATO ALBERTO 004267045

**Comment by leodimonio** [comment]
Se realizo el cambio solicitado.
