### ISSUE TITLE
Alta de juzgado AlDERETES / TUCUMAN en sistema SIM-Urgente(GLPI 7544)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#288]
Adjunto datos de dicho municipio para su alta.
Se requiere el alta del Municipio de Alderetes en PROD SIM.

- Autoridad de Juzgamiento: "Tribunal de Faltas Municipal" con ID SAFIT 1539
- Dirección física: Av. Rivadavia N° 924, local 6.
- Teléfono: -
- Horario de atención: 08:30 a 12:30hs
- Correo electrónico:-
- Valor combustible: $ 19
- Nombre de la Autoridad de Constatación: Municipalidad de Alderetes
- Partido al que se asocia la Autoridad de Constatación: Alderetes- Cruz Alta
- Provincia al que se asocia la Autoridad de Constatación: Tucuman
- Archivo del Logo J17A007.pcx
- Id 17 para Tucumán
- Código: 007
- Adhesión a la ordenanza 437/11

**Comment by leodimonio** [comment]
Listo, ya se cargo el juzgado, autoridad de constatacion, y se le adherio la ordenanza 437/11, saludos.
