### ISSUE TITLE
Sistema Alta Sim/ J. V. Gonzalez /  Salta -PRIORIDAD ALTA(GLPI 7543)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#289]
Adjuntos datos de dicho municipio para su alta.

Se requiere el alta del Municipio de Joaquin V. Gonzalez en PROD SIM.
- Autoridad de Juzgamiento: "Dirección de tránsito" con ID SAFIT 1538
- Dirección física: Av. Güemes N° 101.
- Teléfono: -
- Horario de atención: 09:00 a 14:00hs
- Correo electrónico:-
- Valor combustible: $ 20.50
- Nombre de la Autoridad de Constatación: Municipalidad de Joaquín V. Gonzalez
- Partido al que se asocia la Autoridad de Constatación: Anta
- Provincia al que se asocia la Autoridad de Constatación: Salta
- Archivo del Logo J20A010.pcx
- Id 20 para Salta
- Código: 010
- Adhesión a la ordenanza 437/11

**Comment by leodimonio** [comment]
Listo, ya se agrego el juzgado, autoridad de constatacion, y su correspondiente adhesion al decreto 437, saludos.
