### ISSUE TITLE
SINALIC -- Modificar Pais Emisor(GLPI 2164)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#29]
BONMASSAR GONZALEZ DNI.Nº 92.799.197, Se solicita la modificación del país emisor del DNI. (CORRESPONDE ARGENTINA)

**Comment by EliasWasinger** [comment]
Se realizo el cambio:

`select * from tLicencias where   txNroLicencia = '92799197'

begin transaction
	update tLicencias set txNacionalidad = 'ARGENTINA' where idLicencia = '8231453'
	commit`
