### ISSUE TITLE
Anulación de licencia(GLPI 7484)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#290]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	40965488 JUAREZ, BRAIAN GERARDO - MASCULINO, N° insumo: 7323200
Fecha de Emisión de la licencia: 29/03/2017

**Comment by leodimonio** [comment]
La licencia indicada ya se encontraba ANULADA.
