### ISSUE TITLE
Cambio de estado(GLPI 7550)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#291]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	DNI: 30012081 CORREA, JAVIER EDUARDO, TRAMITE 16073517 , SEXO MASCULINO INSUMO 007290642

MOTIVO DE LA ANULACIÓN:	ERROR EN ESTADO, DESDE ESTE CENTRO EN NINGUN MOMENTO SE ANULO LA LICENCIA.

**Comment by leodimonio** [comment]
La licencia ya se encuentra anulada.
