### ISSUE TITLE
Anulación de licencia(GLPI 7557)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#293]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	34709384 ROLDAN, GASTON EXEQUIEL - MASCULINO, N° insumo: 7323112
Fecha de Emisión de la licencia: 30/03/2017

MOTIVO DE LA ANULACIÓN:	ERROR DE CLASE, ANULAR LICENCIA

**Comment by leodimonio** [comment]
La licencia indicada ya se encuentra aulada.
