### ISSUE TITLE
Error de Estado Anulación de Licencia ANSV(GLPI 7615)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#294]
Usuario solicitante del CEL:	 
COPAS MONICA ALEJANDRA

Teléfono de contacto:	 
388-5815699

SE SOLICITA LA ANULACION DE LA LICENCIA DE:	DNI: 30012081 CORREA, JAVIER EDUARDO, TRAMITE 16073517 , SEXO MASCULINO INSUMO 007290642

MOTIVO DE LA ANULACIÓN:	ERROR EN ESTADO, DESDE ESTE CENTRO EN NINGÚN MOMENTO SE ANULO LA LICENCIA.

**Comment by leodimonio** [comment]
La licencia indicada ya se encuentra en estado ANULADA.
