### ISSUE TITLE
Cambio valor de combustible SIM - Comandante Luis Piedrabuena (Santa Cruz)(GLPI 7683)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#295]
Cambio valor de combustible SIM - Comandante Luis Piedrabuena (Santa Cruz)
Nos solicitaron del Municipio de Comandante Luis Piedrabuena el cambio de valor de combustible a $17,20. Ya se realizó el cambio en el SINAI, necesitamos que se actualice en el SIM.

Provincia: SANTA CRUZ
Departamento / Partido:CORPEN AIKE
Localidad:COMANDANTE LUIS PIEDRABUENA

**Comment by leodimonio** [comment]
Listo, ya se actualizo el valor de combustible, saludos.
