### ISSUE TITLE
Cambio valor de combustible SIM - San Pedro (Jujuy)(GLPI 7684)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#296]
Nos solicitaron del Municipio de San Pedro el cambio de valor de combustible a $20. Ya se realizó el cambio en el SINAI, necesitamos que se actualice en el SIM.

Provincia: JUJUY
Departamento / Partido: SAN PEDRO
Localidad:SAN PEDRO

**Comment by leodimonio** [comment]
Listo, ya se actualizo el valor de combustible, saludos.
