### ISSUE TITLE
Reporte Licencia Emitida(GLPI 7709)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#298]
Buenos días. por favor proporcionar Licencias Emitidas por CEL y por mes desde Enero 2017 hasta la fecha en curso.
Tiene que contener los siguientes campos: 
Año
Mes 
JURISDICCION 
CEL 
Estado 
Sexo 
TOTAL

Gracias

**Comment by leodimonio** [comment]
[reporte licencias emitidas 2017.xlsx](https://github.com/leoimoli/Base-De-Datos/files/905992/reporte.licencias.emitidas.2017.xlsx)
