### ISSUE TITLE
Cambios en la Normativa de Neuquén Capital ORD 12028(GLPI 7793)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#299]
Se realizaron modificaciones en la Ordenanza 12028 de Neuquén Capital en el SINAI. Las mismas son:

-Se modifico N° de ART del código 35 estaba como art 373 y era 273.
-Se modifico el Art 276 se saco el 43 del campo inciso.
-Se saco el código 46 estaba duplicado.
-Se cambio el N° de ART del código 84
-Se agregaron los códigos 222,223 y 224.
-Se corrigió el código del ART 318. Estaba mal denominado el correcto es el 108.

Solicitamos se corrija en el SIM.

**Comment by leodimonio** [comment]
Listo, ya se realizo el cambio en los ptos correspondientes y se agrego los codigos que faltaban cargar, saludos.
