### ISSUE TITLE
Pedido IdCel Provincia Neuquen

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#3]
Elias, por favor envíame el IdCel del siguiente Cel de la base datos de producción.

Provincia: Neuquen
Cel:    

- NEUQUEN 
- DELEGACIÓN SANTA TERESA
- DELEGACIÓN ALTO GODOY
- DELEGACIÓN ALTA BARDA
- DELEGACIÓN PROGRESO
- DELEGACIÓN ETON TERMINAL DE ÓMNIBUS DE NEUQUEN

**Comment by EliasWasinger** [comment]
Buenas, los idCEL:
NEUQUEN: No figura
DELEGACIÓN SANTA TERESA: 46
DELEGACIÓN ALTO GODOY: 501
DELEGACIÓN ALTA BARDA: 152
DELEGACIÓN PROGRESO: 153
DELEGACIÓN ETON TERMINAL DE ÓMNIBUS DE NEUQUEN: 154 (Figura como DELEGACIÓN ETON)

**Comment by leoimoli** [comment]
Se informo la resolución.
