### ISSUE TITLE
Cambio valor de combustible SIM - Corral de Bustos(GLPI 7781)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#301]
Nos solicitaron del Municipio de Corral de Bustos el cambio de valor de combustible a $19,09. Ya se realizó el cambio en el SINAI, necesitamos que se actualice en el SIM.

Provincia: CORDOBA
Departamento / Partido:MARCOS JUAREZ
Localidad: CORRAL DE BUSTOS

**Comment by leodimonio** [comment]
Listo, ya se realizo el cambio del valor combustible, saludos.
