### ISSUE TITLE
MODIFICACIÓN DNI EN EL SISTEMA(GLPI 7827)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#304]
Se solicita que se modifique el DNI de la inhabilitacion registrado con el N° 26.204.049 a nombre del señor QUILPATAY GUSTAVO ANDRES, por el correcto que es el DNI N° 26.204.089

**Comment by leodimonio** [comment]
listo, ya se realizo el cambio, saludos.
