### ISSUE TITLE
Alta del Municipio de SAN ANTONIO DE ARREDONDO en PROD SIM - PDA(GLPI 7865)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#308]
Se requiere el alta del Municipio de SAN ANTONIO DE ARREDONDO en PROD SIM.

- Autoridad de Juzgamiento: "TRIBUNAL ADMINISTRATIVO MUNICIPAL DE FALTAS" con ID SAFIT 1551
- Dirección física: Av. Cura Brochero N° 2305
- Teléfono:
- Horario de atención: 07:00 a 14:00hs
- Correo electrónico: faltassanantonio@hotmail.com
- Valor combustible: $ 18,44
- Nombre de la Autoridad de Constatación: Municipalidad de San Antonio de Arredondo
- Partido al que se asocia la Autoridad de Constatación: Punilla
- Provincia al que se asocia la Autoridad de Constatación: Córdoba
- Archivo del Logo J11A016.pcx
- Id 11 para Córdoba
- Código: 016
- Adhesión a la ordenanza DECRETO 437/11

Sin mas que decir. Saludo Atte.

**Comment by leodimonio** [comment]
Listo, ya se agrego el juzgado , y su correspondiente adhesion al DECRETO 437/11, saludos.
