### ISSUE TITLE
Asignar insumo a Licencia(GLPI 7888)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#309]
Estimados necesito que asignen el insumo 007799133 al tramite del señor:

16123662	EMITIDO	31/03/2017 03:14:00 P.M.	33456246	JUAN CLAUDIO	AGUIRRE	DUPLICADO POR CAMBIO DE DATOS	B.1

el mismo se encuentra en estado NO IMPRESO, y el sistema no me permite por un error interno ASIGNAR la numeracion mencionada, saludos.-

**Comment by EliasWasinger** [comment]
Listo, se asignó el insumo y se le cambió el estado al mismo, dejo la query:

`select * from tLicencias where txNroLicencia = '33456246' /* id 14972923 */

select * from tInsumos where txNumeroInsumo = '007799133' /* id insumo 8331889 */

update tLicencias set idInsumo = '8331889' where idLicencia = '14972923'

update tInsumos set txEstado = 'ASIGNADO' where idInsumo = '8331889'`
