### ISSUE TITLE
SINALIC -- Activar tramite anulado(GLPI 2148)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#31]
Por error se solicitó la anulacion del trámite 13746923, solicitamos REACTIVARLO al estado APROBADO.
DNI 37056130 - Masculino

**Comment by EliasWasinger** [comment]
Ya se realizo

`begin transaction
	update tTramites set txEstado = 'APROBADO' where idTramite = '13746923'
commit`
