### ISSUE TITLE
Eliminar Licencias(GLPI 7889)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#310]
Se solicita la ELIMINACION de las siguientes licencias y tramites, ya que fueron realizadas por la provincia de córdoba el dia 03/03/2017 para las pruebas de la nueva LNC.

Nº de Trámite: 15932087
DNI: 32925062 

Nº de Trámite: 15932088
DNI: 31053482 

Nº de Trámite: 15024775
DNI: 7955639 (pasar a tramite generado)

**Comment by EliasWasinger** [comment]
Listo, se eliminaron licencias y trámites de los dos primeros items, el tercero se cambió de estado.

Eliminar primer item:

`select * from tLicencias where txNroLicencia = '32925062' and idTramite = '15932087' /* id 14808428 */

delete from tLicencias where idLicencia = '14808428';

delete from tClasesLicenciasPorTramite where idTramite = '15932087';
delete from tWorksFlowTramite where idTramite = '15932087';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '15932087');
delete from tExamenesPsicoFisico where idTramite = '15932087'
delete from tResultadosExamenTPCurso where idTramite = '15932087';

delete from tTramites where idTramite = '15932087';`

Eliminar segundo item:
`select * from tLicencias where txNroLicencia = '31053482' and idTramite = '15932088' /* id 14808429 */

delete from tLicencias where idLicencia = '14808429';

delete from tClasesLicenciasPorTramite where idTramite = '15932088';
delete from tWorksFlowTramite where idTramite = '15932088';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '15932088');
delete from tExamenesPsicoFisico where idTramite = '15932088'
delete from tResultadosExamenTPCurso where idTramite = '15932088';

delete from tTramites where idTramite = '15932088';`

Cambio de estado de tercer item:

`select * from tLicencias where txNroLicencia = '7955639 ' and idTramite = '15024775' /* id 14808427 */

update tLicencias set txEstado = 'ANULADA' where idLicencia = '14808427'

update tTramites set txEstado = 'GENERADO' where idTramite = '15024775'`
