### ISSUE TITLE
Ordenanza 023/1993 Municipal de Las Talitas (Tucumán)(GLPI 7990)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#312]
Se agrego el Código 13	en la ORDENANZA 023/1993 de LAS TALITAS que corresponde al Artículo 90 LA FALTA O DEFICIENCIA DE FRENOS.
Se realizó la modificación en el SINAI requerimos que se agregue dicho artículo en el SIM.

**Comment by leodimonio** [comment]
Listo, ya se agrego al sim , saludos.
