### ISSUE TITLE
Cambiar licencia estado no vigente a vigente(GLPI 8023)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#313]
Cel Roca - Caba
Cambiar estado de licencia
DNI 22589310
Masculino
Martin Schapochnik
Tel 46041333

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia, tenía dos, se tomó la emitida en 2016, las dos estaban en no vigente.

`select * from tLicencias where txNroLicencia = '22589310'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '11360182'`
