### ISSUE TITLE
cargar la clase B.1(GLPI 7995)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#315]
Se solicita desde San Juan cargar la licencia B.1 que no se ve en SINALIC 
La licencia de Oldani, Silvia DNI 16900307, dado que la su ultima licencia vigente emitida en CEL SAN JUSTO no tiene subclases asignadas.

**Comment by EliasWasinger** [comment]
Listo, se le agregó la clase B1 al trámite.
Dejo la query:
`select * from tLicencias where txNroLicencia='16900307' /* 809904*/ /* tra 875737 */

select * from tClasesLicenciasPorTramite where idTramite = '875737'

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (9,875737)`
