### ISSUE TITLE
Cambiar licencia estado no vigente a vigente(GLPI 8018)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#316]
CEL Godoy Cruz
Cambiar licencia de estado no vigente a vigente 

DNI 8.115.173
MASCULINO
Bistuer Vicente Mario
Nº Insumo 007121641

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia.

`select * from tLicencias where txNroLicencia = '8115173'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14786661'`
