### ISSUE TITLE
Cambio valor de combustible SIM (Puerto San Julián) Santa Cruz(GLPI 8053)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#317]
Nos solicitaron desde el Municipio de Puerto San Julián, el cambio del valor de combustible a $17,26. Ya se modificó el valor en el SINAI necesitamos que se modifique el en el SIM.

Provincia: Santa Cruz
Partido Departamento: Magallanes
Localidad: Puerto San Julián

**Comment by leodimonio** [comment]
Listo, ya se cambio el valor combustible, saludos.
