### ISSUE TITLE
Agregar Adhesión DECRETO 779/95 Las Talitas (Tucumán) al SIM(GLPI 8063)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#318]
Se solicita se agregue el decreto 779/95 al Municipio de Las Talitas en el SIM. El municipio además de su Ordenanza propia utiliza el decreto 779/95 para el labrado de sus infracciones.
La adhesión ya fue agregada en el SINAI.

**Comment by leodimonio** [comment]
Listo, ya fue agregada la adhesion, saludos.
