### ISSUE TITLE
Solicitud  SIM ORDENANZA BELL VILLE- AGREGARLE A TODOS LOS ARTÍCULOS DE LA ORDENANZA 1992/2016 50% DE DECUENTO(GLPI 8067)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#320]
Estimados solicito agregar en todos los articulo de la ordenanza 1992/16 el 50 % de descuento en el sistema SIM. Dicha modificación corresponde al municipio Bell Vill/ Córdoba.

**Comment by leodimonio** [comment]
Se actualizo todos los articulos al 50 %, igual cabe aclarar que el porcentaje que tenian de descuento eran los que se configuraron en el Sinai, en el momento de dar de alta la ordenanza, saludos.
