### ISSUE TITLE
SOLICITUD CAMBIO TIPO DE INHABILITACION(GLPI 8022)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#321]
Solicito que se modifique en el siguiente DNI 27.781.960 en donde dice tipo de inhabilitacion "INHABILITACION" debe decir ANTECEDENTE.

**Comment by leodimonio** [comment]
Buenas, esta persona tiene cargada en el sistema dos antecedentes, uno del tipo ANTECEDENTE y el otro del Tipo INHABILITACION, el cual el tipo inhabilitacion es definitiva penal, les pido que nos digan que debe quedar o como es el tema, saludos
