### ISSUE TITLE
Solicitud cambio de DNI(GLPI 8028)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#322]
Se solicita que se modifique el DNI de la inhabilitacion registrado con el N° 23.380.118 a nombre del señor LOPEZ Alfredo Guillermo, por el correcto que es el DNI N° 23.380.116

**Comment by leodimonio** [comment]
Buenas, en la base de datos figuran dos DNI distintos con estos mismo datos, con el dni 23380116
el nombre esta como GUILLERMO Y apellido LOPEZ, y el dni 23380118 nombre ALFREDO GUILLERMO apellido LOPEZ, ambos documentos tienen antecedentes, esperamos su respuesta de que hacer, saludos.

**Comment by leoimoli** [comment]
Que se agregue al DNI 23.380.116

**Comment by leodimonio** [comment]
Listo, se asigno el antecedente y su correspondiente historial a la persona que estaba bien cargada. Saludos
