### ISSUE TITLE
No se puede anular licencia VIGENTE(GLPI 8038)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#324]
Nos contactan del CEL Libertador General San Martin, mas precisamente del Departamento de Ledesma - Jujuy para que anulemos una licencia VIGENTE del contribuyente QUINTEROS HELEN GISELLE, DNI 34312411 por error en el apellido.

**Comment by EliasWasinger** [comment]
Listo, se anuló la licencia, trámite e insumo del usuario.
Query:

`select * from tLicencias where txNroLicencia  = '34312411' /* idlic 15118614 // idtra 16295881 // idinsu 7482450 */

update tLicencias set txEstado = 'ANULADA' where idLicencia = '15118614'

select * from tTramites where idTramite = '16295881'

update tTramites set txEstado = 'ANULADO' where idTramite = '16295881'

select * from tInsumos where idInsumo = '7482450'

update tInsumos set txEstado = 'ANULADO' where idInsumo = '7482450'`
