### ISSUE TITLE
Modificar fecha de emision(GLPI 8225)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#325]
modificar la fecha de emisión de la siguiente licencia.

DNI: 25700842
Fecha actual: 26/04/2017
Fecha de emision correcta: 12/04/2016

**Comment by EliasWasinger** [comment]
Listo, se cambió la fecha de emisión.
Query:
`select * from tLicencias where txNroLicencia = '25700842'

update tLicencias set fcFechaEmision = '2016-04-12 10:09:02.000' where idLicencia = '15173325'`
