### ISSUE TITLE
anulación licencia(GLPI 8241)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#326]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	
mencionar DNI, Apellido y nombre, sexo, fecha de emisión de la licencia, nro. de insumo

DNI 36.871.600
NUÑEZ FREDY ALEXIS
MASCULINO
EMITIDO 21/09/2016

Insumo006327778

**Comment by EliasWasinger** [comment]
La licencia ya se encontraba anulada.
