### ISSUE TITLE
anulación licencia(GLPI 8241)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#327]
SE SOLICITA LA ANULACION DE LA LICENCIA DE:	

DNI 36.871.600
NUÑEZ FREDY ALEXIS
MASCULINO
EMITIDO 21/09/2016

Insumo006327778

MOTIVO DE LA ANULACIÓN:	
detallar el motivo por el cual se pide la anulación.

**Comment by EliasWasinger** [comment]
La licencia ya se encuentra anulada.
