### ISSUE TITLE
Asignar Usuario de Entidad a Funcionario(GLPI 8325)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#328]
Se solicita que el Usuario DNI 17238997 se asocie al funcionario que se cargo para Neuquén Capital.
Este usuario está cargado como usuario de entidad y debería pasar luego de asociarlo al funcionario a un Usuario de Funcionario.

**Comment by leodimonio** [comment]
Listo ya se asigno el usuario de entidad a funcionario, saludos.
