### ISSUE TITLE
Anular Licencia No Vigente(GLPI 8323)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#329]
Estimados, se solicita, de ser posible se anule la licencia NO VIGENTE de Duarte Alfredo Daniel DNI 28573312 que por error del municipio de Florencio Varela se emitió a ese ciudadano cuando por el número de DNI no corresponde a él.

Gracias, saludos

**Comment by EliasWasinger** [comment]
Listo, se anuló la licencia.
Query:
`select * from tLicencias where txNroLicencia = '28573312' /* 1244346 */

update tLicencias set txEstado = 'ANULADA' where idLicencia = '1244346'`
