### ISSUE TITLE
Error Producción SINAI V.1.13.8 (Acta Duplicada)(GLPI 8284)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#330]
Desde el Municipio de Corrientes Capital nos informaron que existe el acta n° 06-19-006-16-005214 duplicada en el SINAI. Esto hace que no se pueda ingresar al detalle de la misma, una vez que se consulta y se quiere ingresar por la lupa sale el siguiente cartel de error "query did not return a unique result: 2".

**Comment by leodimonio** [comment]
Listo, ya se elimino la duplicada, saludos.
