### ISSUE TITLE
Cambiar fecha de vigencia de licencia(GLPI 8511)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#332]
Desde Gerencia Operativa Habilitaciones de CABA nos solicitan que se modifique la fecha de vigencia de una licencia ya vencida ya que se registró mal en SiNaLic. Se detalla mail recibido:

Estimados.

Podríamos cambiar la licencia adjunta en el sistema? ya que la misma se había impreso mal con otra fecha de vencimiento y ésta es la que debe estar cargada.

Angel René Dominguez 
DNI 27066681
E1,A22,D22	18/03/2016	30/04/2017	Renovacion con Ampliacion

Gracias!!

**Comment by EliasWasinger** [comment]
Listo, se cambió la fecha de emisión de la licencia correspondiente a la clase renovación con ampliación.
Query:

`select * from tLicencias where txNroLicencia = '27066681'

select * from tTramites where idTramite = '12204562'

select * from tCategoriasLicencia where idCategoriaLicencia = '8'


update tLicencias set fcFechaEmision = '2017-04-30 10:09:02.000' where idLicencia = '11451799'`

**Comment by EliasWasinger** [comment]
Era fecha de vencimiento y no de emisión:
`select * from tLicencias where txNroLicencia = '27066681'

update tLicencias set fcFechaVencimiento = '2017-04-30 00:00:00.000' where idLicencia = '11451799'`
