### ISSUE TITLE
Volver a estado aprobado(GLPI 8461)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#334]
SE SOLICITA VOLVER EL TRAMITE A ESTADO APROBADO PARA CPC N 6

El DNI:  29136702
Nro:Tramite: 16360675

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite.

Query:
`select * from tLicencias where txNroLicencia = '29136702'
select * from tTramites where idTramite = '16360675'
update tTramites set txEstado = 'APROBADO' where idTramite = '16360675'`
