### ISSUE TITLE
Cambio de estado(GLPI 8581)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#335]
Pasar el tramite a estado emitido y la licencia a estado no vigente.

Nro. licencia 16748733 
Fecha inicio trámite 25/02/2013
trámite 2418728
Estado ANULADA
Fecha fin vigencia 25/02/2017
Apellido Nombre MADIA ARIEL OMAR
Insumo 001246030

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite y licencia.
Query:
`select * from tLicencias where txNroLicencia = '16748733'
select * from tTramites where idTramite = '2418728'

update tTramites set txEstado = 'EMITIDO' where idTramite = '2418728'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '2254434'`
