### ISSUE TITLE
ALTA SIM PROD - PUEBLO GRAL. BELGRANO(GLPI 8438)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#336]
Se requiere el alta del Municipio de Pueblo Gral. Belgrano en PROD SIM.
- Autoridad de Juzgamiento: "JUZGADO DE FALTAS MUNICIPAL" con ID SAFIT 1557
- Dirección física: 30 de Noviembre N°194
- Teléfono:
- Horario de atención: 07:00 a 13:00hs
- Correo electrónico: juzgadodefaltaspgb@gmail.com
- Valor combustible: $ 19,99
- Nombre de la Autoridad de Constatación: Municipalidad de Pueblo Gral. Belgrano.
- Partido al que se asocia la Autoridad de Constatación: Gualeguaychu.
- Provincia al que se asocia la Autoridad de Constatación: Entre Ríos.
- Archivo del Logo J13A011.pcx
- Id 13 para Entre Ríos.
- Código: 011.
- Normativa 437/11.

**Comment by leodimonio** [comment]
listo ya se agrego el juzgado y se adhiriio a su ordenanza correspondiente, saludos.
