### ISSUE TITLE
cambio de esatdo(GLPI 8873)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#341]
Solicitan desde el CEL modificar la licencuia en estadi VIGENTE a NO VIGENTE
DNI 22125304 masc ( copio imagen SINALIC)

**Comment by EliasWasinger** [comment]
Listo
`select * from tLicencias where txNroLicencia = '22125304'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '846697'`
