### ISSUE TITLE
Se necesita anular licencias no vigentes(GLPI 8892)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#342]
Se presentó en este CEL una persona que tiene una licencia de Gral. Pueyrredón (Bs. As.), que vence en el año 2021, esta persona ya se radicó en Santiago del Estero y quiere hacer el duplicado de su Licencia de Conducir, pero en la misma quiere realizar una ampliación a la Clase D.1, pero cuando voy a confirmar el trámite me da un error.

La persona tiene 4 licencias emitidas el mismo día (una vigente, 3 no vigentes), se solicita que se anulen para poder realizar el trámite.

Datos de la persona:      Apellido y Nombres: PAZ, ARMANDITO RUDY DE DIOS
                                        DNI Nº: 28.503.097

**Comment by EliasWasinger** [comment]
Listo, se anularon las licencias.
Query:
`select * from tLicencias where txNroLicencia = '28503097'

update tLicencias set txEstado = 'ANULADA' where idLicencia = '13923960'
update tLicencias set txEstado = 'ANULADA' where idLicencia = '13924040'
update tLicencias set txEstado = 'ANULADA' where idLicencia = '13924110'`
