### ISSUE TITLE
Cambio de tramite anulado a aprobado(GLPI 8959)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#343]
Entre Rios - Hernandarias
Tramites:

-DNI 28591604, FIANUCHI STELLA MARIS, FEMENINO, NRO. DE INSUMO 007474539, FECHA DE EMISIÓN DE LA LICENCIA 07/03/2017.

- DNI 31269462, LUQUESI VILMA JESICA, FEMENINO, NRO. DE INSUMO 007474534, FECHA DE EMISIÓN DE LA LICENCIA 08/03/2017.

- DNI 31706558, GRANDOLI WALTER IVAN, MASCULINO, NRO. DE INSUMO 007474533, FECHA DE EMISIÓN DE LA LICENCIA 08/03/2017.

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los estados de los trámites.
Query:
`select * from tLicencias where txNroLicencia = '28591604'

select * from tTramites where idTramite = '15945071'

update tTramites set txEstado = 'APROBADO' where idTramite = '15945071'




select * from tLicencias where txNroLicencia = '31269462'

select * from tTramites where idTramite = '15952935'

update tTramites set txEstado = 'APROBADO' where idTramite = '15952935'



select * from tLicencias where txNroLicencia = '31706558'

select * from tTramites where idTramite = '15946680'

update tTramites set txEstado = 'APROBADO' where idTramite = '15946680'`
