### ISSUE TITLE
Alta Sim jUZGADO eSQUEL-CHUBUT(GLPI 9116)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#348]
Estimados:

Se requiere el alta del Municipio de Esquel en PROD SIM.

- Autoridad de Juzgamiento: "JUZGADO MUNICIPAL DE FALTAS" con ID SAFIT 602
- Dirección física: Av Alvear N° 819
- Teléfono: 02945- 454694
- Horario de atención: 07:00 a 12:00hs
- Correo electrónico: secretariatribunal@esquel.gov.ar
- Valor combustible: $ 30
- Nombre de la Autoridad de Constatación: Municipalidad de Esquel
- Partido al que se asocia la Autoridad de Constatación: Futaleufú
- Provincia al que se asocia la Autoridad de Constatación: Chubut
- Archivo del Logo J04A007.pcx
- Id 04 Chubut
- Código: 007
- Adhesión a la ordenanza N° 289/14 ESQUEL

**Comment by leodimonio** [comment]
Listo, ya se realizo el cambio solicitado saludos.
