### ISSUE TITLE
Alta Juzgado de Faltas SIM Termas de Rio Hondo(GLPI 9053)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#349]
Estimados:

Se requiere el alta del Municipio de Termas de Río Hondo en PROD SIM.

- Autoridad de Juzgamiento: "JUZGADO DE FALTAS" con ID SAFIT 1569
- Dirección física: Caseros 373 Barrio Centro
- Teléfono:
- Horario de atención: 07:00 a 13:00hs
- Correo electrónico: juzgadodefaltas@lastermasderiohondo.gob.ar
- Valor combustible: $ 23,28
- Nombre de la Autoridad de Constatación: Municipalidad de Termas de Rio Hondo
- Partido al que se asocia la Autoridad de Constatación: Rio Hondo
- Provincia al que se asocia la Autoridad de Constatación: Santiago del Estero
- Archivo del Logo J18A010.pcx
- Id 18 para Santiago del Estero
- Código: 010
- Adhesión a la ordenanza DECRETO 437/11

**Comment by leodimonio** [comment]
Listo, ya se realizo el cambio solicitado saludos.
