### ISSUE TITLE
ALTA DE LICENCIA ANULADA(GLPI 9205)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#353]
DNI: 11.213.491
SEXO: FEMENINO 
TRAMITE: 16379968

POSEE UNA LICENCIA (DUPLICADO) ANULADA , LA CUAL SE REALIZO ESA ANULACION POR ERROR, SE SOLICITA QUE SE VUELVA A ESTADO VIGENTE.

**Comment by EliasWasinger** [comment]
Listo, se pasó a vigente, dejo la query:
`select * from tLicencias where txNroLicencia = '11213491'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '15198628'`
