### ISSUE TITLE
SOLICITUD MODIFICACION DE DNI EN SINAT(GLPI 9146)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#358]
Solicito se modifique el DNI 28.830.587 donde fue registrada la inhabilitacion a nombre de QUEIPUL JOSE ARCIDES por el correcto DNI que es 18.830.587 en el SINAT.

**Comment by leodimonio** [comment]
Listo, se modifico el antecedente a la persona correspondiente, ya que JOSE ARCIDES cargado como corresponde con DNI 18.830.587, ya poseia antecedentes previos, saludos.
