### ISSUE TITLE
SOLICITUD CAMBIO DE DNI(GLPI 8635)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#359]
SOLICITO MODIFICACIÓN DE LA INHABIILITACION REGISTRADA CON EL DNI 26.188.769 A NOMBRE DE PATRICIA AGUIRRE POR EL CORRECTO DNI QUE ES EL 26.288.769

**Comment by leodimonio** [comment]
Listo ya se actualizo la persona, saludos.
