### ISSUE TITLE
SINALIC -- Activar Licencia(GLPI 2232)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#36]
Por favor ACTIVAR LICENCIA que se encuentra NO VIGENTE, cuando debería estar VIGENTE, ya que su vencimiento es el 23/11/2020
DNI 37307855 FEMENINO - INSUMO A ACTIVAR 004653792

**Comment by EliasWasinger** [comment]
Se realizo:

`BEGIN TRANSACTION

update tLicencias set txEstado='VIGENTE' where idLicencia = '10427501'

update tinsumos set txEstado='ASIGNADO' where idinsumo = '4793547'`
