### ISSUE TITLE
Asignar Usuario de Entidad a Funcionario(GLPI 9019)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#360]
Se solicita que el Usuario DNI 17990800 se asocie al funcionario que se cargo para para el municipio de Yerba Buena, Tucumán.
Este usuario está cargado como usuario de entidad y debería pasar luego de asociarlo al funcionario a un Usuario de Funcionario.

**Comment by leodimonio** [comment]
Listo, ya se realizo el cambio solicitado, saludos.
