### ISSUE TITLE
poner en estado NO VIGENTE(GLPI 9334)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#361]
las 2 licencias nacionales figuran VIGENTES esto genera un error, por favor poner en estado NO VIGENTE.
DNI 26627406 fem

**Comment by EliasWasinger** [comment]
Fecha de vencimiento: 2017-06-22 y la otra 2017-10-03

**Comment by leoimoli** [comment]
necesitamos anular la que tiene vigencia hasta 22/06/2017

**Comment by EliasWasinger** [comment]
Listo, se pasó a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '26627406'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1399152'`
