### ISSUE TITLE
Modificar estado(GLPI 9330)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#362]
Solicito para a estado "NO VIGENTE" la siguiente licencia y a estado "EMITIDO" el tramite

DNI 4815514

**Comment by EliasWasinger** [comment]
Se cambio el estado del trámite y licencia.
Query:
`select * from tLicencias where txNroLicencia = '4815514'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '8804931'

update tTramites set txEstado = 'EMITIDO' where idTramite = '9331083'`
