### ISSUE TITLE
no suma las vigencias en el computo de antiguedad(GLPI 9343)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#363]
deberiamos editar la fecha de emision de la licencia nacional vigente, colocando la fecha 18/05/2016, luego de realizado el tramite aviso por este mismo medio para que la regresen a la fecha correcta (26/07/2016)

**Comment by EliasWasinger** [comment]
DNI 31869860

**Comment by EliasWasinger** [comment]
Listo, se cambio la fecha de emisión de la licencia.
Query:
`select * from tLicencias where txNroLicencia = '31869860'

update tLicencias set fcFechaEmision = '2016-05-18 11:22:15.000' where idLicencia = '12650971'`
