### ISSUE TITLE
cambio de estado(GLPI 9353)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#367]
Se solicita el cambio de estado de 2 licencias qye detallo a continuacion.
 DNI 11959310 masculino padsar a NO GENTE ya que figura ANULADA
DNI 26017313 masculino pasar a VIGENTE ya que figura NO GENTE

**Comment by EliasWasinger** [comment]
"DNI 11959310 masculino padsar a NO GENTE ya que figura ANULADA"
Ambas licencias están en no vigente, no se realizó operación.

"DNI 26017313 masculino pasar a VIGENTE ya que figura NO GENTE"
Tiene dos licencias en estado no vigente, se necesita idtramite para saber cuál pasar.

**Comment by leoimoli** [comment]
El Nro.Tramite 6751133

**Comment by EliasWasinger** [comment]
El trámite corresponde al DNI 26017313, se cambió a vigente
`select * from tLicencias where txNroLicencia = '26017313'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '6418856'`
