### ISSUE TITLE
MODIFICAR PORCENTAJE DESCUENTO PAGO VOLUNTARIO RAWSON - PDA SIM(GLPI 9391)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#368]
Por medio de la presente solicito modificar el porcentaje de descuento en pago voluntario EN SIM del municipio de Rawson (San Juan). Actualmente el descuento es del 50%......cuando el mismo DEBE SER DEL 40%. Solicito gestionar la modificacion correspondiente. Saludos.

**Comment by leodimonio** [comment]
En la Base del Sim todas las infracciones ya aplicaban un descuento del 40% para la adhesion de la localidad de VILLA KRAUSE, que es la que consumen la gente de rawson, san juan.
