### ISSUE TITLE
NO INGRESAN ACTAS GESTIONADAS POR PDA  A SINAI (GLPI 9378)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#369]
Estimados, conforme al periodo que abarca desde 15/05/2017 al 22/05/2017 el backend del SIM arroja que se gestionaron 1222 actas por PDA.....mientras a que SINAI ingresaron solo 27 actas gestionadas por este medio. Solicito ver este tema de forma prioritaria. Saludos

**Comment by leodimonio** [comment]
Ya se encuentra solucionado el inconveniente, saludos.
