### ISSUE TITLE
SINAI --Listado Usuarios SINAI (GLPI 2252)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#37]
Listado de los Usuarios del Sistema SINAI de los Tribunales de Faltas del municipio de San Miguel de Tucuman, que contenga los datos de nombre de usuario, apellido y nombre, tipo de funcionario, autoridad de juzgamiento o juzgado al que pertenece y perfiles habilitados.

**Comment by EliasWasinger** [comment]
Listo, te dejo el reporte y el script:

select u.*, d.* from tEntidades j, tEntidades d, tAutoridadesDeJuzgamiento aj, tAsignacionesFuncionario af, tFuncionarios f, tUsuarios u
 where j.txNombre like '%Tucumán%'
   and j.idEntidad = d.idJurisdiccion
   and d.idEntidad = aj.idEntidad
   and aj.idAutoridadDeJuzgamiento = af.idAutoridadDeJuzgamiento
   and af.idFuncionario = f.idFuncionario
   and f.idFuncionario = u.idFuncionario

[Listado Usuarios SINAI TUCUMAN.xlsx](https://github.com/leoimoli/Base-De-Datos/files/420353/Listado.Usuarios.SINAI.TUCUMAN.xlsx)

**Comment by EliasWasinger** [comment]
Se re hizo porque no era lo que pedía (en realidad sí, pero los títulos tenían otros nombres y mostraba datos de más)

[Listado Usuarios Tucuman.xlsx](https://github.com/leoimoli/Base-De-Datos/files/420677/Listado.Usuarios.Tucuman.xlsx)
