### ISSUE TITLE
pasar a estado aprobado(GLPI 9416)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#370]
pasar a estado aprobado un tramite que se encuentra en estado ANULADO DNI 41847420

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite.
Query:
`select * from tLicencias where txNroLicencia = '41847420'

update tTramites set txEstado = 'APROBADO' where idTramite = '16625600'`
