### ISSUE TITLE
pasar a vigente(GLPI 9442)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#372]
Se solicita pasar la licencia NO GENTE a estado VIGENTE.
DNI 28729542 masc

EMISION 29/05/2015	VIGENCIA 29/05/2017

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia.
Query:
`select * from tLicencias where txNroLicencia = '28729542'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '8960692'`
