### ISSUE TITLE
licencia doble(GLPI 9664)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#378]
Pasar la siguiente licecnia a estado "NOVIGENTE"

Licencia N° 14023462  
fecha de emision 08/09/2014 
tramite N° 7426481

**Comment by EliasWasinger** [comment]
Listo, se pasó a no vigente.
`select * from tLicencias where txNroLicencia = '14023462'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '7051353'`
