### ISSUE TITLE
ALTA -  Viedma(GLPI 9571)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#379]
Se solicita el Municipio de Viedma (Rio Negro) en el SIM

- Autoridad de Juzgamiento: "JUZGADO DE FALTAS MUNICIPAL" con ID SAFIT 1575
- Dirección física: Tucumán N° 522
- Teléfono: 
- Horario de atención: 08:00 a 12:00hs
- Correo electrónico:
- Valor combustible: $ 1,00
- Nombre de la Autoridad de Constatación: Municipalidad de Viedma
- Partido al que se asocia la Autoridad de Constatación: Adolfo Alsina
- Provincia al que se asocia la Autoridad de Constatación: Rio Negro
- Archivo del Logo J05A013.pcx
- Id 05 para Rio Negro
- Código: 013
- Adhesión a la ordenanza ORDENANZA N°7557/14 VIEDMA

EL % A UTILIZAR PARA EL PAGO VOLUNTARIO ES DEL 20% Y EN ALGUNAS INFRACCIONES NO SE LE OTORGA PAGO VOLUNTARIO ES DECIR ES EL 0%.
SE CONFIGURO COMO VALOR DE COMBUSTIBLE $1, YA QUE LA ORDENANZA DE LA JURISDICCIÓN ESTABLECE MONTO FIJOS PARA LAS INFRACCIONES.

**Comment by leodimonio** [comment]
Listo, se agrego el juzgado, la autoridad de constatacion, y su correspondiente adhesion a la ordenanza ORDENANZA N°7557/14 VIEDMA, saludos.
