### ISSUE TITLE
cambiar de estado(GLPI 9679)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#380]
La licencia se encuentra anulada y el tramite aprobado, se solicita cambiar de estado.
DNI 7966706 masc. relacionada al insumo 008291816 vencimiento 24/052018

**Comment by leoimoli** [comment]
Pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO"

DNI: 7966706
Tramite: 16672344

**Comment by EliasWasinger** [comment]
Listo, se cambió de estado a vigente y trámite emitido.

Query:
`select * from tLicencias where txNroLicencia = '7966706'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '15456893'

update tTramites set txEstado = 'EMITIDO' where idTramite = '16672344'`
