### ISSUE TITLE
MODIFICAR FECHA DE NACIMIENTO(GLPI 9740)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#384]
Corregir la fecha de nacimiento en la licencia VIGENTE que indico.
N° de tramite 8638089 DNI 23082702 femen
fecha de nacimiento 26/08/1973

**Comment by EliasWasinger** [comment]
Aclaración: La licencia indicada está como NO VIGENTE, pero igualmente se cambió la fecha de nacimiento de esa licencia.

Query:
`select * from tLicencias where txNroLicencia = '23082702'

update tLicencias set fcFechaNacimientoLicencia = '1973-08-26 00:00:00.000' where idLicencia = '8151752'`
