### ISSUE TITLE
Incidente - Cambiar estado de licencia a VIGENTE (GLPI 9725)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#385]
cambiar el estado de la licencia a  "VIGENTE" y el tramite a "emitido de la licencia N° 33991945 tramite N° 1213495

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia y trámite.

Query:
`select * from tLicencias where txNroLicencia = '33991945'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '1134055'

update tTramites set txEstado = 'EMITIDO' where idTramite = '1213495'`
