### ISSUE TITLE
cambiar el estado(GLPI 9748)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#388]
Pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO".
DNI 41796263

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia y trámite.

Query:
`select * from tLicencias where txNroLicencia = '41796263'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12177370'

update tTramites set txEstado = 'EMITIDO' where idTramite = '13122475'`
