### ISSUE TITLE
Activar licencia - (GLPI 9807)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#389]
Pasar la licencia N° 37089645 a estado "VIGENTE" y el tramite N° 16805941 a estado "EMITIDO"

**Comment by EliasWasinger** [comment]
Listo, se pasaron los estados.
Query:
`select * from tLicencias where txNroLicencia = '37089645'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '15576627'

update tTramites set txEstado = 'EMITIDO' where idTramite = '16805941'`
