### ISSUE TITLE
PASAR A ESTADO NO VIGENTE - (ID 9779)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#391]
pasar la licencia N° 7800348 a estado "NO VIGENTE"

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '7800348'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1063200'`
