### ISSUE TITLE
Cambio de datos - (ID 9780)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#392]
Modificar el numero de DNI en persona y tramite y el numero de licencia N°  35176254 por el numero 35176255.

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los DNI de la persona, en la tabla personas físicas, ya existe la misma persona con ambos DNI, pero el que tiene el número incorrecto, está dado de baja.

Query:
`select * from tLicencias where txNroLicencia = '35176255'

select * from tTramites where idTramite = '12470528'

select * from tPersonasFisicas where txNumeroDocumento = '35176255' /* 35176254  */


update tPersonasFisicas set txNumeroDocumento = '35176255' where idPersonaFisica = '8465244'

update tTramites set idPersonaFisica = '10346457' where idTramite = '12470528'`
