### ISSUE TITLE
ALTA EN SIM - FAMAILLÁ - TUCUMAN - (ID 9800)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#393]
Descripción : Se solicita el Municipio de Famaillá (Tucumán) en el SIM

- Autoridad de Juzgamiento: "TRIBUNAL DE FALTAS" con ID SAFIT 1577
- Dirección física: Bartolomé Mitre 386
- Teléfono:
- Horario de atención: 08:00 a 13:00hs
- Correo electrónico:
- Valor combustible: $ 24,40
- Nombre de la Autoridad de Constatación: Municipalidad de Famaillá
- Partido al que se asocia la Autoridad de Constatación: Famaillá
- Provincia al que se asocia la Autoridad de Constatación: Tucumán
- Archivo del Logo J17A011.pcx
- Id 17 para Tucumán
- Código: 011
- Adhesión a la Ordenanza Decreto 437/11

**Comment by leodimonio** [comment]
Listo ya se agrego la autoridad, el juzgado y se adhirio al decreto solicitado, saludos.
