### ISSUE TITLE
ALTA EN SIM CONCEPCION TUCUMAN - (ID 9791)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#394]
Buen di gente por medio de la presente solicito alta del Municipio de Concepcion (Tucuman)

Descripción : Se solicita el Municipio de Concepción (Tucumán) en el SIM

- Autoridad de Juzgamiento: "JUZGADO MUNICIPAL DE FALTAS" con ID SAFIT 1578
- Dirección física: 25 de Mayo 186 Planta Alta
- Teléfono: 
- Horario de atención: 08:00 a 13:00hs
- Correo electrónico: tribunaldefaltas@concepción.gob.ar
- Valor combustible: $ 1,00
- Nombre de la Autoridad de Constatación: Municipalidad de Concepción
- Partido al que se asocia la Autoridad de Constatación: CONCEPCIÓN - CHICLIGASTA
- Provincia al que se asocia la Autoridad de Constatación: Tucumán
- Archivo del Logo J17A010.pcx
- Id 17 para Tucumán
- Código: 010
- Adhesión a la ordenanza ORDENANZA N° 1499

EL % A UTILIZAR PARA EL PAGO VOLUNTARIO CON DESCUENTO ES 0% PARA TODAS LAS INFRACCIONES.
SE CONFIGURO COMO VALOR DE COMBUSTIBLE $1, YA QUE LA ORDENANZA DE LA JURISDICCIÓN ESTABLECE MONTO FIJOS PARA LAS INFRACCIONES.

**Comment by leodimonio** [comment]
Listo, ya se agrego la autoridad, el juzgado , la ordenanza y correspondiente adhesion, aclaro el porcentaje de descuento es el mismo que esta definido en el Sinai, por ende si este esta en 0, el del sim , sera en 0, saludos.
