### ISSUE TITLE
ID para WS - (ID 9820)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#395]
Solicito ID de CEL y Localidad para el CEL de Comuna 12, de CABA.

**Comment by EliasWasinger** [comment]
COMUNA 12     ID = 561

**Comment by EliasWasinger** [comment]
Id localidad 3358


select * from tCentrosEmisionLicencias where txNombre = 'Comuna 12'

select * from tDomicilios where idDomicilio = '15351623'
