### ISSUE TITLE
reporte - (ID 9863)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#397]
Solicito informe de licencias no impresas de los siguientes municipios de la provincia de Corrientes.

Esquina
Goya
Santa Lucia

**Comment by EliasWasinger** [comment]
Listo, dejo el reporte. Hay dos CELs que solamente tienen una licencia sin imprimir (cada una).

[no impresas Corrientes.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1061832/no.impresas.Corrientes.xlsx)
