### ISSUE TITLE
Reporte Licencia Emitida - (ID 9815)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#398]
Buenos días. por favor proporcionar Licencias Emitidas por CEL y por mes desde Enero 2017 hasta la fecha en curso.
Tiene que contener los siguientes campos: 
Año
Mes 
JURISDICCION 
CEL 
Estado 
Sexo 
TOTAL

**Comment by EliasWasinger** [comment]
Listo, dejo el reporte
[licencias emitidas 2017.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1061818/licencias.emitidas.2017.xlsx)
