### ISSUE TITLE
INCIDENTE - USUARIO DUPLICADO(GLPI 1488)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#4]
Buenas tardes, se solicita modificar el usuario 34805907, ya que el mismo se encuentra duplicado en la base de datos.
datos usuario:
DNI: 34805907
NOMBRES Y APELLIDO: jesica rios
CEL: Santa Teresa, Neuquen.

EN SINALIC PRODUCCIÓN.

**Comment by EliasWasinger** [comment]
Listo, acá te dejo el script que me pediste:
`begin transaction
	delete from tPerfilesPorUsuario where idUsuario = '3659'
	begin transaction
	delete from tUsuarios where idUsuario = '3659'
commit`

**Comment by leoimoli** [comment]
Se informo por GLPI.
