### ISSUE TITLE
modificar datos de registro de licencia nacional - (ID 9903)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#403]
se solicita modificar el registro de licencia nacional perteneciente al DNI 05078377 quitando el 0 que antecede al mismo ya que no es correcto, debe quedar:

DNI 5078377 BRASESCO

**Comment by EliasWasinger** [comment]
Listo, se cambió el dni de la licencia.

Query:
`select * from tLicencias where txNroLicencia = '5078377'

update tLicencias set txNroLicencia = '5078377' where idLicencia = '1846274'`
