### ISSUE TITLE
Cambiar de estado - (ID 9952)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#404]
La licencia figura anulada y el trámite en estado Aprobado, se solicita el pase de la licencia a estado vigente
DNI 20941188 Femenino

**Comment by EliasWasinger** [comment]
Contiene dos licencias anuladas, se necesita el id del trámite.

**Comment by leoimoli** [comment]
Se realizo el pedido del dato faltante.

**Comment by leoimoli** [comment]
tramite numero: 9353348
DNI Numero: 20941188 
Fecha de emision: 01/06/2015
Estado: No vigente

**Comment by EliasWasinger** [comment]
Los datos no corresponden, la licencia emitida el 1/6/2015 se encuentra en estado anulada, pero la licencia que está asociada con estado no vigente tiene fecha de emisión el día 16/6/2017 con el mismo id de trámite, y la persona actualmente cuenta con una licencia en estado vigente emitida el día 19/6/2017, por lo que si se pasa una licencia actualmente anulada a vigente, contará con dos licencias vigentes para una misma persona.
