### ISSUE TITLE
mal la vigencia - (ID 9995)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#405]
Modificar la fucha de vencimiento del siguiente tramite

fecha de vencimiento: 05/06/2017
Numero de tramite: 6737969
DNI: 13465977

**Comment by EliasWasinger** [comment]
Listo, se cambió la fecha del trámite.
Query.
`select * from tTramites where idTramite = '6737969'

update tTramites set fcFechaVencimiento = '2017-06-05 00:00:00.000' where idTramite = '6737969'`
