### ISSUE TITLE
Cambiar estado de licencia - (ID 9980)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#407]
Pasar el tramite al estado "EMITIDO"y la licencia a estado "VIGENTE"

Numero de tramite: 16814185
Numero de licencia: 28008135

**Comment by EliasWasinger** [comment]
Se cambiaron los estados.
Query:
`select * from tLicencias where txNroLicencia = '28008135'

update tTramites set txEstado = 'EMITIDO' where idTramite = '16814185'
update tLicencias set txEstado = 'VIGENTE' where idLicencia = '15583750'`
