### ISSUE TITLE
asignar insumos - (ID 10011)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#408]
Asignar el siguiente rango de insumos al CEL franck de Santa Fe, por sistema no se puede realizar porque figuran recibidos en jurisdiccion Buenos aisres

007750251 a 007750500

**Comment by EliasWasinger** [comment]
Listo, se asignaron los insumos al cel correspondiente.

Query:
`select * from tInsumos where txNumeroInsumo = '007750251'

select * from tCentrosEmisionLicencias where txNombre = 'franck' /* 494 */
/*
juridiccion null
dsp CEL correspondiente
dsp recibido en cel
*/

update tInsumos set idJurisdiccion = NULL where txNumeroInsumo > '007750250' and txNumeroInsumo < '007750501'

update tInsumos set idCentroEmisionLicencia = '494' where txNumeroInsumo > '007750250' and txNumeroInsumo < '007750501'

update tInsumos set txEstado = 'RECIBIDO_EN_CEL' where txNumeroInsumo > '007750250' and txNumeroInsumo < '007750501'`
