### ISSUE TITLE
sinalic-cambio datos - (ID 10003)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#409]
modiicar numero de identificacion de CEL de aca pista para que permita modificar la firma de CEL, ya que por error de carga y error de sistema tienen el mismo numero que otro CEL

**Comment by EliasWasinger** [comment]
Listo, se cambió el número identificatorio a 16

Query:
`update tCentrosEmisionLicencias set txNumeroIdentificacion = '16' where idCentroEmisionLicencia = '39'`
