### ISSUE TITLE
SINAI -- REPORTE - CUPONES PAGOS SAN ANTONIO OESTE JULIO 2016(GLPI 1982)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#41]
consulta para SAO (el xls se llama SAO_Pagos2015….) de loss CUPONES pagas en JULIO con los siguientes campos:

numero_acta
fcFechaCarga
nuImportePagado
fcFechaPagoActa
txApellidoNombreFuncionario
txCargoFuncionario

**Comment by EliasWasinger** [comment]
[SAO Pagos 2016 JULIO.xlsx](https://github.com/leoimoli/Base-De-Datos/files/423021/SAO.Pagos.2016.JULIO.xlsx)
