### ISSUE TITLE
agregar subclases - (ID 10014)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#410]
Agregar las subclases aq la siguiente licencia
DNI: 34432190
Numero de tramite: 1112658
Subclases: A3; B2

**Comment by EliasWasinger** [comment]
Listo, se agregaron las subclases a la licencia.
Query:
`select * from tLicencias where txNroLicencia='34432190' /* 1037583 */

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = 1037583

select * from tClasesLicencia /* 6 10 */

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (6,1037583)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (10,1037583)`
