### ISSUE TITLE
sinalic-agregar subclases - (ID 10014)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#411]
Agregar las subclases aq la siguiente licencia
DNI: 34432190
Numero de tramite: 1112658
Subclases: A3; B2

**Comment by EliasWasinger** [comment]
Se agregaron las dos subclases a la licencia.
Query:
`select * from tLicencias where txNroLicencia='34432190'

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = '1112658'

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (6,1112658)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (10,1112658)`
