### ISSUE TITLE
SINALIC-- mal la vigencia - (ID 9995)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#413]
Modificar la fecha de vigencia de la licencia N° 13465977

fecha de vencimiento: 05/06/2017
Numero de tramite: 6737969

**Comment by EliasWasinger** [comment]
Listo, se cambió la fecha de vencimiento de la licencia
Query:
`select * from tLicencias where txNroLicencia = '13465977'

update tLicencias set fcFechaVencimiento = '2017-06-05 00:00:00.000' where idLicencia = '6406540'`
