### ISSUE TITLE
 Cargar sub clases B1 y B2 - (ID 9536)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#416]
Estimados, se solicita cargar las sub clases de licencia B1 y B2  de  CAAMAÑO FERRARO Karina Anabela DNI 23288909  ya que en SiNaLic solo figura clase B pero sin el detalle de las sub clases.

Se adjuntan escaneados DNI y licencia del ciudadano.

**Comment by EliasWasinger** [comment]
Listo, se agregó la subclase B1, pero la B2 ya la tenía asignada al trámite de la licencia que actualmente tiene vigente por lo que no se agregó nuevamente.
`
select * from tLicencias where txNroLicencia='23288909'

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = 16858895

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (9,16858895)`
