### ISSUE TITLE
Reporte Licencias Emitidas - (ID 10373)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#421]
Buenos días. por favor proporcionar Licencias Emitidas por CEL y por mes desde Enero 2017 hasta la fecha en curso.
Tiene que contener los siguientes campos: 
Año
Mes 
JURISDICCION 
CEL 
Estado 
Sexo 
TOTAL

Gracias

**Comment by EliasWasinger** [comment]
Listo, dejo el reporte de las licencias emitidas

[Licencias emitidas 2017.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1122050/Licencias.emitidas.2017.xlsx)


Query:
`
declare @FechaIni datetime
declare @FechaFin datetime
set @FechaIni = convert(datetime, '01/01/2017', 103)   -- dd/mm/yyyy 
set @FechaFin = convert(datetime, '04/07/2017', 103)  -- dd/mm/yyyy 
--select @FechaIni,@FechaFin

SELECT   
    Datepart(YEAR,dbo.tLicencias.fcFechaEmision ) as Año ,
    Datepart(MONTH,dbo.tLicencias.fcFechaEmision ) as Mes , 
    tEntidades_1.txNombre AS JURISDICCION, 
    dbo.tCentrosEmisionLicencias.txNombre AS CEL,
    dbo.tLicencias.txEstado as Estado, 
    dbo.tLicencias.txSexoLicencia as Sexo,
    COUNT(   dbo.tLicencias.idLicencia)as TOTAL
FROM         
	 dbo.tLicencias INNER JOIN
     dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite INNER JOIN
     dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia INNER JOIN
     dbo.tEntidades ON dbo.tCentrosEmisionLicencias.idEntidad = dbo.tEntidades.idEntidad INNER JOIN
     dbo.tEntidades AS tEntidades_1 ON dbo.tEntidades.idJurisdiccion = tEntidades_1.idEntidad         
WHERE
	 tLicencias.txEstado in ('VIGENTE','NO_VIGENTE') 
	 and tLicencias.fcFechaEmision BETWEEN @FechaIni AND @FechaFin
	 
GROUP BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia
ORDER BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia`
