### ISSUE TITLE
Sinalic - eliminar datos - (ID 10364)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#422]
Eliminar la siguientes licencias que fueron realizadas en la provincia de Misiones para las pruebas del nuevo diseño de la Licencia.
ELIMINAR LA LICENCIA Y EL TRAMITE
DNI : 30381024
TRAMITE: 15932122 

ELIMINAR LA LICENCIA Y EL TRAMITE
DNI : 29671501
TRAMITE: 15932121

ELIMINAR LA LICENCIA Y PASAR EL TRAMITE A ESTADO GENERADO
DNI : 27253913
TRAMITE: 15912119

**Comment by EliasWasinger** [comment]
Listo, se eliminaron las licencias y trámites.
Query:
`select * from tLicencias where txNroLicencia = '27253913' and idTramite = '15912119' /* id 14808462 */
select * from tTramites where idTramite = '15912119';
delete from tLicencias where idLicencia = '14808463';

delete from tClasesLicenciasPorTramite where idTramite = '15912119';
delete from tWorksFlowTramite where idTramite = '15912119';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '15912119');
delete from tExamenesPsicoFisico where idTramite = '15912119'
delete from tResultadosExamenTPCurso where idTramite = '15912119';

delete from tTramites where idTramite = '15912119';`
