### ISSUE TITLE
Incidente - Sinalic - Cambiar datos -( GLPI 10432)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#424]
Pasar la licecnia a estado vigente y el tramite a estado emitido Licencia: 21697986 Tramite: 6197627

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los estados solicitados.

Query:
`select * from tLicencias where txNroLicencia = '21697986'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '5898016'


select * from tTramites where idTramite = '6197627'
update tTramites set txEstado = 'EMITIDO' where idTramite = '6197627'`
