### ISSUE TITLE
Cambio de Estado Licencia - (GLPI 10244)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#425]
poner la licencia nacional en estado NO VIGENTE , DNI: 33564921 Tramite: 4409852

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '33564921'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '4144693'`
