### ISSUE TITLE
Eliminar licencia DUPLICADA - (GLPI 10514)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#428]
Eliminar la siguiente licencia, ya que se encuentra duplicada en el sistema DNI 16738016 Tramite: 13304456

**Comment by EliasWasinger** [comment]
Listo, se eliminó la licencia.
Query:
`select * from tLicencias where txNroLicencia = '16738016' and idTramite = '13304456' /* id 12349155 */

delete from tLicencias where idLicencia = '12349155';`
