### ISSUE TITLE
Pasar el tramite a estado aprobado GLPI(10610)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#434]
Pasar el tramite a estado aprobado Tramite: 12913779 DNI: 40358367

![imagen](https://user-images.githubusercontent.com/16002393/28073324-c1c7709a-662b-11e7-9fd3-2257fec912e6.png)

**Comment by EliasWasinger** [comment]
Listo, se pasó el trámite aprobado.
Query:
`select * from tTramites where idTramite = '12913779'

update tTramites set txEstado = 'APROBADO' where idTramite = '12913779'

select * from tLicencias where idTramite = '12913779'`
