### ISSUE TITLE
Sinalic - Cambiar datos - GLPI( 10610)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#436]
eliminar la clase WS y dejar solo la A21

Tramite: 12913779 DNI: 40358367

**Comment by EliasWasinger** [comment]
Se eliminó la subclase WS
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 12913779
delete from tClasesLicenciasPorTramite where idClaseLicenciaPorTramite = '53042867'`
