### ISSUE TITLE
Cargar subclases B1 y B2 - GLPI  10782

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#440]
Agregar la subclase B2 DNI: 33033609 Tramite: 3185241

**Comment by EliasWasinger** [comment]
Listo, se agregó la sublclase.
Query:
`select * from tLicencias where txNroLicencia = '33033609'



select * from tLicencias where txNroLicencia='33033609'

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = 3185241

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (10,3185241)`
