### ISSUE TITLE
Volver a estado vigente - (ID 10828)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#441]
Pasar el tramite a estado "EMITIDO" y la licencia a estado "VIGENTE"

Tramite: 13778226
DNI: 4550601

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia y del trámite.
Query:
`select * from tLicencias where txNroLicencia = '4550601'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12809138'

update tTramites set txEstado = 'EMITIDO' where idTramite = '13778226'`
