### ISSUE TITLE
Correccion de datos - (ID 10860)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#442]
Cambiar el pais emisor de documento a ARGENTINA

DNI: 25791698
Masculino

**Comment by EliasWasinger** [comment]
Listo, se cambió el país emisor a Argentina.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '25791698'

select * from tPaises

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '10510569'`
