### ISSUE TITLE
cambiar de estado - (ID 10940)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#443]
Pasar la licencia a estado "NOVIGENTE" y el tramite a estado "EMITIDO"

DNI 34122867
Tramite: 9827699

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los estados.
Query:
`select * from tLicencias where txNroLicencia = '34122867'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '9271159'

update tTramites set txEstado = 'EMITIDO' where idTramite = '9827699'`
