### ISSUE TITLE
cambiar de estado - (ID 10835)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#444]
Pasar el  licencia a estado "VIGENTE"
DNI 39199844 
Tramite 12811173

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a vigente.
Query:
`select * from tLicencias where txNroLicencia = '39199844'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '11876494'`
