### ISSUE TITLE
Cambiar datos - (ID 10941)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#445]
Se solicita pasar a estado "NOVIGENTE" la siguiente licencia.

DNI: 17757156
Tramite: 14171390

**Comment by EliasWasinger** [comment]
Listo, se pasó a no vigente.
Query:

`select * from tLicencias where txNroLicencia = '17757156'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '13198422'`
