### ISSUE TITLE
Cambiar estado de licencia a VIGENTE - (ID 10630)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#446]
Solicito pasar el tyramite a estado "EMITIDO" y la licencia a estado "VIGENTE"

DNI: 39086241
Tramite: 16668345

DNI: 8239457 
Tramite: 17085713

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los estados solicitados.
Query:
`select * from tLicencias where txNroLicencia = '8239457'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '15813166'

update tTramites set txEstado = 'EMITIDO' where idTramite = '17085713'`
