### ISSUE TITLE
Cambiar estado de licencia a VIGENTE - (ID 11113)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#447]
Se solicita cambiar el estado de licencia de Copa Hernan Abel a VIGENTE y trámite EMITIDO.

DNI : 30110611
TRAMITE : 12517949

**Comment by EliasWasinger** [comment]
Se cambió el estado del trámite y de la licencia.
Query:
`select * from tLicencias where txNroLicencia = '30110611'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12105217'

update tTramites set txEstado = 'EMITIDO' where idTramite = '12517949'`
