### ISSUE TITLE
cambiar de estado - GLPI 11192

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#452]
Pasar la licencia a estado "VIGENTE" DNI 94027623 Tramite: 12992375

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
QuerY:
`select * from tLicencias where txNroLicencia = '94027623'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12121975'`
