### ISSUE TITLE
Eliminar una licencia y tramite - GLPI 11232

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#453]
Eliminar la licencia y tramite. DNI: 40235991 tramite: 12789198

**Comment by EliasWasinger** [comment]
Listo, se eliminó licencia y trámite.
Query:
`select * from tLicencias where txNroLicencia = '40235991' and idTramite = '12789198' /* id 13792957 */

delete from tLicencias where idLicencia = '11854862';

delete from tClasesLicenciasPorTramite where idTramite = '12789198';
delete from tWorksFlowTramite where idTramite = '12789198';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '12789198');
delete from tExamenesPsicoFisico where idTramite = '12789198'
delete from tResultadosExamenTPCurso where idTramite = '12789198';

delete from tTramites where idTramite = '12789198';`
