### ISSUE TITLE
Agregar las clases - GLPID 11282

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#454]
Agregar las clases A3 y B2 al siguiente tramite y licencia DNI: 28972475 Tramite: 1272811

**Comment by EliasWasinger** [comment]
Listo, se agregaron las subclases.
Query:
`
select * from tLicencias where txNroLicencia='28972475'

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = 1272811

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (6,1272811)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (10,1272811)`
