### ISSUE TITLE
Cambiar estado de licencia a NO VIGENTE - GLPID 11518

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#457]
Pasar la licencia a "NO_VIGENTE" Tramite: 10935996 DNI: 37146292

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado.
Query:
`select * from tLicencias where txNroLicencia = '37146292'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10308265'`
