### ISSUE TITLE
Cambiar estado licencia - GLPID 11512

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#458]
Pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO" DNI: 94890792 Tramite: 17397543

**Comment by EliasWasinger** [comment]
Se cambiaron los estados.
QuerY:
`select * from tLicencias where txNroLicencia = '94890792'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16073239'

update tTramites set txEstado = 'EMITIDO' where idTramite = '17397543'`
