### ISSUE TITLE
Sinalic - eliminar datos - GLPID 11541

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#459]
Solicito eliminar del sistema la licencia y tramite, ya que fueron realizados a modo de prueba DNI: 12979035 Tramite: 17371575

**Comment by EliasWasinger** [comment]
Se eliminó trámite y licencia.
Query:
`select * from tLicencias where txNroLicencia = '12979035' and idTramite = '17371575' /* id 13792957 */

delete from tLicencias where idLicencia = '16049389';

delete from tClasesLicenciasPorTramite where idTramite = '17371575';
delete from tWorksFlowTramite where idTramite = '17371575';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '17371575');
delete from tExamenesPsicoFisico where idTramite = '17371575'
delete from tResultadosExamenTPCurso where idTramite = '17371575';

delete from tTramites where idTramite = '17371575';`
