### ISSUE TITLE
Eliminar la licencia y el tramite GLPID 11485

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#460]
Eliminar la licencia y el tramite, ya que se encuentra repetido y no permite realizar el nuevo tramite. DNI: 7007506 Tramite: 11283618

**Comment by EliasWasinger** [comment]
Listo, se eliminó licencia y trámite.
Query:
`select * from tLicencias where txNroLicencia = '7007506' and idTramite = '11283618' /* id 13792957 */

delete from tLicencias where idLicencia = '10630584';

delete from tClasesLicenciasPorTramite where idTramite = '11283618';
delete from tWorksFlowTramite where idTramite = '11283618';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '11283618');
delete from tExamenesPsicoFisico where idTramite = '11283618'
delete from tResultadosExamenTPCurso where idTramite = '11283618';

delete from tTramites where idTramite = '11283618';`
