### ISSUE TITLE
licencias no impresas CEL La Paz, pcia de Entre Ríos - GLPID 11519

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#461]
Solicito reporte de licencias no impresas CEL La Paz, pcia de Entre Ríos. Gracias. Slds

**Comment by EliasWasinger** [comment]
Dejo el reporte:
[La Paz - No impresas.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1187612/La.Paz.-.No.impresas.xlsx)
