### ISSUE TITLE
cambiar datos en persona GLPID 11384

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#462]
cambiar datos en persona 
DNI 94323840 
PAIS EMISOR ARGENTINA 
NACIONALIDAD PARAGUAY

**Comment by EliasWasinger** [comment]
Listo, se cambió el país emisor por Argentina.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '94323840' /* 312 */

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '6181491'`
