### ISSUE TITLE
asignar insumos CGPC 12 – CABA

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#463]
asignar los siguientes lotes 
008406751 a 008407000
008407001 a 008407250
008407251 a 008407500
al CGPC 12 – CABA

**Comment by EliasWasinger** [comment]
Insumos asignados.
Query:
`update [sinalic_prod].[dbo].[tInsumos] set txEstado = 'RECIBIDO_EN_CEL', idCentroEmisionLicencia = 561 where idInsumo in(SELECT [idInsumo]
      
  FROM [sinalic_prod].[dbo].[tInsumos]
  where txNumeroInsumo between 008406751 and 008407500)`
