### ISSUE TITLE
Eliminar tramite y licencia GLPID 11552

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#464]
Eliminar tramite y licencia ya que figura 2 veces en el sinalic 
DNI: 17967137 tramite: 14177349

**Comment by EliasWasinger** [comment]
Licencia y trámite eliminado.
Query:
`delete from tLicencias where idLicencia = '13176160';

delete from tClasesLicenciasPorTramite where idTramite = '14177349';
delete from tWorksFlowTramite where idTramite = '14177349';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14177349');
delete from tExamenesPsicoFisico where idTramite = '14177349'
delete from tResultadosExamenTPCurso where idTramite = '14177349';

delete from tTramites where idTramite = '14177349';`
