### ISSUE TITLE
modificar país emisor GLPID 11650

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#465]
modificar pais emison de la persona  JUAN JOSE EMANUEL GUAYMAS, DNI 40.764.840 , figura con ANGUILLA  y corresponde a ARGENTINA

**Comment by EliasWasinger** [comment]
Se cambió el país emisor.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '40764840'

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '8137486'`
