### ISSUE TITLE
cambio de estado - GLPID 11706

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#466]
Se solicita el cambio de estado de esta licencia se encuentra NO VIGENTE se debe pasar a VIGENTE DNI 34223874 fem

**Comment by EliasWasinger** [comment]
Se pasó a vigente.
Query:
`select * from tLicencias where txNroLicencia = '34223874'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '8120954'`
