### ISSUE TITLE
SINALIC -- eliminar Tramite

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#47]
Solicito la eliminación del trámite 9363179 en estado EMITIDO

**Comment by EliasWasinger** [comment]
Se eliminó, dejo la query nuevamente por si acaso

`select * from tTramites where idTramite = '9363179'
select * from tLicencias where idTramite = '9363179'


select * from tClasesLicenciasPorTramite where idTramite = '9363179'
select * from tWorksFlowTramite where idTramite = '9363179'
select * from tExamenesPsicoFisico where idTramite = '9363179'
select * from tResultadosExamenTPCurso where idTramite = '9363179'
select * from tDetallesPsicoFisico where idExamenPsicoFisico = '2380568'

begin transaction

delete from tResultadosExamenTPCurso where idResultadoExamenTPCurso = '3100280' 
delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281889' 
delete from tExamenesPsicoFisico where idExamenPsicoFisico = '2380568' 
delete from tWorksFlowTramite where idWorkFlowTramite = '6660098' 
delete from tClasesLicenciasPorTramite where idClaseLicenciaPorTramite = '38120465' 
delete from tClasesLicenciasPorTramite where idClaseLicenciaPorTramite = '38120466' 
delete from tLicencias where idLicencia = '8834039'
delete from tTramites where idTramite = '9363179' 

commit`
