### ISSUE TITLE
Base de Datos, ... Cambios en Insumos Sinalic

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#474]
Elias que tal, por favor podes pasar el siguiente rango de insumos a Libertador San Martin – Entre Rios. Están cargados a Jurisdicción y no me deja hacer la devolución a mi.

9011251 al 9012000

Cualquier cosa avisame ;)

Gracias!!

**Comment by EliasWasinger** [comment]
Listo, se asignaron los insumos al CEL.
Query:
`update [sinalic_prod].[dbo].[tInsumos] set txEstado = 'RECIBIDO_EN_CEL', idCentroEmisionLicencia = 226 where idInsumo in(SELECT [idInsumo]
      
  FROM [sinalic_prod].[dbo].[tInsumos]
  where txNumeroInsumo between 9011251 and 9012000)`

**Comment by leodimonio** [comment]
Buenísimo, muchas gracias crack !
