### ISSUE TITLE
Cambiar estado de licencia a VIGENTE - GLPID 11920

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#475]
pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO"
 Tramite:17503979 
Licencia: 26270266

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite y la licencia.
Query:
`select * from tLicencias where txNroLicencia = '26270266'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16172581'
update tTramites set txEstado = 'EMITIDO' where idTramite = '17503979'`
