### ISSUE TITLE
cambio de estado - GLPID 12069

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#476]
pasar la licencia a estado NO VIGENTE y el tramite a estado EMITIDO DNI 22215092 Tramite: 12153787

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite y de la licencia.
QuerY:
`select * from tLicencias where txNroLicencia = '22215092'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '11484829'

update tTramites set txEstado = 'EMITIDO' where idTramite = '12153787'`
