### ISSUE TITLE
Licencia anulada se necesita volver a estado vigente - GLPID 11973

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#477]
Pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO"
 Tramite: 13911454
 DNI: 20196120

**Comment by EliasWasinger** [comment]
Se cambiaron los estados.
QuerY:
`select * from tLicencias where txNroLicencia = '20196120'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '13348632'

update tTramites set txEstado = 'EMITIDO' where idTramite = '13911454'`
