### ISSUE TITLE
cambio insumos

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#478]
reasignar los siguientes insumos

Desde 8790751 hasta 8792250
Se encuentran asignados a Jurisdiccion Jujuy y deben ir para el CEL  Libertador Gral San Martin - Pcia de Jujuy

**Comment by EliasWasinger** [comment]
Se asignaron los insumos.
Query:
`update [sinalic_prod].[dbo].[tInsumos] set txEstado = 'RECIBIDO_EN_CEL', idCentroEmisionLicencia = 318 where idInsumo in(SELECT [idInsumo]
      
  FROM [sinalic_prod].[dbo].[tInsumos]
  where txNumeroInsumo between 8790751 and 8792250)`
