### ISSUE TITLE
Cambio de estado de licencia a VIGENTE - GLPID 11977

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#480]
Pasar el trmite a estado "EMITIDO" y la licencia a estado "VIGENTE" tramite 13704833 dni 16194657

**Comment by EliasWasinger** [comment]
La persona tiene dos licencias con el mismo trámite, se tomó la licencia con fecha de emisión más reciente, tienen la misma fecha pero distinta hora.
Se cambió los estados pedidos.
Query:
`select * from tLicencias where txNroLicencia = '16194657' and idTramite = '13704833'

select * from tTramites where idTramite = '13704833'

update tTramites set txEstado = 'EMITIDO' where idTramite = '13704833'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12813827'`
