### ISSUE TITLE
Cambiar estado de licencia a VIGENTE  y tramite a  EMITIDO - ID 12220

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#481]
Pasar el tramite a estado "EMITIDO" y la licencia a estado "VIGENTE" 
Tramite: 1407638
 DNI: 27594625

**Comment by EliasWasinger** [comment]
Listo, se cambiaron los estados pedidos.
Query:
`select * from tLicencias where txNroLicencia = '27594625' and idTramite = '1407638'

select * from tTramites where idTramite = '1407638'

update tTramites set txEstado = 'EMITIDO' where idTramite = '1407638'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '1319088'`
