### ISSUE TITLE
agregar la subclase - ID 12338

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#484]
agregar la subclase B1 
DNI: 27537693 
Tramite: 1063035

**Comment by EliasWasinger** [comment]
Listo, se agregó la subcalse.
QUery:
`select * from tLicencias where txNroLicencia='27537693'

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = 2923661

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (9,1063035)`
