### ISSUE TITLE
cambiar el pais emisor ID 11911

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#485]
cambiar el pais emisor del DNI 
DNI: 94292854 
Sexo: Masc 
Paraguay.

**Comment by EliasWasinger** [comment]
Se cambió el pais emisor a Paraguay.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '94292854'

select * from tPaises

update tPersonasFisicas set idPaisEmisor = '171' where idPersonaFisica = '7526364'`
