### ISSUE TITLE
cambio de país emisor - ID 12386

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#486]
cambiar pais emisor del DNI: 
DNI: 94777006 
ARGENTINA

**Comment by EliasWasinger** [comment]
Se cambió el país emisor a Argentina.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '94777006'

select * from tPaises

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '7510065'`
