### ISSUE TITLE
Incidente - Agregar subclase a licencia - ID 12534

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#487]
Agregar las Subclases B1 A21 a la siguiente licencia 
Tramite: 1370354 
DNI: 25159646

**Comment by EliasWasinger** [comment]
Listo, se agregó la subclase al trámite
QuerY:
`select * from tClasesLicenciasPorTramite where idTramite = 1370354

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (10,1370354)`
