### ISSUE TITLE
cargar subclases - ID 12437

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#488]
se solicita agregar subclases A21 B.1 Y B.2 
dni: 33483105 
Tramite: 1367949

**Comment by EliasWasinger** [comment]
Listo, se agregaron las subclases a la licencia.
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 1367949

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (4,1367949)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (9,1367949)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (10,1367949)`
