### ISSUE TITLE
sinalic - reporte - ID 12703

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#489]
Solicito reporte de los siguientes Municipios de la provincia de Mendoza, el listado debe contener la siguiente informacion.

fecha de emisión
Nombre Apellido
DNI
N° de Licencia
N° de Trámite
Domicilio

Municipios: 
Guaymallén (Mza)
Las Heras (Mza)
Maipú (Mza)

**Comment by EliasWasinger** [comment]
Reporte de qué?

**Comment by leodimonio** [comment]
es de las licencias emitidas

**Comment by EliasWasinger** [comment]
[Licencias emitidas Mendoza.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1232127/Licencias.emitidas.Mendoza.xlsx)
Se tomó como licencia emitida aquellas que tengan el estado en VIGENTE y NO VIGENTE

Query:
`SELECT        
	tCentrosEmisionLicencias.txNombre as CEL,
	tLicencias.idLicencia,
	tLicencias.fcFechaEmision as fechaEmision,
	tLicencias.fcFechaNacimientoLicencia as fechaNacimiento,
	tLicencias.fcFechaVencimiento as fechaVencimiento,
	tLicencias.idInsumo as idInsumo,
	tLicencias.idTramite,
	tLicencias.txAltura as altura,
	tLicencias.txApellidoLicencia as apellido,
	tLicencias.txBarrio as barrio,
	tLicencias.txCalle as calle,
	tLicencias.txClasesLicencia as ClaseLicencia,
	tLicencias.txCodigoPostal as codigoPostal,
	tLicencias.txDepartamento as Departamento,
	tLicencias.txEstado as Estado,
	tLicencias.txFactorSanguineo as FactorSanguineo,
	tLicencias.txLocalidad as localidad,
	tLicencias.txNacionalidad as Nacionalidad,
	tLicencias.txNombreLicencia as nombre,
	tLicencias.txNroLicencia as NroLicenciaDNI,
	tLicencias.txObservaciones as Observaciones,
	tLicencias.txPiso as Piso,
	tLicencias.txSexoLicencia as sexo,
	tLicencias.txTipoDocumento as TipoDocumento,
	tLicencias.txTipoSanguineo as TipoSanguineo
	

FROM
	tLicencias 
	INNER JOIN tTramites ON tLicencias.idTramite = tTramites.idTramite
	INNER JOIN tCentrosEmisionLicencias ON tTramites.idCentroEmisionLicencia = tCentrosEmisionLicencias.idCentroEmisionLicencia
	
	
WHERE
	tCentrosEmisionLicencias.idCentroEmisionLicencia = 495 AND
	(tLicencias.txEstado in ('VIGENTE', 'NO_VIGENTE'))
GROUP BY
	tLicencias.idLicencia,
	tLicencias.fcFechaEmision,
	tLicencias.fcFechaNacimientoLicencia,
	tLicencias.fcFechaVencimiento,
	tLicencias.idInsumo,
	tLicencias.idTramite,
	tLicencias.txAltura,
	tLicencias.txApellidoLicencia,
	tLicencias.txBarrio,
	tLicencias.txCalle,
	tLicencias.txClasesLicencia,
	tLicencias.txCodigoPostal,
	tLicencias.txDepartamento,
	tLicencias.txEstado,
	tLicencias.txFactorSanguineo,
	tLicencias.txLocalidad,
	tLicencias.txNacionalidad,
	tLicencias.txNombreLicencia,
	tLicencias.txNroLicencia,
	tLicencias.txObservaciones,
	tLicencias.txPiso,
	tLicencias.txSexoLicencia,
	tLicencias.txTipoDocumento,
	tLicencias.txTipoSanguineo,
	tCentrosEmisionLicencias.txNombre`
