### ISSUE TITLE
MODIFICACION DE ANTECEDENTE -- SINAI(GLPI 2608)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#49]
Se cargo en tipo antecedente como INHABILITACION en donde debería cargarse como ANTECEDENTE.

DNI : 32260350
NOMBRE: MALPARTIDA NAHUEL QUIMEY

**Comment by leoimoli** [comment]
El tipo de antecedente “ANTECEDENTE” no contempla el estado  inhabilitado, por lo tanto el estado debería pasar a HABILITADO.

**Comment by leodimonio** [comment]
listo cambiado el antecedente y el estado de la persona
