### ISSUE TITLE
El reporte debe contener unicamente las licencias no impresas ID 12703

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#490]
Solicito reporte de los siguientes Municipios de la provincia de Mendoza, el listado debe contener la siguiente informacion. fecha de emisión Nombre Apellido DNI N° de Licencia N° de Trámite Domicilio Municipios: Guaymallén (Mza) Las Heras (Mza) Maipú (Mza)

**Comment by EliasWasinger** [comment]
Dejo el reporte, solamente hay licencias en estado no impresas en Guaymallén.

[Licencias no impresas.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1234420/Licencias.no.impresas.xlsx)
