### ISSUE TITLE
Pasar a estado Vigente - ID 12710

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#491]
Pasar la licencia a estado "VIGENTE" 
DNI 32009600 
Tramite: 10593422

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a vigente.
QuerY:
`select * from tLicencias where txNroLicencia = '32009600'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '9985139'`
