### ISSUE TITLE
Cambiar estado licencia - ID 12849

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#492]
Pasar la licencia a estado "VIGENTE" 
DNI: 35478829 
tramite: 15735374

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
QuerY:
`select * from tLicencias where txNroLicencia = '35478829'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14726521'`
