### ISSUE TITLE
volver a estado VIGENTE - ID 12931

### ISSUE THREAD

**Issue by silvestriandres** [leoimoli/Base-De-Datos#493]
pasar licencia  al estado VIGENTE 
DNI 22784245 masculino 
n° de tramite 9620846 
MORALES HECTOR ANIBAL

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
QuerY:
`select * from tLicencias where txNroLicencia = '22784245'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '9077104'`
