### ISSUE TITLE
consulta licencia - ID 13109

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#494]
solicito que se modifique el país emisor del documento que figura cargado en el registro de persona, el mismo debe ser ARGENTINA
D.N.I.: 17.369.353 Ramirez Jose Antonio

**Comment by EliasWasinger** [comment]
Se cambió el país emisor a Argentina.
Query.
`select * from tPersonasFisicas where txNumeroDocumento = '17369353'
update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '10698112'`
