### ISSUE TITLE
CAMBIAR DE ESTADO - ID 13399

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#495]
Pasar la licencia a estado "VIGENTE" 
DNI 25676247 
TRAMITE 8289788

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado.
Query:
`select * from tLicencias where txNroLicencia = '25676247'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '7825731'`
