### ISSUE TITLE
Incidente - Sinalic - Cambiar datos - (ID 13779)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#496]
Eliminar la licencia y el tramite, ya que estan cargados 2 veces

DNI 22922839
Tramite: 14547444

**Comment by EliasWasinger** [comment]
Se eliminó licencia y trámite.
QuerY:
`select * from tLicencias where txNroLicencia = '22922839' and idTramite = '14547444' /* id 13792957 */

delete from tLicencias where idLicencia = '13529441';

delete from tClasesLicenciasPorTramite where idTramite = '14547444';
delete from tWorksFlowTramite where idTramite = '14547444';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14547444');
delete from tExamenesPsicoFisico where idTramite = '14547444'
delete from tResultadosExamenTPCurso where idTramite = '14547444';

delete from tTramites where idTramite = '14547444';`
