### ISSUE TITLE
Incidente - Pasar a estado no vigente - (ID 13565)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#498]
Pasar la licencia a estado "NO VIGENTE"

DNI 16276946	
Tramite 1522433

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '16276946'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1434961'`
