### ISSUE TITLE
Incidente - Sinalic - Cambiar datos - (ID 13763)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#499]
Eliminar la licencia y el tramite ya que fueron utilizados para pruebas del sistema

DNI: 34205126
Tramite: 68687

**Comment by EliasWasinger** [comment]
Se eliminó la persona y el trámite.
Query:
`select * from tLicencias where txNroLicencia = '34205126' and idTramite = '68687' /* id 13792957 */

delete from tLicencias where idLicencia = '56504';

delete from tClasesLicenciasPorTramite where idTramite = '68687';
delete from tWorksFlowTramite where idTramite = '68687';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '68687');
delete from tExamenesPsicoFisico where idTramite = '68687'
delete from tResultadosExamenTPCurso where idTramite = '68687';

delete from tTramites where idTramite = '68687';`
