### ISSUE TITLE
INCIDENTE -BAJA DE ACTA(GLPI 1433)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#5]
Se solicita la baja del acta N° 040300716002923 del juzgado de Cmte. Luis Piedra Buena. Se enviara memo con la respectiva nota del municipio.

Produccion SINAI.

**Comment by EliasWasinger** [comment]
Listo, se realizo baja lógica, te dejo las consultas:
`select * from tActasConstatacion where txNumeroActa = '040300716002923'

begin transaction
	update tActasConstatacion set txEstado = 'DADA_DE_BAJA' where idActaConstatacion = 328420
commit`

**Comment by leoimoli** [comment]
Se informo por GLPI.
