### ISSUE TITLE
dos licencias vigentes - (ID 13930)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#502]
Se solicita poner en estado NO VIGENTE la licencia correspondiente al DNI 35838152 N° de tramite 1586917
BOYKO RODRIGO JOAQUIN

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
Query:
`update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1489199'`
