### ISSUE TITLE
PASAR A ESTADO NO VIGENTE - (ID 14127)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#506]
Pasar la licencia a Estado NO VIGENTE

DNI: 35002904
Tramite:  10920545

**Comment by EliasWasinger** [comment]
Se pasó a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '35002904'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10292984'`
