### ISSUE TITLE
Eliminar una licencia - (ID 14244)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#507]
Pasar la licencia a estado NOVIGENTE 
DNI 25685016
Tramite: 3902431

**Comment by EliasWasinger** [comment]
Se pasó a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '25685016'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '3671283'`
