### ISSUE TITLE
Incidente - CAMBIAR DE ESTADO - (ID 14272)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#508]
Pasar la licecnia a estado VIGENTE y el tramite a estado EMITIDO

Tramite: 14398774
DNI 16854664

**Comment by EliasWasinger** [comment]
Listo, se pasó los estados solicitados.
Query:
`select * from tLicencias where txNroLicencia = '16854664' and idTramite = '14398774'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16471922'

update tTramites set txEstado = 'EMITIDO' where idTramite = '14398774'`
