### ISSUE TITLE
Incidente - Cambiar estado licencia - (ID 14690)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#509]
Cambiar estado licencia
Pasar a estado Vigente

KARINA ITATI VERON
DNI: 24702187
INSUMO: 004959077

**Comment by EliasWasinger** [comment]
Se pasó a vigente
Query:
`select * from tLicencias where txNroLicencia = '24702187'

select * from tInsumos where txNumeroInsumo = '004959077'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12628027'`
