### ISSUE TITLE
SINALIC -- USUARIOS

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#51]
Pasar a perfil Administrador
34205126

Dar de baja los siguientes usuario. Fecha de BAJA la de hoy
30136021
28806029
28016192
22870450
29235688
30516171

**Comment by EliasWasinger** [comment]
Listorti. Dejo los script:
`select * from tUsuarios where txUsuarioAD IN (
'30136021',
'28806029',
'28016192',
'22870450',
'29235688',
'30516171')

begin transaction 
	update [sinalic_prod].[dbo].tUsuarios set fcFechaBaja = '2016-08-31 09:54:000', txEstado = 'INACTIVO' where idUsuario = '679'
	update [sinalic_prod].[dbo].tUsuarios set fcFechaBaja = '2016-08-31 09:54:000', txEstado = 'INACTIVO' where idUsuario = '328'
	update [sinalic_prod].[dbo].tUsuarios set fcFechaBaja = '2016-08-31 09:54:000', txEstado = 'INACTIVO' where idUsuario = '256'
	update [sinalic_prod].[dbo].tUsuarios set fcFechaBaja = '2016-08-31 09:54:000', txEstado = 'INACTIVO' where idUsuario = '786'
	update [sinalic_prod].[dbo].tUsuarios set fcFechaBaja = '2016-08-31 09:54:000', txEstado = 'INACTIVO' where idUsuario = '166'
	update [sinalic_prod].[dbo].tUsuarios set fcFechaBaja = '2016-08-31 09:54:000', txEstado = 'INACTIVO' where idUsuario = '2449'
commit`


`begin transaction 
	update [sinalic_prod].[dbo].[tPerfilesPorUsuario] set idPerfil = '18' where idUsuario = '6'
commit`
