### ISSUE TITLE
Incidente - Licencias iguales en sistema - (ID 14510)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#510]
Estimados, solicito se elimine UNO de los dos registros que figuran en sistema
DNI: 32538241

**Comment by EliasWasinger** [comment]
Se eliminó la licencia y el trámite asociado.
Query:
`select * from tLicencias where txNroLicencia = '32538241'
/* id 11714102 tramite 12643454 */
select * from tLicencias where txNroLicencia = '11714102' and idTramite = '12643454'

delete from tLicencias where idLicencia = '11714102';

delete from tClasesLicenciasPorTramite where idTramite = '12643454';
delete from tWorksFlowTramite where idTramite = '12643454';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '12643454');
delete from tExamenesPsicoFisico where idTramite = '12643454'
delete from tResultadosExamenTPCurso where idTramite = '12643454';

delete from tTramites where idTramite = '12643454';`
