### ISSUE TITLE
Incidente - cambio de pais emisor - (ID 14684)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#511]
Se solicita el cambio de país emisor.
mencionar DNI.92.803.825
Apellido y nombre: GRANDON RODRIGUEZ, AGUSTIN ARMANDO
sexo: MASCULINO
Nro. de insumo.
solicito que se modifique el país de centro de emisor que figura Bolivia.

**Comment by EliasWasinger** [comment]
Se cambió el país emisor a Argentina.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '92803825'

select * from tPaises

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '1167500'`
