### ISSUE TITLE
Incidente - Eliminar una licencia - (ID 14814)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#512]
Eliminar la licencia duplicada y el tramite asociado del siguiente ciudadano.
DNI: 92803825

**Comment by leoimoli** [comment]
Eliminar la licencia y el tramite.

DNI: 92803825 
Tramite: 14357363

**Comment by EliasWasinger** [comment]
Se eliminó licencia y trámite.
Query:
`delete from tLicencias where idLicencia = '13347717';

delete from tClasesLicenciasPorTramite where idTramite = '14357363';
delete from tWorksFlowTramite where idTramite = '14357363';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14357363');
delete from tExamenesPsicoFisico where idTramite = '14357363'
delete from tResultadosExamenTPCurso where idTramite = '14357363';

delete from tTramites where idTramite = '14357363';`
