### ISSUE TITLE
Incidente - Cambiar estado de licencia a VIGENTE - (ID 14810)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#513]
Pasar la licencia a estado VIGENTE

DNI 32750968
TRAMITE 16075076

**Comment by EliasWasinger** [comment]
Se cambió el estado de la licencia a vigente.
Query:
`select * from tLicencias where txNroLicencia = '32750968'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14942540'`
