### ISSUE TITLE
Incidente - Sinalic - Error Producción - (ID 14796)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#514]
Modificar la vigencia (21/09/2020) ,  pasar la licencia  a estado vigente y el tramite a emitido

DNI: 41518339
Tramite: 17887539

**Comment by EliasWasinger** [comment]
Se cambió la fecha de vencimiento.
Query:
`select * from tLicencias where txNroLicencia = '41518339'

update tLicencias set fcFechaVencimiento = '2020-09-21 00:00:00.000' where idLicencia = '16519396'`
