### ISSUE TITLE
Sinalic - Cambiar datos - (ID 14955)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#516]
Modificar la fecha de vencimiento de la licencia

DNI: 41607110
Tramite: 17886375
Fecha que corresponde: 21/09/2020

**Comment by EliasWasinger** [comment]
Listo, se cambió la fecha de vencimiento.
Query:
`select * from tLicencias where txNroLicencia = '41607110'

update tLicencias set fcFechaVencimiento = '2020-09-21 00:00:00.000' where idLicencia = '16517940'`
