### ISSUE TITLE
Sinalic - Error Producción - ID 14796

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#520]
pasar la licencia  a estado VIGENTE y el tramite a EMITIDO

DNI: 41518339
Tramite: 17887539
modificar Insumo: 009592698

**Comment by EliasWasinger** [comment]
Se cambió el estado de la licencia y trámite. Se le asignó el nuevo insumo a la licencia y se cambió el estado a ASIGNADO al insumo nuevo.
Query:
`select * from tLicencias where txNroLicencia = '41518339'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16519396'
update tLicencias set idInsumo = '10191704' where idLicencia = '16519396'
update tTramites set txEstado = 'EMITIDO' where idTramite = '17887539'
update tInsumos set txEstado = 'ASIGNADO' where idInsumo = '10191704'

select * from tInsumos where txNumeroInsumo = '009592698' /* 10191704 */
`
