### ISSUE TITLE
Eliminiar Registro - ID 15001

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#522]
Anular licecnia y tramite ya que se encuentra repetida.

DNI 21461289
Tramite: 13975834

**Comment by EliasWasinger** [comment]
Se anuló la licencia y el trámite.
QuerY:
`select * from tLicencias where txNroLicencia = '21461289'

update tLicencias set txEstado = 'ANULADA' where idLicencia = '12981881'
update tTramites set txEstado = 'ANULADO' where idTramite = '13975834'`
