### ISSUE TITLE
Cambio de estado de licencia y tramite - ID 14975

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#523]
Pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO"

DNI 15108870
Tramite n 14546485

**Comment by EliasWasinger** [comment]
Se cambiaron los estados.
QuerY:
`select * from tLicencias where txNroLicencia  = '15108870'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '13693605'
update tTramites set txEstado = 'EMITIDO' where idTramite = '14546485'`
