### ISSUE TITLE
Cambiar estado de licencia - ID 14974

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#524]
Pasar la licecnia aestado NOVIGENTE

DNI: 12224364
Tramite: 12110086

**Comment by EliasWasinger** [comment]
Se pasó a no vigente.
Query.
`select * from tLicencias where txNroLicencia  = '12224364'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '11407586'`
