### ISSUE TITLE
Error Renovación - ID 14532

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#525]
DNI 4597766, MOGGIA ROBERTO RUBEN

LOS TRAMITES QUE DEBEN ELIMINARSE SON LOS SIGUIENTES:
N° 14738461;
N° 14738564;
N° 14738649

Eliminar tambien las licencias asociadas a dichos tramites

**Comment by EliasWasinger** [comment]
Se eliminaron los trámites y las licencias.
Query:
`select * from tLicencias where txNroLicencia = '4597766' and idTramite = '14738649'

delete from tLicencias where idLicencia = '13709015';

delete from tClasesLicenciasPorTramite where idTramite = '14738649';
delete from tWorksFlowTramite where idTramite = '14738649';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14738649');
delete from tExamenesPsicoFisico where idTramite = '14738649'
delete from tResultadosExamenTPCurso where idTramite = '14738649';

delete from tTramites where idTramite = '14738649';`
