### ISSUE TITLE
 Dar de baja una licencia - ID 15123

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#528]
Eliminar licencia y tramite

DNI: 22279847
Tramite: 14438131

**Comment by EliasWasinger** [comment]
Se eliminó la licencia y el trámite.
Query:
`
delete from tLicencias where idLicencia = '13424385';

delete from tClasesLicenciasPorTramite where idTramite = '14438131';
delete from tWorksFlowTramite where idTramite = '14438131';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '14438131');
delete from tExamenesPsicoFisico where idTramite = '14438131'
delete from tResultadosExamenTPCurso where idTramite = '14438131';

delete from tTramites where idTramite = '14438131';`
