### ISSUE TITLE
cambio de estado - ID 15268

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#531]
Pasar la licencia a NO VIGENTE. y el tramite a EMITIDO

DNI 36216650 masculino
N° de tramite 7063093

**Comment by EliasWasinger** [comment]
Se cambiaron los estados solicitados.
Query:
`select * from tLicencias where txNroLicencia = '36216650'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '6706566'
update tTramites set txEstado = 'EMITIDO' where idTramite = '7063093'`
