### ISSUE TITLE
PASAR A ESTADO NO VIGENTE - ID 15593

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#534]
solicito pasar a estado NO VIGENTE el siguiente registro:

documento: 35887088	numero de tramite 2598305	MANCINI	JENNIFER ELIANA EDITH

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '35887088'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '2654495'`
