### ISSUE TITLE
modificacion de clases - ID 15547

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#535]
solicito modificar las clases del siguiente registro

documento 24134534	numero de tramite	2671890	-  VIGENTE	07/04/2013	25/02/2018	A B		BIAGETTI	JUAN LUIS	 

el mismo debe poseer la A.3 y B.1, gracias.-

**Comment by EliasWasinger** [comment]
Se agregaron las subclases solicitadas.
Query:
`insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (9,2671890)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (6,2671890)`
