### ISSUE TITLE
Incidente - Cambiar estado de licencia a VIGENTE - ID 15558

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#537]
Pasar la licencia a estado VIGENTE

DNI 	25679137
TRAMITE 15643860

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
Query:
`select * from tLicencias where txNroLicencia = '25679137'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14547807'`
