### ISSUE TITLE
Incidente - Sinalic - Cambiar datos - ID 15761

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#538]
Modificar la vigencia de las siguientes licencias

DNI: 42037003
Tramite: 18002229
Vigencia: 06/10/2020

DNI: 41518199
Tramite: 17981620
Vigencia: 06/10/2020

DNI: 41607118
Tramite: 18000554
Vigencia: 06/10/2020

DNI: 42186126
Tramite: 18000911
Vigencia:06/10/2020

DNI: 41476965
Tramite: 17996903
Vigencia: 06/10/2020

DNI: 41416424
Tramite: 17993168
Vigencia: 06/10/2020

DNI: 41382962
Tramite: 17988596
Vigencia: 05/10/2020

**Comment by EliasWasinger** [comment]
Se modificaron las fechas de vencimiento de los trámites y licencias pedidas.
Query:
`select idLicencia, idTramite, fcFechaVencimiento from tLicencias where txNroLicencia = '41382962'

update tLicencias set fcFechaVencimiento = '2020-10-05 00:00:00.000' where idLicencia = '16609776'

update tTramites set fcFechaVencimiento = '2020-10-05 00:00:00.000' where idTramite = '17988596'`
