### ISSUE TITLE
Incidente - Sinalic - Cambiar datos - ID 15824

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#540]
Cambiar la vigencia de la licencia

DNI: 41415441
Tramite: 18006953
Vigencia: 09/10/2020

**Comment by EliasWasinger** [comment]
Se cambió la fecha de vencimiento del trámite y la licencia.
Query:
`select * from tLicencias where txNroLicencia='41415441'

update tLicencias set fcFechaVencimiento = '2020-10-09 00:00:00.000' where idLicencia = '16633594'
update tTramites set fcFechaVencimiento = '2020-10-09 00:00:00.000' where idTramite = '18006953'`
