### ISSUE TITLE
Incidente - Se solicita cambiar estado de licencia a VIGENTE - ID 15786	

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#542]
Pasar la licencia a estado "NOVIGENTE" y el tramite a estado "EMITIDO"

DNI: 11957593
Tramite: 14358258

**Comment by EliasWasinger** [comment]
Se cambiaron los estados solicitados.
Query:
`update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '13356274'
update tTramites set txEstado = 'EMITIDO' where idTramite = '14358258'`
