### ISSUE TITLE
Incidente - Cambiar estado licencia - ID 16066

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#543]
estimados, solicito el cambio de estado de la siguiente licencia:

dni 33447104 sexo masculino - numero de tramite 6876708	- VIGENTE - GALLEGOS CAYUN - SANTIAGO ANDRES

el mismo debe pasarse a NO VIGENTE, gracias.-

**Comment by EliasWasinger** [comment]
Listo, se pasó a no vigente
Query:
`select * from tLicencias where txNroLicencia = '33447104'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '6558807'`
