### ISSUE TITLE
SOLICITUD LICENCIAS NO IMPRESAS - CORDOBA - ID 16199

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#545]
SOLICITUD LICENCIAS NO IMPRESAS - CORDOBA 
Solicitamos detalle de licencias no impresas de los siguientes municipios:

Bell ville, marcos Juarez y villa Maria de la provincia de Cordoba.

**Comment by EliasWasinger** [comment]
Dejo el excel:
[cordoba no impresas.xlsx](https://github.com/leoimoli/Base-De-Datos/files/1399370/cordoba.no.impresas.xlsx)
