### ISSUE TITLE
volver a estado VIGENTE - ID 16458

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#546]
39974158 SOSA, ELVIO SERGIO - MASCULINO, N° insumo: 010120469
Fecha de Emisión de la licencia: 18/10/2017

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia.
QuerY:
`select * from tLicencias where txNroLicencia = '39974158'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16681751'`
