### ISSUE TITLE
Incidente - duplicado - ID 16384

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#547]
solicito que se cambien el estado de la licencia 34063161 perteneciente a Piña Gonzalo David debido a que el ciudadano concurre al establecimiento a realizar un duplicado por cambio de dato ya que extravió la misma

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado de la licencia.
Query:

`select * from tLicencias where txNroLicencia = '34063161'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '14963263'`
