### ISSUE TITLE
Agragar subclase B1  --ID 16556

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#549]
Agragar subclase B1 

DNI: 27352048
Tramite: 1371488

**Comment by EliasWasinger** [comment]
Se agregó la subclase B1 al trámite.
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 1371488

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (9,1371488)`
