### ISSUE TITLE
Cambiar estado a VIGENTE - ID 16650

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#550]
Pasar la licencia a estado "VIGENTE"

DNI: 8352386
Tramite: 10956078

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
Query:
`select * from tLicencias where txNroLicencia = '8352386'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10328442'`
