### ISSUE TITLE
No figura clase B en licencia - ID 16273

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#551]
Agregar la subclase B1

DNI 32286852 
Tramite: 2001263

**Comment by EliasWasinger** [comment]
Se agregó la subclase B1.
Query:
`select * from tLicencias where txNroLicencia='32286852'

select * from tTramites

select * from tClasesLicenciasPorTramite where idTramite = 2001263

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (9,2001263)`
