### ISSUE TITLE
agregar subclases - ID 16775

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#553]
Cargar las subclases que no figuran por sistema
RUEDA RAMIREZ JUAN N° de tramite 1886355 DNI 94275275
A2.1 y B1

**Comment by EliasWasinger** [comment]
Se asignaron las subclases al trámite.
QuerY:
`select * from tClasesLicenciasPorTramite where idTramite = 1886355

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (4,1886355)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (9,1886355)`
