### ISSUE TITLE
existen 2 licencias VIGENTES - ID 16908

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#555]
Pasar la licencia a estado "NOVIGENTE"

DNI 26768365
Tramite: 1859503

**Comment by EliasWasinger** [comment]
Se pasó el estado
Query:
`select * from tLicencias where txNroLicencia = '26768365'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1730941'`
