### ISSUE TITLE
2 licencias en estado VIGENTE - ID 16923

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#556]
DNI 25663026 N° de tramite 1796067 en estado NO VIGENTE

**Comment by EliasWasinger** [comment]
Listo, se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '25663026'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1673157'`
