### ISSUE TITLE
ANULACION DE UNA DE LAS LICENCIAS - ID 16799

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#557]
ANULA ESTA: dni 35000862 Y AL N° DE TRAMITE 13643866

**Comment by EliasWasinger** [comment]
Listo, se anuló el trámite y la licencia.
Query:
`select * from tLicencias where txNroLicencia = '35000862'

update tLicencias set txEstado = 'ANULADA' where idLicencia = '12666041'

update tTramites set txEstado = 'ANULADO' where idTramite = '13643866'`
