### ISSUE TITLE
Eliminar licencia duplicada - ID 16947

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#558]
dni 23019084 masculino
numero de tramite 11285030

**Comment by EliasWasinger** [comment]
Se eliminó la licencia y trámite.
Query:
`select * from tLicencias where txNroLicencia = '23019084' and idTramite = '11285030' /* id 10631996 */

delete from tLicencias where idLicencia = '10631996';

delete from tClasesLicenciasPorTramite where idTramite = '11285030';
delete from tWorksFlowTramite where idTramite = '11285030';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '11285030');
delete from tExamenesPsicoFisico where idTramite = '11285030'
delete from tResultadosExamenTPCurso where idTramite = '11285030';

delete from tTramites where idTramite = '11285030';`
