### ISSUE TITLE
SINALIC -- ERROR AL CARGAR OPERADOR - CAMBIO DE JURISDICCION(GLPI 2702)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#56]
El operdador Patiño Visconti, Pablo Blas Alberto DNI 37.192.597 fue cargado en San Martin - Mendoza como operador y deberia estar en San Luis - San Luis. Se solicita ese cambio ya que hubo un error al cargarlo.

**Comment by leodimonio** [comment]
listo, aclaro que esta inactivo
