### ISSUE TITLE
pcia Bs As - ID 17021

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#561]
Agregar subclase B1

DNI: 27332089
Tramite:1477758

**Comment by EliasWasinger** [comment]
Listo, se agregó la subclase B1 a la licencia.
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 1477758

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)
values (9,1477758)`
