### ISSUE TITLE
Cambiar país emisor - ID 16930

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#562]
94968410 masc 
cambiar la nacionalidad de peru a paraguay

**Comment by EliasWasinger** [comment]
Listo, se cambió la nacionalidad.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '94968410'

update tPersonasFisicas set idPaisNacionalidad = '171' where idPersonaFisica = '1793068'`
