### ISSUE TITLE
agregar subclases - ID 16951

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#563]
Se solicita agregar las subclases  A1 A2 A21 A22 A3 B1 B2 G1 G2 CORRESPONDIENTES AL DNI 13316449  M° DE TRAMITE 1863104

**Comment by EliasWasinger** [comment]
Listo, se agregaron las subclases a la licencia.
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 1863104

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (2,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (4,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (5,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (6,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (9,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (10,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (24,1863104)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite)values (25,1863104)`
