### ISSUE TITLE
Incidente - Cambiar estado licencia - ID 17274

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#564]
Pasar la licencia a estado NO_VIGENTE
DNI: 34426879 
Tramite: 11236282

**Comment by EliasWasinger** [comment]
Se pasó a no vigente
Query:
`select * from tLicencias where txNroLicencia = '34426879'
update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10653632'`
