### ISSUE TITLE
Incidente - modificar a no vigente - ID 17363

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#565]
Pasar la licencia a estado NO VIGENTE 
DNI: 7735055 
Tramite: 11203614

**Comment by EliasWasinger** [comment]
Se cambió el estado a no vigente
QUerY:
`select * from tLicencias where txNroLicencia = '7735055'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10554731'`
