### ISSUE TITLE
Cambiar País emisor - ID 17252

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#566]
Modificar nacionalidad

DNI: 92558689
Sexo: Masc
Nacionalidad: Ecuador

**Comment by EliasWasinger** [comment]
Se cambió la nacionalidad.
QuerY:
`select * from tPersonasFisicas where txNumeroDocumento = '92558689'

select * from tPaises

update tPersonasFisicas set idPaisNacionalidad = '66' where idPersonaFisica = '3614365'`
