### ISSUE TITLE
Cambiar país emisor - ID 16930

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#568]
Cambiar pais emisor.
DNI: 94968410

**Comment by EliasWasinger** [comment]
Se cambió el país emisor.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '94968410' 
update tPersonasFisicas set idPaisEmisor = '171' where idPersonaFisica = '1793068'`

**Comment by EliasWasinger** [comment]
Se volvió a cambiar el país emisor a Argentina
QuerY:
`select * from tPersonasFisicas where txNumeroDocumento = '94968410' 
update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '1793068'

select * from tPaises`
