### ISSUE TITLE
Cambiar estado de licencia a VIGENTE - ID 16965 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#569]
Pasar la licencia a estado "VIGENTE " y el tramite a estado "EMITIDO"

DNI 27894519
TRAMITE 17173410

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
Query:
`select * from tLicencias where txNroLicencia = '27894519'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16073277'`
