### ISSUE TITLE
Pasar licencia a estado NO VIGENTE - ID 17688 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#571]
Pasar a licencia "NO VIGENTE"
DNI 24.558.086 
trámite 9622350

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '24558086'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '9235103'`
