### ISSUE TITLE
se solicita cambio de estado- ID 17640 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#572]
licencia:  21871845 fem
   
tramite: 1994999  

pasa a no vigente

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
QuerY:
`select * from tLicencias where txNroLicencia = '21871845'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1851377'`
