### ISSUE TITLE
Pasar Trámite a estado APROBADO - ID 17748 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#573]
Pasar el tramite a estado "APROBADO"

DNI: 30546084
Tramite: 18206393

**Comment by EliasWasinger** [comment]
Se cambió el estado del trámite.
Query:
`select * from tTramites  where idTramite = '18206393'
update tTramites set txEstado = 'APROBADO' where idTramite = '18206393'`
