### ISSUE TITLE
Pasar a VIGENTE - ID 17830 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#574]
Pasar la licencia a estado "VIGENTE"

DNI: 29958228
Tramite: 6811929

**Comment by EliasWasinger** [comment]
Se pasó la licencia a vigente.
Query:
`select * from tLicencias  where txnroLicencia = '29958228'


update tLicencias set txEstado = 'VIGENTE' where idLicencia = '6477499'`
