### ISSUE TITLE
Pasar a estado no vigente - ID 18196 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#576]
Pasar a estado "NOVIGENTE"

Tramite: 1983977
DNI: 17277272

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '17277272'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1841078'`
