### ISSUE TITLE
Error sinalic - ID 18221 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#577]
Pasar la Licencia a estado "NOVIGENTE"

Tramite: 12027117
DNI: 39813794

**Comment by EliasWasinger** [comment]
Se pasó a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '39813794'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '11329470'`
