### ISSUE TITLE
Cambiar estado de trámite - ID 17958

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#578]
Cambiar estado de trámite
Solicitan modificar el estado del trámite de anulado a APROBADO.

TORRES, LUIS ALBERTO - DNI 36.275.522
TRAMITE 18211187

**Comment by EliasWasinger** [comment]
Se cambió el estado a aprobado.
Query:
`select * from tTramites where idTramite = '18211187'

update tTramites set txEstado = 'APROBADO' where idTramite = '18211187'`
