### ISSUE TITLE
MODIFICAR PAIS EMISOR - ID 18285

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#579]
Se autoriza a cambiar el pais emisor 
DNI 7856399 NICOLAS BENITO
Pais emisor: Argentina

**Comment by EliasWasinger** [comment]
Se cambió el país emisor a Argentina.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '7856399'
update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '6127917'`
