### ISSUE TITLE
SIM PRODUCCIÓN 1.13.7- CORRIENTES(GLPI 2753)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#58]
Se debe cambiar en la leyenda de las actas de PDA de CORRIENTES CAPITAL (JURISDICCION : CORRIENTES -DEPENDENCIA: CORRIENTES) el domicilio donde se cita a la persona. 
Domicilio anterior: Hipolito Irigoyen 1342
DOMICILIO ACTUAL: AV ARTIGAS N°1100.

**Comment by leodimonio** [comment]
listo cambiado !!!
