### ISSUE TITLE
Cambiar sexo - ID 18260

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#581]
Cambiar sexo a "Masculino"

DNI: 36124396
Tramite: 15471391

**Comment by EliasWasinger** [comment]
Se cambió el sexo a Masculino.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '36124396'
select * from tLicencias where txNroLicencia = '36124396'

update tLicencias set txSexoLicencia = 'M' where idLicencia = '14391962'
update tPersonasFisicas set txSexo = 'M' where idPersonaFisica = '9759754'`
