### ISSUE TITLE
Cambiar pais Emisor - ID 18198

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#582]
CAMBIAR PAIS EMISOR DE DOCUMENTO 

Señor Miño, Lucio Fernando DNI 26.964.802 nacionalidad Argentino

**Comment by EliasWasinger** [comment]
Se cambió la nacionalidad.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '26964802'
update tPersonasFisicas set idPaisNacionalidad = '13' where idPersonaFisica = '3264529'`

**Comment by EliasWasinger** [comment]
Se volvió a poner la nacionalidad China y país emisor como Argentina

`select * from tPersonasFisicas where txNumeroDocumento = '26964802'

update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '3264529'`
