### ISSUE TITLE
asignar subclases - ID 16735

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#583]
Agregar Subclase B1

Licencia: 31938601
Tramite: 1937633

**Comment by EliasWasinger** [comment]
Se agregó la subclase B1.
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 1937633

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (9,1937633)`
