### ISSUE TITLE
PASAR A VIGENTE - ID 18469

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#585]
Pasar la licencia a estado "VIGENTE" y el tramite a estado "EMITIDO"

DNI: 40242001 
Tramite: 18222586

**Comment by EliasWasinger** [comment]
Se cambió el estado de la licencia a vigente.
Query:
`select * from tLicencias where txNroLicencia = '40242001'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16815062'`
