### ISSUE TITLE
sinalic- cambiar datos - ID 18471

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#586]
Buen dia solicito modificar el vencimiento de la matricula N° 1889508-100
fecha cargada: 07/12/2020 
fecha que corresponde 07/12/2019

**Comment by EliasWasinger** [comment]
Se cambió la fecha de vencimiento de la matricula de la persona.
Query:

`select * from tFuncionarios where txLegajo like '%18895081-100%'

select * from dbo.tDetallesHabilitacion d where  d.idFuncionario = '6008' /* idDetalleHabilitacion = 14546 */

update tDetallesHabilitacion set fcFechaHasta = '2019-12-07 00:00:00.000' where idDetalleHabilitacion = '14546'`
