### ISSUE TITLE
Asignar sub clases - ID 18404

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#587]
Agregar subclases A21 y B1

Licencia 25290559
Tramite:1979426

**Comment by EliasWasinger** [comment]
Se agregaron las subclases a la licencia.
Query:
`insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (4,1979426)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (9,1979426)`
