### ISSUE TITLE
Error sinalic (licencias vigentes) - ID 18399

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#588]
Pasar a estado "NOVIGENTE"

Tramite: 1903426
Licencia 25502675

**Comment by EliasWasinger** [comment]
Se pasó la licencia a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '25502675'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '1889580'`
