### ISSUE TITLE
Error 2 licencias iguales - ID 18517

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#589]
Eliminar la siguiente licencia

Tramite: 11345341
Licencia: 18048849

**Comment by EliasWasinger** [comment]
Se eliminó el trámite y licencia.
Query:
select * from tLicencias where txNroLicencia = '18048849' and idTramite = '11345341' 

delete from tLicencias where idLicencia = '10690864';

delete from tClasesLicenciasPorTramite where idTramite = '11345341';
delete from tWorksFlowTramite where idTramite = '11345341';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '11345341');
delete from tExamenesPsicoFisico where idTramite = '11345341'
delete from tResultadosExamenTPCurso where idTramite = '11345341';

delete from tTramites where idTramite = '11345341';
