### ISSUE TITLE
SINALIC -- LICENCIAS EMIITIDAS(GLPI 2828)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#59]
Licencias Emitidas por CEL y por mes de Enero a Agosto 2016.
Gracias.-

**Comment by EliasWasinger** [comment]
Listo, dejo el script y el excel.
[Total Licencias por CEL en mes Agosto.xlsx](https://github.com/leoimoli/Base-De-Datos/files/461868/Total.Licencias.por.CEL.en.mes.Agosto.xlsx)

`
SELECT        
	tProvincias.txNombre as Provincia,
	qryCentrosEmisionLicenciasByProvincia.txNombre as CEL,
	COUNT(tLicencias.idLicencia) AS totalLicencias

FROM
	tLicencias 
	INNER JOIN tTramites ON tLicencias.idTramite = tTramites.idTramite
	INNER JOIN qryCentrosEmisionLicenciasByProvincia ON tTramites.idCentroEmisionLicencia = qryCentrosEmisionLicenciasByProvincia.idCentroEmisionLicencia
	INNER JOIN tProvincias ON tProvincias.idProvincia = qryCentrosEmisionLicenciasByProvincia.idProvincia
	
WHERE
	(tLicencias.fcFechaEmision BETWEEN '2016-08-01' AND '2016-09-01') AND 
	(tLicencias.txEstado = 'NO_IMPRESA') 

GROUP BY  
	qryCentrosEmisionLicenciasByProvincia.txNombre,
	tProvincias.txNombre
`

**Comment by EliasWasinger** [comment]
Nuevamente, se agregaron las fechas:

[Total Licencias por CEL desde Enero a Agosto.xlsx](https://github.com/leoimoli/Base-De-Datos/files/461967/Total.Licencias.por.CEL.desde.Enero.a.Agosto.xlsx)


SELECT        
	tProvincias.txNombre as Provincia,
	qryCentrosEmisionLicenciasByProvincia.txNombre as CEL,
	COUNT(tLicencias.idLicencia) AS totalLicencias,
	
	CONVERT(VARCHAR(10), tLicencias.fcFechaEmision, 103)  as fechaEmision

FROM
	tLicencias 
	INNER JOIN tTramites ON tLicencias.idTramite = tTramites.idTramite
	INNER JOIN qryCentrosEmisionLicenciasByProvincia ON tTramites.idCentroEmisionLicencia = qryCentrosEmisionLicenciasByProvincia.idCentroEmisionLicencia
	INNER JOIN tProvincias ON tProvincias.idProvincia = qryCentrosEmisionLicenciasByProvincia.idProvincia
	
WHERE
	(tLicencias.fcFechaEmision BETWEEN '2016-01-01' AND '2016-09-01') AND 
	(tLicencias.txEstado = 'NO_IMPRESA') 

GROUP BY  
	qryCentrosEmisionLicenciasByProvincia.txNombre,
	tProvincias.txNombre,
	tLicencias.fcFechaEmision,
