### ISSUE TITLE
Error dos licencias vigentes - ID 18515

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#590]
Solicito la eliminacion de la siguiente licencia

Tramite 2126297
Licencia: 25737495

**Comment by EliasWasinger** [comment]
Se eliminó la licencia y el trámite.
Query:
`select * from tLicencias where txNroLicencia = '25737495' and idTramite = '2126297' 

delete from tLicencias where idLicencia = '1976391';

delete from tClasesLicenciasPorTramite where idTramite = '2126297';
delete from tWorksFlowTramite where idTramite = '2126297';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '2126297');
delete from tExamenesPsicoFisico where idTramite = '2126297'
delete from tResultadosExamenTPCurso where idTramite = '2126297';

delete from tTramites where idTramite = '2126297';`
