### ISSUE TITLE
AMBIAR PAIS EMISOR DOCUMENTO - ID 18604

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#594]
cambiar pais emisor del documento a "ARGENTINA"
DNI: 94444527

**Comment by EliasWasinger** [comment]
Se cambió el país emisor a Argentina.
Query:
`select * from tPersonasFisicas where txNumeroDocumento = '94444527'
update tPersonasFisicas set idPaisEmisor = '13' where idPersonaFisica = '8021468'`
