### ISSUE TITLE
Dos licencias vigentes - ID 18795

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#595]
Pasar la licencia a estado "NOVIGENTE"

DNI: 36452010
Tramite: 8188360

**Comment by EliasWasinger** [comment]
Se pasó a no vigente.
Query:
`select * from tLicencias where txNroLicencia = '36452010'


update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '7738696'`
