### ISSUE TITLE
 Cambiar estado de licencia a ANULADA - ID 18737

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#596]
Eliminar la siguiente licencia

Tramite: 11343136
DNI: 28754775

**Comment by EliasWasinger** [comment]
Se eliminó la licencia y el trámite.
Query:
`select * from tLicencias where txNroLicencia = '28754775' and idTramite = '11343136' /* id 10688659 */

delete from tLicencias where idLicencia = '10688659';

delete from tClasesLicenciasPorTramite where idTramite = '11343136';
delete from tWorksFlowTramite where idTramite = '11343136';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '11343136');
delete from tExamenesPsicoFisico where idTramite = '11343136'
delete from tResultadosExamenTPCurso where idTramite = '11343136';

delete from tTramites where idTramite = '11343136';`
