### ISSUE TITLE
Pasar a VIGENTE - ID 18846

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#598]
Pasar la licencia a estdo "VIGENTE"

Tramite: 18173975
DNI: 20125203

**Comment by EliasWasinger** [comment]
Se pasó a vigente.
Query:
`select * from tLicencias where txNroLicencia = '20125203'

update tLicencias set txEstado = 'VIGENTE' where idLicencia = '16780384'`
