### ISSUE TITLE
Cambiar estado de trámite - ID 19381 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#599]
Pasar el tramite a estado "EMITIDO"

Tramite: 10436222
DNI 30854694

**Comment by EliasWasinger** [comment]
Se cambió el estado del trámite.
Query:

`select *from tLicencias where txNroLicencia = '30854694'

update tTramites set txEstado = 'EMITIDO' where idTramite = '10436222'`
