### ISSUE TITLE
SINALIC producción Anulación de licencia(GLPI 1377)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#6]
Fecha:

07/07/2016

CEL:

LIBERTADOR SAN MARTIN.

Usuario solicitante del CEL:

VOGEL, RAUL

Teléfono de contacto:

343 4910335

SE SOLICITA LA ANULACION DE LA LICENCIA DE:
Dni 16977904, GONZALEZ, Ruben

INSUMO 004406435

MOTIVO DE LA ANULACIÓN:

Error carga de datos

**Comment by EliasWasinger** [comment]
Se anula por sistema.
