### ISSUE TITLE
SINALIC -- modificar estado(GLPI 2816)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#60]
Pasar el estado de la siguiente licencia a "Vigente"

35418528 NO_VIGENTE RENOVACIÓN 07/06/2016 07/06/2018

**Comment by EliasWasinger** [comment]
Listo, se cambio el estado, dejo el script abajo:

`select * from tLicencias where txNroLicencia = '35418528'  ORDER BY fcFechaEmision ASC



begin transaction
	update tLicencias set txEstado = 'VIGENTE' WHERE idLicencia = '12165966'


commit`
