### ISSUE TITLE
Agregar subclases - ID 19426 (*)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#600]
Agregar clases A3 y B2 

DNI: 23539611
Tramite: 2615496

**Comment by EliasWasinger** [comment]
Se agregaron las subclases solicitadas.
Query:
`select * from tClasesLicenciasPorTramite where idTramite = 2615496

select * from tClasesLicencia

insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (6,2615496)
insert into tClasesLicenciasPorTramite (idClaseLicencia,idTramite) values (10,2615496)`
