### ISSUE TITLE
Licencia retenida - ID 19446

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#601]
Pasar a estado "NOVIGENTE"

DNI: 29281740
Tramite: 14722308

DNI: 17892144
Tramite:13072556

**Comment by EliasWasinger** [comment]
Se pasaron las licencias a no vigente.
Query:
`select *from tLicencias where txNroLicencia = '17892144'

update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '12152062'`
