### ISSUE TITLE
Dos licencias vigentes - ID 19462 

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#602]
Eliminar licencia y tramite

Tramite: 2115759
DNI: 11856052

**Comment by EliasWasinger** [comment]
Se eliminó la licencia y el trámite solicitado.
Query:
`select * from tLicencias where txNroLicencia = '11856052' and idTramite = '2115759' /* id 1967185 */

delete from tLicencias where idLicencia = '1967185';

delete from tClasesLicenciasPorTramite where idTramite = '2115759';
delete from tWorksFlowTramite where idTramite = '2115759';
delete from tDetallesPsicoFisico where idExamenPsicoFisico = (select top 1 idExamenPsicoFisico from tExamenesPsicoFisico where idTramite = '2115759');
delete from tExamenesPsicoFisico where idTramite = '2115759'
delete from tResultadosExamenTPCurso where idTramite = '2115759';

delete from tTramites where idTramite = '2115759';`
