### ISSUE TITLE
SINALIC -- Consulta(2765)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#61]
Por favor necesito los id de los siguiente Cel.

- Las Heras, Mendoza
- General Enrique Godoy, Rio Negro
- Allen, Rio Negro

**Comment by EliasWasinger** [comment]
Listo, te dejo los ID de cada CEL:

Las Heras, Mendoza, id = 517
General Enrique Godoy, Rio Negro id = 502
Allen, Rio Negro id = 519

También dejo el script, no me fijé que el id provincia sea el buscado, la query me tiró un resultado por consulta, dudo que sean otros:

`select * from tCentrosEmisionLicencias where txNombre = 'Allen'`
