### ISSUE TITLE
SINAI -- Consulta(GLPI 2893)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#65]
Por medio de la presente solicito el id de 
* Juzgado de faltas comunal de Humboldt.
* Juzgado de faltas comunal de Oliveros.
* Juzgado penal en lo Correccional, segunda secretaria de Rafaela.

**Comment by leodimonio** [comment]
Juzgado de faltas comunal de Humboldt. = el id es 836
Juzgado de faltas comunal de Oliveros. = el id es 840
Juzgado penal en lo Correccional, segunda secretaria de Rafaela. = el id es 455
