### ISSUE TITLE
SINALIC -- Cambiar estado a vigente(GLPI 2939)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#67]
Se solicita pasar a estado vigente una licencia. Se adjunta print de pantalla con datos de la licencia.

Es una licencia extranjera dni Brasil. 92389166 masculino, hubo un error el contribuyente quiere ampliar a A22. Se imprimió CAT A21, CLAUDIO ATTILA ESQUIVEL PAVAN

**Comment by EliasWasinger** [comment]
Se cambió el estado. Estaba en estado ANULADA y se pasó a VIGENTE, con fecha de emisión: 2016-09-14 09:16:07.000

Dejo la query:

`begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '13312519'
	
commit`

**Comment by EliasWasinger** [comment]
Se cambió la Licencia correcta, dejo la query:

`begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '10026251' and idTramite = '10636455'
	
commit`
