### ISSUE TITLE
SINALIC -- Reactivar Licencia (GLPI 2983)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#68]
DNI 35305991 - MASCULINO
INSUMO 005132439

POR FAVOR REACTIVAR LICENCIA YA QUE SE ANULO POR ERROR.

**Comment by EliasWasinger** [comment]
Listo, se puso la licencia en VIGENTE, dejo la query:

`select * from tInsumos where txNumeroInsumo = '005132439' /* me da idInsumo '5073194' */


select * from tLicencias where txNroLicencia = '35305991' and idInsumo = '5073194'

begin transaction
	update tLicencias set txEstado = 'VIGENTE' where txNroLicencia = '35305991' and idInsumo = '5073194'
	
commit`
