### ISSUE TITLE
SINALIC- Cambiar Pais Emisor(GLPI 1592)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#7]
Toffoli Alejandra dni 36260086. el DNI fue emitido el 08/07/2013 en Nogoyá, Entre Ríos. 

CAMBIAR PAÍS EMISOR: Lesotho por ARGENTINA

**Comment by EliasWasinger** [comment]
Ya se cambió, acá te dejo la query:

`update tPersonasFisicas set idPaisEmisor = 13 where idPersonaFisica = 8924784`
