### ISSUE TITLE
SINAI--SIM URGENTE ¡¡¡¡¡¡ALTA SIM - CHOELE CHOEL (PRODUCCION)(GLPI 3017)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#73]
Te solicito el alta de la jurisdicción Choele Choel en el SIM, la misma ya esta trabajando via SINAI con actas manuales.

DATOS CHOELE CHOEL (RIO NEGRO) – PRODUCCIÓN.
- Autoridad de Juzgamiento: "JUZGADO DE FALTAS" con ID SAFIT 1370

- Dirección física: San Martin 1327, Choele Choel, CP. 8360
- Teléfono: 02946-442225
- Horario de atención: 07:30hs 12:30hs
- Correo electrónico: asesorialegal@choelechoel.gob.ar
- Valor combustible: $ 12,72
- Nombre de la Autoridad de Constatación: Municipalidad de Choele Choel

- Partido al que se asocia la Autoridad de Constatación: Avellaneda
- Provincia al que se asocia la Autoridad de Constatación: Rio Negro
- Archivo del Logo J05A011.pcx (se adjunta)
- Id (05 para Río Negro)
- Código: 011

- Adhesión a la Ordenanza 36/2015

**Comment by leodimonio** [comment]
agregado el juzgado y su ordenanza correspondiente
