### ISSUE TITLE
SINAI 1.13.7- PROD(GLPI 2960)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#74]
Se debe cambiar el tipo de funcionario a el usuario 16853565 de administrativo a responsable de juzgamiento. El mismo corresponde a corrientes capital.
Jurisdiccion : 19-Pa$$word
Dependencia: 1914006- Sinai006

**Comment by leodimonio** [comment]
cambiado el tipo de funcionario a responsable
