### ISSUE TITLE
SINALIC- volver a estado VIGENTE(GLPI 3054)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#76]
Pasar a estado Vigente la licencia 30745717  B1 otorgado el 12/08/2013 con vencimiento 12/08/2018

**Comment by EliasWasinger** [comment]
Listo Leo, se cambio el estado a VIGENTE, dejo la query:

`select * from tLicencias where txNroLicencia = '30745717'


begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '3260694'
	
commit`
