### ISSUE TITLE
SINALIC -- informe de licencias no impresas(GLPI 3060)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#77]
Estimados, solicito reporte de licencias NO IMPRESAS de las siguientes localidades:

QUIMILI - SANTIAGO DEL ESTERO
LAMARQUE - RIO NEGRO
CHOELE CHOEL - RIO NEGRO
DARWIN - RIÓ NEGRO
LUIS BELTRAN - RIO NEGRO
RIO COLORADO - RIO NEGRO
CORONEL BELISLE - RIO NEGRO
CHIMPAY - RIO NEGRO

**Comment by EliasWasinger** [comment]
Listo, te dejo la query y el excel:

[Cantidad no impresas por CEL.xlsx](https://github.com/leoimoli/Base-De-Datos/files/482697/Cantidad.no.impresas.por.CEL.xlsx)

`declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='RÍO NEGRO';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	dbo.tCentrosEmisionLicencias.txNombre AS CEL,
	COUNT(1) as Cantidad from dbo.tLicencias


	INNER JOIN dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite
	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	INNER JOIN dbo.tPersonasFisicas ON dbo.tTramites.idPersonaFisica = dbo.tPersonasFisicas.idPersonaFisica
	INNER JOIN dbo.tCategoriasLicencia ON dbo.tTramites.idCategoriaLicencia = dbo.tCategoriasLicencia.idCategoriaLicencia
	INNER JOIN dbo.tTiposDocumento ON dbo.tPersonasFisicas.idTipoDocumento = dbo.tTiposDocumento.idTipoDocumento
	
WHERE 
	dbo.tCentrosEmisionLicencias.txNombre = 'CHIMPAY' and 
	ttramites.idCentroEmisionLicencia 
		IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))
       AND tLicencias.txEstado = 'NO_IMPRESA'
GROUP BY
	dbo.tCentrosEmisionLicencias.txNombre
ORDER  BY 
	dbo.tCentrosEmisionLicencias.txNombre
`
