### ISSUE TITLE
SINALIC -- asignar insumo(GLPI 3086)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#78]
Solicito asignar el siguiente insumo ya que la licencia se encuentra vencida y por sistema no lo permite.

Licencia N° 12524993
fecha de emision 04/05/2015
fecha de vencimiento 04/05/2016
insumo a asignar 003899115

**Comment by EliasWasinger** [comment]
Listo Leo, te dejo la query:
`select * from tLicencias where txNroLicencia = '12524993' /* id 8750081 */


select * from tInsumos where txNumeroInsumo = '003899115' /* id = 3914497 */


begin transaction
	update tLicencias set idInsumo = 3914497 where idLicencia = '8750081'
	
commit`
