### ISSUE TITLE
SINALIC Eliminar Licencia

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#8]
Se debera corroborar el estado de las siguientes licencias y las mismas deberán ser eliminadas de la base de datos. Estas licencias fueron utilizadas como casos de prueba en la puesta en producción de la versión 1.7.6

34205126 F (cel Santa Rosa)
32208573 F (cel Añatuya)
18904258 F (cel Parana)

**Comment by EliasWasinger** [comment]
Listo, te dejo el código bardo:

`

select * from tClasesLicenciasPorTramite where idTramite = '13397308'

select * from tWorksFlowTramite where idTramite = '13397308'

select * from tExamenesPsicoFisico where idTramite = '13397308'

select * from tResultadosExamenTPCurso where idTramite = '13397308'

select * from tDetallesPsicoFisico where idExamenPsicoFisico = '2380568'

begin transaction
	


	delete from tResultadosExamenTPCurso where idResultadoExamenTPCurso = '3100280'
	delete from tResultadosExamenTPCurso where idResultadoExamenTPCurso = '3100285'
	delete from tResultadosExamenTPCurso where idResultadoExamenTPCurso = '3100286'
	
		
		
	delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281889'
	delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281890'
	delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281891'
	delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281892'
	delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281893'
	delete from tDetallesPsicoFisico where idDetallePsicoFisico = '14281894'
	
	delete from tExamenesPsicoFisico where idExamenPsicoFisico = '2380568'
	
		delete from tWorksFlowTramite where idWorkFlowTramite = '6660095'
	delete from tWorksFlowTramite where idWorkFlowTramite = '6660096'
	delete from tWorksFlowTramite where idWorkFlowTramite = '6660097'
	delete from tWorksFlowTramite where idWorkFlowTramite = '6660098'
	
		delete from tClasesLicenciasPorTramite where idClaseLicenciaPorTramite = '55147259'
	delete from tClasesLicenciasPorTramite where idClaseLicenciaPorTramite = '55147260'
	

	

	
	delete from tLicencias where idLicencia = '12436766'
	
		delete from tTramites where idTramite = '13397308'
	
	commit
	
	`
