### ISSUE TITLE
SINALIC -- reactivar tramite aprobado(GLPI 3279)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#84]
REACTIVAR LOS TRAMITES ANULADOS:
DNI 11150231 MASCUL
DNI 27172071 FEMENINO

1) Buscar en la tabla persona por el dni indicado y sacar el id de la persona
2) Con el id de la persona buscar en la tabla tramites

**Comment by EliasWasinger** [comment]
Listo, se pasaron los trámites a APROBADO, te dejo las query:

`select * from tPersonasFisicas where txNumeroDocumento = '11150231' /* idpersona 9325923 */

select * from tPersonasFisicas where txNumeroDocumento = '27172071' /* idpersona 9353634 */

select * from tTramites where idPersonaFisica = '9325923' /* idTramite 14450998 */

select * from tTramites where idPersonaFisica = '9353634' /* idTramite 14516466 */


begin transaction 
	update tTramites set txEstado = 'APROBADO' where idTramite = '14450998'
	
	update tTramites set txEstado = 'APROBADO' where idTramite = '14516466'
	
commit`
