### ISSUE TITLE
SINALIC -- Numero de licencias emitidas (GLPI 3281)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#86]
solicito en numero de licencias emitidas de la provincia de rió negro en su totalidad desde sus comienzos al día de hoy

**Comment by EliasWasinger** [comment]
Leo, la cantidad de licencias emitidas (contadas según el estado de trámite como EMITIDO) son: 110273

Te dejo la query (mucho no me cierra el número):

`declare @idJurisdiccion int, @provincia varchar(20);
set @provincia='RÍO NEGRO';
set @idJurisdiccion=(SELECT TOP 1 [idEntidad] FROM [sinalic_prod].[dbo].[tEntidades] WHERE [txNombre]=@provincia and [idJurisdiccion] is NULL);

SELECT 
	COUNT(1) as Cantidad from dbo.tTramites


	INNER JOIN dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia
	
WHERE 
	ttramites.idCentroEmisionLicencia 
	IN (SELECT idCentroEmisionLicencia FROM   tCentrosEmisionLicencias WHERE  idEntidad IN (SELECT idEntidad FROM   tEntidades WHERE  idJurisdiccion = @idJurisdiccion))
    AND tTramites.txEstado = 'EMITIDO'
`
