### ISSUE TITLE
SIM V.1.13.7-PROD(GLPI 3282)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#88]
Se debe cambiar el porcentaje de descuento al 40% en el Municipio de Choele Choel -Rio Negro, el cual trabaja con la ord. municipal 36/15.

**Comment by leodimonio** [comment]
modificada todas las infracciones que corresponden a la adhesion de la ordenanza 36/15 del municipio Choele Choel -Rio Negro, al 40 %
