### ISSUE TITLE
SINAI -- No tiene ningún auto y el dominio que figura en la infracción lo desconoce(GLPI 3289)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#89]
Sres.:
Solicito por favor la corrección de la infracción que figura en la boleta del CENAT, motiva dicho pedido que el Sr Rodríguez nunca fue a Entre Ríos ya que cuida a sus hijos permanentemente y además porque no tiene trabajo.
El necesita tramitar la licencia para motos por un trabajo que le ofrecieron y debido a este problema que nos enteramos hoy al imprimir la boleta, se complica el tema del trabajo.
Por otro lado, no tiene ningún auto y el dominio que figura en la infracción lo desconocemos. Por favor les pido si pueden solucionarlo. Consideramos que se trata de un error de tipeo en el DNI.-
Gracias
Doy Fe..-
Luz Jopia
DNI 14.101.468
TS en Seguridad Social
Lic. en Trabajo Social

**Comment by leodimonio** [comment]
no figura en la base de datos del SINAI esta persona
