### ISSUE TITLE
SINALIC Consulta Producción

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Base-De-Datos#9]
Por favor pasarme los siguientes datos (IdLicencia -- idTramite -- idInsumo) de esta licencia.
Nro.Licencia = 8342797
Estado: Anulada

**Comment by EliasWasinger** [comment]
Acá te dejo los datos de la licencia 8342797 de SCATOLON	JOSE OSCAR:
idLicencia: 12586812
idTramite: 13558925
idInsumo: 6313897
