### ISSUE TITLE
SINALIC -- cambiar de estado(GLPI 3355)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#91]
Solicitamos que se cambie el estado a EMITIDO
NÚMERO TRÁMITE SINALIC 10485923

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado del trámite, dejo la query:

`select * from tTramites where idTramite = '10485923'

begin transaction
	update tTramites set txEstado = 'EMITIDO' where idTramite = '10485923'
	
commit`
