### ISSUE TITLE
SINALIC - Error en aprobación de trámite (GLPI 3345)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#92]
para la persona Menendez Cynthia Renne con DNI 26914118 , modificar la vigencia de 3 a 5 años, el tramite se encuentra en estado aprobado

**Comment by EliasWasinger** [comment]
Se cambió los años de vigencia a 5 años. Dejo la query:

`select * from tLicencias where txNroLicencia = '26914118'

select * from tPersonasFisicas where txNumeroDocumento = '26914118' /* idPersonaFisica 9312164 */

select * from tTramites where idPersonaFisica = '9312164' /* idTramite 14415628 */

begin transaction
	update tTramites set nuVigenciaMaxima = '5' where idTramite = '14415628'
	
commit`
