### ISSUE TITLE
SINALIC - Reactivar tramite (GLPI 3386)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#93]
cambiar el estado al N° DE TRAMITE: 14081687 a APROBADO,

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado a APROBADO, dejo la query:

`select * from tTramites where idTramite = '14081687'


begin transaction
	update tTramites set txEstado = 'APROBADO' where idTramite = '14081687'
	
commit`
