### ISSUE TITLE
SINALIC - informe (GLPI 3460)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#94]
solicito el detalle de las licencias no impresas de los siguientes municipios de la provincia de Salta:

Salta Capital
El Galpon
Rosario de la Frontera.

**Comment by EliasWasinger** [comment]
Listo, dejo el excel con las licencias de los tres municipios, junto con la query.

[Detalle de las licencias no impresas.xlsx](https://github.com/leoimoli/Base-De-Datos/files/513860/Detalle.de.las.licencias.no.impresas.xlsx)

`SELECT        
	tCentrosEmisionLicencias.txNombre as CEL,
	tLicencias.idLicencia,
	tLicencias.fcFechaEmision as fechaEmision,
	tLicencias.fcFechaNacimientoLicencia as fechaNacimiento,
	tLicencias.fcFechaVencimiento as fechaVencimiento,
	tLicencias.idInsumo as idInsumo,
	tLicencias.idTramite,
	tLicencias.txAltura as altura,
	tLicencias.txApellidoLicencia as apellido,
	tLicencias.txBarrio as barrio,
	tLicencias.txCalle as calle,
	tLicencias.txClasesLicencia as ClaseLicencia,
	tLicencias.txCodigoPostal as codigoPostal,
	tLicencias.txDepartamento as Departamento,
	tLicencias.txEstado as Estado,
	tLicencias.txFactorSanguineo as FactorSanguineo,
	tLicencias.txLocalidad as localidad,
	tLicencias.txNacionalidad as Nacionalidad,
	tLicencias.txNombreLicencia as nombre,
	tLicencias.txNroLicencia as NroLicenciaDNI,
	tLicencias.txObservaciones as Observaciones,
	tLicencias.txPiso as Piso,
	tLicencias.txSexoLicencia as sexo,
	tLicencias.txTipoDocumento as TipoDocumento,
	tLicencias.txTipoSanguineo as TipoSanguineo
	

FROM
	tLicencias 
	INNER JOIN tTramites ON tLicencias.idTramite = tTramites.idTramite
	INNER JOIN tCentrosEmisionLicencias ON tTramites.idCentroEmisionLicencia = tCentrosEmisionLicencias.idCentroEmisionLicencia
	
	
WHERE
	tCentrosEmisionLicencias.txNombre = 'ROSARIO DE LA FRONTERA' AND
	(tLicencias.txEstado = 'NO_IMPRESA') 

GROUP BY
	tLicencias.idLicencia,
	tLicencias.fcFechaEmision,
	tLicencias.fcFechaNacimientoLicencia,
	tLicencias.fcFechaVencimiento,
	tLicencias.idInsumo,
	tLicencias.idTramite,
	tLicencias.txAltura,
	tLicencias.txApellidoLicencia,
	tLicencias.txBarrio,
	tLicencias.txCalle,
	tLicencias.txClasesLicencia,
	tLicencias.txCodigoPostal,
	tLicencias.txDepartamento,
	tLicencias.txEstado,
	tLicencias.txFactorSanguineo,
	tLicencias.txLocalidad,
	tLicencias.txNacionalidad,
	tLicencias.txNombreLicencia,
	tLicencias.txNroLicencia,
	tLicencias.txObservaciones,
	tLicencias.txPiso,
	tLicencias.txSexoLicencia,
	tLicencias.txTipoDocumento,
	tLicencias.txTipoSanguineo,
	tCentrosEmisionLicencias.txNombre`
