### ISSUE TITLE
SINALIC - Reporte Licencia Emitida (GLPI 3461)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#95]
Licencias Emitidas por CEL y por mes de Enero a Septiembre 2016.
(Es el mismo reporte que pedia Horacio cada principio de mes).
Tiene que contener los siguientes campos:
Año
Mes	
JURISDICCION	
CEL	
Estado	
Sexo	
TOTAL

**Comment by EliasWasinger** [comment]
Listo, dejo reporte y query:

[Reporte Licencia Emitida.xlsx](https://github.com/leoimoli/Base-De-Datos/files/514359/Reporte.Licencia.Emitida.xlsx)


`use sinalic_prod

declare @FechaIni datetime
declare @FechaFin datetime
set @FechaIni = convert(datetime, '01/01/2016', 103)   -- dd/mm/yyyy 
set @FechaFin = convert(datetime, '01/10/2016', 103)  -- dd/mm/yyyy 
--select @FechaIni,@FechaFin

SELECT   
    Datepart(YEAR,dbo.tLicencias.fcFechaEmision ) as Año ,
    Datepart(MONTH,dbo.tLicencias.fcFechaEmision ) as Mes , 
    tEntidades_1.txNombre AS JURISDICCION, 
    dbo.tCentrosEmisionLicencias.txNombre AS CEL,
    dbo.tLicencias.txEstado as Estado, 
    dbo.tLicencias.txSexoLicencia as Sexo,
    COUNT(   dbo.tLicencias.idLicencia)as TOTAL
FROM         
	 dbo.tLicencias INNER JOIN
     dbo.tTramites ON dbo.tLicencias.idTramite = dbo.tTramites.idTramite INNER JOIN
     dbo.tCentrosEmisionLicencias ON dbo.tTramites.idCentroEmisionLicencia = dbo.tCentrosEmisionLicencias.idCentroEmisionLicencia INNER JOIN
     dbo.tEntidades ON dbo.tCentrosEmisionLicencias.idEntidad = dbo.tEntidades.idEntidad INNER JOIN
     dbo.tEntidades AS tEntidades_1 ON dbo.tEntidades.idJurisdiccion = tEntidades_1.idEntidad         
WHERE
	 tLicencias.txEstado in ('VIGENTE','NO_VIGENTE') 
	 and tLicencias.fcFechaEmision BETWEEN @FechaIni AND @FechaFin
	 
GROUP BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia
ORDER BY
	Datepart(YEAR,dbo.tLicencias.fcFechaEmision ),
	Datepart(MONTH,dbo.tLicencias.fcFechaEmision ),
	tEntidades_1.txNombre,
	dbo.tCentrosEmisionLicencias.txNombre, 
	dbo.tLicencias.txEstado, 
	dbo.tLicencias.txSexoLicencia`
