### ISSUE TITLE
SINALIC - Cambiar estado de licencia (GLPI 3498)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#96]
Cambiar el estado a "VIGENTE" la licencia perteneciente a Ricardo Omar Dimarsico con DNI 8308152, con fecha de emisión 12/08/2016 y con vto 12/08/2017

**Comment by EliasWasinger** [comment]
Listo, se modificó el estado de la licencia, dejo la query:

`begin transaction
	update tLicencias set txEstado = 'VIGENTE' where idLicencia = '12846918'
	
commit`
