### ISSUE TITLE
SINALIC - volver a tramite aprobado (GLPI 3538)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#97]
Pasar a estado aprobado el estado de un tramite anulado, los datos son:
OLDRA, SANTIAGO MARTIN
DNI 34073808
FECHA NAC. 06/08/1988
Nro de insumo: 006668163

**Comment by EliasWasinger** [comment]
Listo, se pasó el estado a APROBADO, dejo la query:

`select * from tLicencias where txNroLicencia = '34073808'


select * from tTramites where idTramite = '14636888'

begin transaction

	update tTramites set txEstado = 'APROBADO' where idTramite = '14636888'
	
commit`
