### ISSUE TITLE
SINALIC - volver a estado aprobado (GLPI 3536)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#98]
cambiar a estado aprobado el ultimo tramite anulado de esta persona. con DNI 36737564 sexo femenino

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado, tenía una sola licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '36737564' /*id13599462*/



begin transaction

	update tLicencias set txEstado = 'APROBADO' where idLicencia = '13599462'
	
commit`

**Comment by leodimonio** [comment]
SE ACTUALIZO EL TRAMITE NO LA LICENCIA
