### ISSUE TITLE
SINALIC - Cambiar estado de licencia (GLPI 3635)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Base-De-Datos#99]
SOLICITO MODIFICAR EL ESTADO DE LICENCIA DEL SEÑOR PUENTES, DAVID
DNI: 14759983
N° DE TRAMITE: 10672730
N° DE INSUMO: 004457360
SE ENCUENTRA EN ESTADO "ANULADO" Y NECESITO QUE ESTE "NO_VIGENTE", GRACIAS.-

**Comment by EliasWasinger** [comment]
Listo, se cambió el estado a la licencia, dejo la query:

`select * from tLicencias where txNroLicencia = '14759983' /* 10059504 */

begin transaction
	update tLicencias set txEstado = 'NO_VIGENTE' where idLicencia = '10059504'
	
commit`
